### ISSUE TITLE
Problems with carousel! Please anyone can help me?

### ISSUE THREAD

**Issue by maxinelobato** [vercel/commerce#1001]
Hello everyone, how are you doing? I'm new to Shopify and I'm having some difficulty setting up the carousel on the homepage of my e-commerce store. If anyone could help me, I would be truly grateful!

**Comment by leerob** [comment]
Can you be more specific what the issue is why the carousel in this template? 🙏

**Comment by leerob** [comment]
Closing out, but happy to revisit.
