### ISSUE TITLE
Suggestion: Adding support for Starter Plan in Shopify

### ISSUE THREAD

**Issue by stephyswe** [vercel/commerce#1006]
I like to take the time to give a warm CONGRATULATIONS! what a massive achievement to bring ecommerce to latest next version. Thank you so much! 

While It is great to use all features that Shopify has to offer in this template. 

It would be if possible very appreciative to add a version where you can start with 5$ plan in Shopify. 

Try your shop out and have a few months to customize it before adding a more robust plan like 30 dollar per month

As for myself, I'm gonna try doing one myself, using the older ecommerce template as ground work. 
Would it be possible? And if so, what parts in this new version require the more expensive plan?

**Comment by leerob** [comment]
I am not sure if this is possible (not a Shopify expert) but maybe someone else can chime in who has more experience 🙏

**Comment by manovotny** [comment]
@stephyswe I don't believe this is possible as Shopify's Starter plan doesn't allow for custom theme installation. https://github.com/vercel/commerce/pull/1040

**Comment by stephyswe** [comment]
> @stephyswe I don't believe this is possible as Shopify's Starter plan doesn't allow for custom theme installation. https://github.com/vercel/commerce/pull/1040


I made it work but there's more boilerplate ofc.

**Comment by manovotny** [comment]
@stephyswe care to share more? I perfectly ok being wrong and open to considering changes that may make it possible.
