### ISSUE TITLE
`fetch` revalidation and path revalidation

### ISSUE THREAD

**Issue by kristojorg** [vercel/commerce#1009]
This app uses path-level revalidation, setting `revalidate = 43200` on paths like [`/app/[page]/page.tsx`](https://github.com/vercel/commerce/blob/main/app/%5Bpage%5D/page.tsx#LL9C56-L9C56). However, it also sets `revalidate: 900` in the [`shopifyFetch`](https://github.com/vercel/commerce/blob/main/lib/shopify/index.ts#LL78C26-L78C26) function. From my read on the docs, the lowest value would always be used, so all pages depending on `shopifyFetch` would actually be revalidated every 15 minutes. In that vase, what is the purpose of the `revalidate = 43200` on the path level?

**Comment by kristojorg** [comment]
In addition, the shopify GraphQL requests use the `POST` method, which seemingly invalidates the `revalidate` and default `cache: "force-cache"` behavior. So it seems these requests would not be cached at all. Should we consider a lint/typescript/build time warning when trying to add cache and revalidation parameters to fetch requests that use POST?

**Comment by leerob** [comment]
Yeah, it seems like the `43200` one could be removed.

Where are you seeing `POST` not being cached with `force-cache`?

**Comment by leerob** [comment]
Docs should be updated now!
