### ISSUE TITLE
Convert to use Server Actions

### ISSUE THREAD

**Issue by leerob** [vercel/commerce#1011]
There are few places in this codebase that could utilize Server Actions, including the new support for optimistic UI:

https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions

**Comment by leerob** [comment]
Set cookies in a Server Action: https://github.com/vercel/commerce/blob/main/components/cart/button.tsx#L22-L33

**Comment by adamlaz** [comment]
@leerob what other places? 😬

**Comment by leerob** [comment]
Anywhere in this repo where we're inserting/updating/deleting data through event handlers and API Routes currently.

**Comment by manovotny** [comment]
Waiting on the following downstream bug fixes. 

* https://github.com/vercel/next.js/issues/50697
* https://github.com/vercel/next.js/issues/50099
