### ISSUE TITLE
Switch from time-based ISR to on-demand revalidation

### ISSUE THREAD

**Issue by leerob** [vercel/commerce#1013]
Currently, fetches to Shopify use ISR with a 15 minute window. We could now use `revalidatePath` and `revalidateTag` in combination with Shopify webhooks. 

https://nextjs.org/docs/app/building-your-application/data-fetching/revalidating#using-on-demand-revalidation

**Comment by itsanishjain** [comment]
This is something I am gonna try to add to my project and see if I am contributing back to this project, this project is a gem. thanks Vercel team

**Comment by manovotny** [comment]
This is something we're also planning on working on over the next week or two.

**Comment by itsanishjain** [comment]
Yeah seems caching creates so many problems here. I just changed to 60 secs, because my store owner quite freq play with Shopify collections, and it's messed up things.

this change can be huge.

**Comment by manovotny** [comment]
Some additional resources (so they're not just floating around in my open tabs).

* Prior art (in private repo), [PR#120](https://github.com/vercel/commerce-2.0/pull/120) and [PR#122](https://github.com/vercel/commerce-2.0/pull/122)
* [Shopify webhooks overview](https://shopify.dev/docs/apps/webhooks)
* [Shopify webhooks best practices](https://shopify.dev/docs/apps/webhooks/best-practices)
* [Shopify webhook event topics](https://shopify.dev/docs/api/admin-rest/2022-04/resources/webhook#event-topics)
* [Next.js — Using On-Demand Revalidation](https://nextjs.org/docs/app/building-your-application/data-fetching/revalidating#using-on-demand-revalidation)
* For the README... Where in the Shopify admin to add webhooks: `https://[shop]/admin/settings/notifications`
