### ISSUE TITLE
/product/${product.handle} not resolving for linked instagram/facebook stores 

### ISSUE THREAD

**Issue by Seyaji** [vercel/commerce#1025]
The SEO and product link for shopify products is by default `/products/*item*` 
This template uses `/product/*item*`
This is not an issue when routing traffic internally on the vercel hosted site but when linking from an external integration (like instagram) the link will return a 404. 

I did not find a way to change the default product URL on Shopify , although there may be a way.

This is an issue when trying to handle multiple sales channels that feed the website.

**Comment by leerob** [comment]
https://github.com/vercel/commerce/pull/1026#issuecomment-1556291798
