### ISSUE TITLE
Redirect on checkout to 404

### ISSUE THREAD

**Issue by Seyaji** [vercel/commerce#1027]
I'm having an issue when attempting to checkout. 
Instead of getting routed to shopify checkout I'm getting sent back to a 404..
It seems like this guy had the same issue and solved it: https://community.shopify.com/c/technical-q-a/unintended-headless-checkout-redirect-on-partner-development/m-p/1906361

I understand his explanation but I'm still investigating how to implement his fix... 
Any help would be appreciated.

**Comment by itsanishjain** [comment]
Well can you check the URL for checkout you SHOPIFY_DOMAIN/checkouts so if you change anything that's create the issue, because base code is working fine

**Comment by Seyaji** [comment]
@itsanishjain 
https://motifmotive.com/
The checkout URL looks good, and The only changes I have made to the template so far have been styling/cosmetic.

**Comment by itsanishjain** [comment]
Confused your site redirect to https://motifmotive.com/cart/c/c1-f2f8e2e43b80b984568e8575d2039580

/cart when you do checkouts
usually default we redirect to /checkouts 

but you can look into custom redirects here, it might be useful 
https://github.com/instantcommerce/shopify-headless-theme

**Comment by Seyaji** [comment]
Will check it out, the vercel demo uses cart also?
<img width="534" alt="Screenshot 2023-05-23 at 20 44 36" src="https://github.com/vercel/commerce/assets/67058118/e09547e3-77c9-4b64-8072-ecbc10f3432a">

**Comment by Seyaji** [comment]
**Solved**
When using your own domain you have to set shopify_domain.myshopify.com to be the primary domain otherwise it will just redirect back to your headless store that has no checkout.
