### ISSUE TITLE
npm install wasn't working 

### ISSUE THREAD

**Issue by provinit** [vercel/commerce#1031]
It was throwing the error.
error - 
```
[npm ERR! △  @vercel/git-hooks: installing base hook to filepath\commerce\.git\hooks
npm ERR! node:internal/fs/utils:347
npm ERR!     throw err;](url)
```

solution - 
deleted the "pre-commit.sample" file from ".git/hooks/" 

and it worked!

is there anyone who's facing this error or just me?

**Comment by provinit** [comment]
solution -
deleted the "pre-commit.sample" file from ".git/hooks/"

and it worked!

is there anyone who's facing this error or just me?

**Comment by kVarunkk** [comment]
Hi @provinit, I'm still facing this issue after trying the solution you mentioned. Anything which can help me?
