### ISSUE TITLE
Help Deployment Issue: Adding Static Page to Vercel/Next.js App Without Shopify CMS API

### ISSUE THREAD

**Issue by vivacoda** [vercel/commerce#1032]
I am attempting to add a new static page to my application without using the Shopify CMS API. Everything is working fine on my local build as well as in Vercel.

Here's the process I've followed: 

1. I cloned the repository from https://github.com/vercel/commerce.
2. In the application directory, I removed the existing '[page]' folder. 
3. I then created a new folder named 'my-page'. 
4. I added a 'page.tsx' file into this 'my-page' folder.

While this setup works perfectly in the development environment, I'm encountering difficulties when attempting to deploy.
Application error: a client-side exception has occurred (see the browser console for more information).' Digest: 898870660. Does anyone have an idea?

**Comment by itsanishjain** [comment]
`[page]` see there is [] used for dynamic routes, I don't understand your use case, but if you want dynamic routes like 
/slug/page1 you need [] for my-page - [my-page]

**Comment by manovotny** [comment]
@vivacoda seems to work just fine. See #1044.
