### ISSUE TITLE
vercel/commerce setup on vercel 

### ISSUE THREAD

**Issue by kaus-1296** [vercel/commerce#1033]
I was proceeding with the integration of vercel/commerce with shopify, but on configure project section, I faced the issue of not getting the values of **SHOPIFY_REVALIDATION_TOKEN**, others two I have the values. Can you please draw attention on it
![Screenshot 2023-05-25 173236](https://github.com/vercel/commerce/assets/105623408/b5ac03b8-1f18-4b32-a017-5dd124dcda7e)

**Comment by itsanishjain** [comment]
SHOPIFY_REVALIDATION_TOKEN where this token is mentioned?

**Comment by kaus-1296** [comment]
The thing is when I went to the Vercel/commerce, I wanted to use the boiler plate on it for the deployment. So on the procedure I came across the configuration Project. On that there were three options, the values of the first and the last ones I have. But for the **SHOPIFY_REVALIDATION_TOKEN** ,
 I am not having the values. I am facing this issue for the deployment process.

First I went to the vercel and choose one of the boiler plates -
![Step1-marked](https://github.com/vercel/commerce/assets/105623408/3c61c139-ef52-4d43-a5f0-0f68636deea1)


Then on choosing one of the boiler plate I clicked on deploy -
![Step2](https://github.com/vercel/commerce/assets/105623408/2008d1a4-a84a-4416-b9ba-8c2b2965d0fc)


After creating the git with vercel. I came across the issue I am facing which is on the configure Project.
![Screenshot 2023-05-25 173236](https://github.com/vercel/commerce/assets/105623408/db52c555-4301-4ff9-ba5d-7df658da3070)

**Comment by itsanishjain** [comment]
Ok I don't know why but that code needs that env

but instead, use this 

https://nextjs.org/commerce it won't ask for that env

![image](https://github.com/vercel/commerce/assets/43033153/70a52014-cade-4f50-b3d6-8e902e2e53f2)

btw you need a pro plan to deploy this codebase of edge function time limit, you can check this issue #1028 

or use the v1 which is even better "wont' require pro plan" how to deploy it see #1034

**Comment by kaus-1296** [comment]
I got this new error on vercel/commerce setup on vercel. Can draw some attention to it.

![pnpm-run](https://github.com/vercel/commerce/assets/105623408/369cc0aa-d6f7-4d4d-a6ec-071a592669a0)

**Comment by leerob** [comment]
https://github.com/vercel/commerce/blob/main/.env.example

**Comment by kaus-1296** [comment]
I could successfully run the vercel/commerce setup locally. But on vercel it is showing error in building stage of the deployment status. Here is the screen shot I am sending. 
![deployement_status](https://github.com/vercel/commerce/assets/105623408/63480bf5-40a3-4478-9f79-56396848991c)

**Comment by kaus-1296** [comment]
Solved this issue -->

We have to minimize the font file contained in the app folder of the repository, preferably I converted into woff2 from ttf

1. Initially the error was showing that the file size was 1.02 MB which was exceeding than 1MB.
2. So for that I get into the **app**> **og**. In that there was two ttf files and route.tsx file.
3. Then I convert the ttf file into woff2 file.
4. Then I placed the converted file(woff2) into route.tsx file
5. After redeploying on vercel, it's working

**Comment by zyoung-rc** [comment]
> Solved this issue -->
> 
> We have to minimize the font file contained in the app folder of the repository, preferably I converted into woff2 from ttf
> 
> 1. Initially the error was showing that the file size was 1.02 MB which was exceeding than 1MB.
> 2. So for that I get into the **app**> **og**. In that there was two ttf files and route.tsx file.
> 3. Then I convert the ttf file into woff2 file.
> 4. Then I placed the converted file(woff2) into route.tsx file
> 5. After redeploying on vercel, it's working

This worked for me!

**Comment by manovotny** [comment]
@kaus-1296 we really appreciate you bringing this up. The Template Marketplace pages was out of sync with the repo. I just updated it with all the latest environment variables. 

https://vercel.com/templates/next.js/nextjs-commerce
