### ISSUE TITLE
Add eslint and prettier

### ISSUE THREAD

**Issue by marceloF5** [vercel/commerce#104]
Hey people, 

I created this issue just to represent the PR already submitted before but I created it without an issue opened related. #71.
Basically, we should think about organization and standardization, so I submitted a simple configuration of eslint and prettier. And obviously, we can improve other things over time, but for the moment I saw reason to just go here. These configurations already support the project well the development experience and we are already unlocked to analyze indentation, for example, future reviews. So from that moment its just saves the file and everything is automatically adjusted. Also, I added .idea and .vscode in gitignore.

**Comment by mostafakhawas2** [comment]
prettier configuration is added in the package.json file.

**Comment by marceloF5** [comment]
> prettier configuration is present in the package.json file.

@mosmk2 you right, I'm gonna review it.

**Comment by okbel** [comment]
Done!
