### ISSUE TITLE
The Edge Function "[page]/opengraph-image" size is 1 MB and your plan size limit is 1 MB.

### ISSUE THREAD

**Issue by tenosh** [vercel/commerce#1047]
Not able to deploy on a pristine e-commerce clone.
![image](https://github.com/vercel/commerce/assets/32285955/51a75fd8-74ba-45b8-ba3b-68957545ebaa)

**Comment by becomevocal** [comment]
Also seeing this while testing. Seems limited to `hobby` plans though. It _does_ work on our `pro` plan.

**Comment by tmb5cg** [comment]
Yes having same issue, broken on hobby

**Comment by DiegoAvenda** [comment]
So you need a Shopify subscription and a Vercel Pro plan for this to work.

**Comment by paulomenezes** [comment]
I have the same error, but it says that my image is 1.01 MB and the limit is 1 MB.

![image](https://github.com/vercel/commerce/assets/10564179/1bb543f5-dfcc-4642-b3b4-f24ffd0b7ccd)

**Comment by Loa212** [comment]
I found a workaround for this. 

We can lower the size by skipping the import of the font "inter".


```typescript
// ./components/opengraph-image.tsx

import { ImageResponse } from '@vercel/og';

export type Props = {
  title?: string;
};

export default async function OpengraphImage(props?: Props): Promise<ImageResponse> {
  const { title } = {
    ...{
      title: process.env.SITE_NAME
    },
    ...props
  };

  return new ImageResponse(
    (
      <div tw="flex h-full w-full flex-col items-center justify-center bg-black">
        <svg viewBox="0 0 32 32" width="140">
          <rect width="100%" height="100%" rx="16" fill="white" />
          <path
            fillRule="evenodd"
            clipRule="evenodd"
            fill="black"
            d="M17.6482 10.1305L15.8785 7.02583L7.02979 22.5499H10.5278L17.6482 10.1305ZM19.8798 14.0457L18.11 17.1983L19.394 19.4511H16.8453L15.1056 22.5499H24.7272L19.8798 14.0457Z"
          />
        </svg>
        <p tw="mt-12 text-6xl font-bold text-white">{title}</p>
      </div>
    ),
    {
      width: 1200,
      height: 630,
      // fonts: [
      //   {
      //     name: 'Inter',
      //     data: await fetch(new URL('../fonts/Inter-Bold.ttf', import.meta.url)).then((res) =>
      //       res.arrayBuffer()
      //     ),
      //     style: 'normal',
      //     weight: 700
      //   }
      // ]
    }
  );
}

```

**Comment by digicoparis** [comment]
Hi, just made a new deploy try, same error with Hobby Plan.

https://vercel.com/digicoparis/nextjscommerce3/B1LBCqM4eYTyi7NGsNG7W9nMJyhK

![image](https://github.com/vercel/commerce/assets/25030291/83de66da-8f14-4998-8b0e-e121c15a31a9)

Take care,
Digico Paris

**Comment by manovotny** [comment]
We are aware of this issue / limitation and are working on solutions to address. Stay tuned...

**Comment by digicoparis** [comment]
This would a good workaround font is not nice (basic Serif or Helvetica), if we are on "Hobby" Plan.

**Comment by digicoparis** [comment]
Some speed RAS while in hobby plan.
![image](https://github.com/vercel/commerce/assets/25030291/1ac1ee77-94c6-46f6-9995-a2998496e3c1)

**Comment by Loa212** [comment]
@digicoparis  I don't think this is related to the initial question since to be able to test it you must've been able to deploy it.

Also, I am getting the same results as the [demo](https://demo.vercel.store/) provided by nextjs/commerce on a website I deployed using the hobby plan. 

I am using [Google's pagespeedinsights](https://pagespeed.web.dev/) to analyze it.
