### ISSUE TITLE
Enable provider forks to easily implement their own revalidate route logic

### ISSUE THREAD

**Issue by becomevocal** [vercel/commerce#1049]
Currently `/app/api/revalidate/route.ts` is hardcoded to support Shopify's collection and webhook model. This means a provider can't focus only on the `lib` folder and will cause overhead over time to keep the fork up to date with changes Vercel makes to the core.

Would be nice to have this logic moved to be inside the `lib` folder as well, maybe even separated out under `lib/hooks/revalidate.ts` so it's clear what it handles.

**Comment by osseonews** [comment]
Choosing Shopify as the standard is really the strangest thing about V2. Shopify already has a React-powered framework in Hydrogen that is actively maintained and is updated nearly daily. Why would anyone who uses Shopify choose this repo over Hydrogen? So who exactly are they building this for? Personally, I think they should have built an agnostic repo with products in a JSON file, a cart powered by Vercel KV (Redis), and checkout with Stripe. This would allow headless CMS's to support the repo for the product part, and the other features can be augmented via different 3rd party packages.
