### ISSUE TITLE
Clicking on a dialog (mobile menu / cart) closes the dialog on a first interaction

### ISSUE THREAD

**Issue by tenosh** [vercel/commerce#1056]
On my initial commit (no files modified) when opening the mobile menu dialog or cart dialog and clicking on the search box or anywhere inside the dialog it triggers the `onClose` <Dialog /> event. After closing and opening again it will work as expected.

On mobile menu dialog:
![ezgif-3-632fe7315b](https://github.com/vercel/commerce/assets/32285955/7bf265b0-1b66-4663-a240-5646d4fdc50d)

On cart dialog:
![cart](https://github.com/vercel/commerce/assets/32285955/b560e26f-03e8-4b69-9736-33a74abccf8e)

No files are being modified at this point, I have just added my env variables values to get data from Shopify. 
I was able to reproduce it on Brave / Chrome / Firefox's latest versions.

**Comment by Olaleye-Blessing** [comment]
[This commit](https://github.com/vercel/commerce/commit/9678306b2365a25feebf68ccbd5eaa5b65a0137d) fixed it.

**Comment by manovotny** [comment]
Thanks for verifying @Olaleye-Blessing!

**Comment by tenosh** [comment]
This fixes the cart Dialog, but is there any quick fix for the mobile menu dialog?

**Comment by tenosh** [comment]
> [This commit](https://github.com/vercel/commerce/commit/9678306b2365a25feebf68ccbd5eaa5b65a0137d) fixed it.

Also, would mind explain what was the cause of this issue? 🤔

**Comment by manovotny** [comment]
> Also, would mind explain what was the cause of this issue? 🤔

I didn't know this issue was related to an issue I created until it was all over with. More context here: https://github.com/vercel/commerce/issues/1051

**Comment by tenosh** [comment]
> > Also, would mind explain what was the cause of this issue? 🤔
> 
> I didn't know this issue was related to an issue I created until it was all over with. More context here: #1051

Got it, so must be related to the headlessui Dialog. I probably need to downgrade to fix or find a workaround. Thanks for the context!

**Comment by manovotny** [comment]
@tenosh that was my initial hunch, but we didn't wind up needing to downgrade. In our instance, it wound up being a CSS issue. Reworking the state seems to have fixed it. Details are in #1053.
