### ISSUE TITLE
Webhooks docs unclear about revalidation URL

### ISSUE THREAD

**Issue by dannyyu92** [vercel/commerce#1059]
The docs show webhooks being created using:

https://`[REDACTED]`/api/revalidate?secret=...

but it's unclear what this URL should be. Is this our shopify domain url on production? Locally using ngrok makes sense, but once in prod do we change this to our live url?

**Comment by leerob** [comment]
This would be the URL of your deployed version of this repository 👍 Or `localhost`, if testing locally.

**Comment by danieldanielecki** [comment]
I agree, this docs is missing this crucial part.

**Comment by danieldanielecki** [comment]
The docs seems to have `e` visible, meaning it could've been potentially `demo.vercel.store`, wouldn't say that should've been a secret to keep it blurred in the docs.

**Comment by danieldanielecki** [comment]
That was indeed the URL of my domain `abc.vercel.app`, but could've been mentioned more explicitly in the docs :(  the wrong URL was the reason my I've seen in logs info about `invalid revalidation...`. Additionally, would be good to mention in the docs `api/revalidate` is being handled automatically be Vercel as it was also confusing for me whether I need to set up an API endpoint, but eventually it's not needed.
