### ISSUE TITLE
Use Shopifys (from hydrogen-react package) prebuilt types and schema + add graphql config

### ISSUE THREAD

**Issue by tobbbe** [vercel/commerce#1060]
Shopify already has [prebuilt types and gql schema for the storefront api](https://shopify.dev/docs/api/hydrogen-react/2023-04/utilities/storefront-api-types). It would be nice to use those instead of `/lib/shopify/[fragments/queries/mutations]`. The npm-package is even synced with shopifys api-version!

This also opens the opportunity to add a [graphql config file](https://the-guild.dev/graphql/config/docs) to get autocompletion of the schema.
Example file:
```
schema: node_modules/@shopify/hydrogen-react/storefront.schema.json
documents: 'lib/**/*.{graphql,ts}'
```

This do however require that [@shopify/hydrogen-react](https://www.npmjs.com/package/@shopify/hydrogen-react) is added as a dependency to the project.

**Comment by leerob** [comment]
Hey! Thanks for asking about this. AFAIK there isn't a way to do this without setting up codegen, which I'd like to avoid.

**Comment by tobbbe** [comment]
Hmm I dont think so. Types can be imported like so:
```typescript
import type {
  Product,
  Collection,
} from '@shopify/hydrogen-react/storefront-api-types'
```
The graphql schema auto-complete only requires that you have [the vscode graphql plugin](https://marketplace.visualstudio.com/items?itemName=GraphQL.vscode-graphql) installed (and the config file present).

Thats all have in my repo which works 😊

Codegen is not needed as I understand it from Shopifys docs here: https://shopify.dev/docs/api/hydrogen-react/2023-04/utilities/storefrontapicustomscalars

> Note that @shopify/hydrogen-react has already generated types for the Storefront API, so you may not need to setup GraphQL Codegen on your own.

**Comment by leerob** [comment]
What happens if you're not using VSCode? 

I'm hesitant to change the approach we have here because it's straightforward and doesn't require extra dependencies.

**Comment by tobbbe** [comment]
I believe most editors has gql plugins(?), but if not the only difference will be that gql autocompletion won't work.

Okey! You have a point 😊

**Comment by leerob** [comment]
We might revisit this decision in the future 😄
