### ISSUE TITLE
please help me. I get this error when a try to deploy to vercel

### ISSUE THREAD

**Issue by indjongwe** [vercel/commerce#1061]
Error occurred prerendering page "/sitemap.xml". Read more: https://nextjs.org/docs/messages/prerender-error
--
14:30:21.929 | [object Object]
14:30:22.076 | - info Generating static pages (5/5)
14:30:22.078 |  
14:30:22.079 | > Export encountered errors on following paths:
14:30:22.079 | /sitemap.xml/route: /sitemap.xml
14:30:22.137 | ELIFECYCLE  Command failed with exit code 1.
14:30:22.162 | Error: Command "pnpm run build" exited with 1
14:30:22.542 | BUILD_UTILS_SPAWN_1: Command "pnpm run build" exited with 1

**Comment by manovotny** [comment]
This is being tracked and discussed in #1010. Closing this as a duplicate.
