### ISSUE TITLE
Prices on cart showing different currencies

### ISSUE THREAD

**Issue by maxmag-soft** [vercel/commerce#1062]
I have changed the prices from a product
![image](https://github.com/vercel/commerce/assets/70498883/1c75fcf9-f8c0-4e8b-b5a2-062555a843a2)
At First, nothing changed on the nextjs dev page...
Then I needed to load the page on incognito mode or deleting app storage cache on chrome for it to load the changes...
After that, When I added the product on my cart, the price on product is showing USD, EUR, number from BRL and is very confusing:
![image](https://github.com/vercel/commerce/assets/70498883/ac314033-97f1-4a2c-ad22-dc8c0afde2c7)

How can I help by providing more info?

**Comment by leerob** [comment]
Hey! It's hard to tell what you might have changed in your forked/modified version of this code. We are not currently planning to add i18n or different localized prices at this time 🙏
