### ISSUE TITLE
Did everything right, but no products showing up

### ISSUE THREAD

**Issue by Prottoy2938** [vercel/commerce#1069]
I've followed the official instruction [here](https://vercel.com/templates/next.js/nextjs-commerce) step by step but seems like it's not connected with the Shopify storefront.

I doubled checked all the API keys, everything seems correct. I have also tested the webhook api using `Send test notification` and checking console  logs on the `/api/revalidate/routes`. 

How can I check/figure out whats wrong? Why isn't the nextjs store showing the products I've added on the shopify store?

**Comment by leerob** [comment]
Hey there, sorry you're having trouble here. It's hard to tell what could be wrong in your setup. Could you try starting from scratch maybe? Maybe we can add more to the README if you determine what is missing.

**Comment by leerob** [comment]
Closing as stale, but let me know.

**Comment by coolburly** [comment]
hi @leerob , the homepage is blank, but can search products:

https://nextjs-commerce-qadq.vercel.app/product/sony-alpha-zv-e10-mirrorless-vlog-camera

https://nextjs-commerce-qadq.vercel.app

**Comment by danieldanielecki** [comment]
My `SHOPIFY_REVALIDATION_SECRET` was wrong as I put there the blurred first part in https://vercel.com/docs/integrations/shopify#configure-shopify-webhooks-in-the-shopify-admin instead of what comes after `secret=XYZ` generated from https://www.uuidgenerator.net/guid.
