### ISSUE TITLE
Checkout page doesn't render locally

### ISSUE THREAD

**Issue by luke-denton-aligent** [vercel/commerce#107]
When attempting to load the `/checkout` route in Next Commerce on a local dev machine, this error appears:

![image](https://user-images.githubusercontent.com/18253422/100688995-82c50c80-33d3-11eb-8395-84581010bb85.png)

Here it is again for text searches
```
Server Error
Error: Objects are not valid as a React child (found: [object Promise]). If you meant to render a collection of children, use an array instead.
    in apiHandler (at _app.tsx:20)
    in Fragment
    in Noop (at _app.tsx:19)
    in Context.Provider
    in Unknown (at context.tsx:183)
    in Context.Provider (at context.tsx:170)
    in UIProvider (at context.tsx:182)
    in ManagedUIContext (at _app.tsx:18)
    in Fragment
    in MyApp
    in Unknown
    in Context.Provider
    in Context.Provider
    in Context.Provider
    in Context.Provider
    in AppContainer

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Source
../pages/_document.tsx (83:33) @ Function.getInitialProps

  81 |     }
  82 | 
> 83 |     const { html, head } = await ctx.renderPage({ enhanceApp })
     |                                 ^
  84 |     const styles = [...flush()]
  85 |     return { html, head, styles }
  86 |   }
```

**Comment by fkurdi** [comment]
not sure this is part of the scope of this app.
the checkout page, `<baseurl>/checkout`, will render on prod because big commerce hosts that checkout page. 
i might be wrong, but for compliance reasons and customer account safety, the checkout pages are usually hosted on the platforms and are not directly exposed to coders.
best we can do here is a mock checkout page??

it would be amazing if we can render this in dev, but better if we can customize. 🤞 i hope it's possible. this is up to each platform i would imagine.

**Comment by luke-denton-aligent** [comment]
Thanks @fkurdi, I think you might be correct! I noticed when I tested my app that was deployed that I was redirected to a big commerce hosted checkout.

Locally, I would still expect the route to be handled in some way - either displaying a message that says "this page isn't for dev" or something else, rather than just error's and breaking the app

**Comment by FredvanRijswijk** [comment]
@fkurdi https://github.com/bigcommerce/checkout-js is the full open-source version of BigCommerce checkout

**Comment by okbel** [comment]
@RayeEMThompson

**Comment by manovotny** [comment]
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: #966
