### ISSUE TITLE
Clicking a collection in the sidenav on search results page doesn't clear the search term

### ISSUE THREAD

**Issue by mattbrailsford** [vercel/commerce#1074]
When on a search results page, if you select one of the navigate away to a collection in the side nav the search term isn't cleared in the searchbox

![image](https://github.com/vercel/commerce/assets/527305/5d0ffd27-febc-4a36-9f45-9f8b2d7bc8d3)

Selecting a category should clear the search term in the search box

**Comment by leerob** [comment]
Fixed!
