### ISSUE TITLE
Bad Practice: Creating a cart for every visitor

### ISSUE THREAD

**Issue by mattbrailsford** [vercel/commerce#1075]
I know this is just a demo, but it's really bad practice to create a cart for every site visitor. If this demo gets used by anyone in production this could be an issue with databases quickly getting filled up with lots of empty carts.

It would be much better if a cart was only created at the point of an item being added to the cart.

**Comment by leerob** [comment]
Fixed!

**Comment by mattbrailsford** [comment]
Wow, that was quick. Really nicely done. Will test this out this week 👍🏻

**Comment by manovotny** [comment]
To be clear, we've fixed it in a branch we're looking to release in the next couple of weeks.

**Comment by mattbrailsford** [comment]
Ahh, no problem. Thanks for clarifying 👍🏻
