### ISSUE TITLE
Use url instead of `setState` for image gallery

### ISSUE THREAD

**Issue by manovotny** [vercel/commerce#1105]
It would be cool to use url state for this rather than `setState` – makes things more shareable.

![cleanshot_2023-07-22_at_15 48 49](https://github.com/vercel/commerce/assets/446260/c0d77c8d-d870-4452-b641-3c58cea388aa)

**Comment by fucha-co** [comment]
it would also be cool if the images could be mapped to colour variant selectors [somehow]. using the [awesome Vercel drawstring bag](https://www.vercel.store/product/acme-drawstring-bag?) as an example... 

- there are 2 colour variants (black and white) and two product images (black bag and white bag) 
- atm  the black colour variant and black image are loaded by default
- but if you click the white image thumbnail it loads the white full-size image but the black colour variant [pill] doesn't change so Black is still selected
- could this be possible? 

![image](https://github.com/vercel/commerce/assets/1171169/fe11ab98-3d1c-4447-ae00-df8c58684910)

**Comment by manovotny** [comment]
@fucha-co is it possible? Maybe. In Shopify's models, the [Product](https://shopify.dev/docs/api/storefront/2023-04/objects/Product) has [Options](https://shopify.dev/docs/api/storefront/2023-04/objects/ProductOption) (how we lay out color and size above) and [Variants](https://shopify.dev/docs/api/storefront/2023-04/objects/ProductVariant) (all the possible combinations). Options don't have images, so you'd have to come up with some magic to associate a selected option with a Variant, which does have an `image` property. Additionally, this may work for a product where there is one image per color as you show above, but for other products like the [cowboy hat](https://demo.vercel.store/product/acme-cowboy-hat) where there are multiple images per color, it get's even more trickier. As such, we're not going to change the template to try and match colored images to selected option values. The gallery is purely a display of all images associate with the product.
