### ISSUE TITLE
Not displaying product description on page reload (demo.vercel.store website)

### ISSUE THREAD

**Issue by ulysset** [vercel/commerce#111]
Hi,
This problem has been found when testing the website on desktop Chrome 87, Safari and another computer on a different network :
When refreshing a product page the description disappears (see image bellow)
Failed to load resource: the server responded with a status of 500 ()` 
<img width="1440" alt="Screenshot 2020-12-02 at 20 10 39" src="https://user-images.githubusercontent.com/13087992/100919750-7d061e80-34da-11eb-8163-fbe27326d724.png">

**Comment by stevencmh** [comment]
Hello,

I'm seeing the same with these two warnings:

`Warning: Prop `dangerouslySetInnerHTML` did not match.`

`Warning: Invalid DOM property `shape-rendering`. Did you mean `shapeRendering`?`
