### ISSUE TITLE
Page "jumps" on navigation / refresh

### ISSUE THREAD

**Issue by manovotny** [vercel/commerce#1114]
From Twitter: https://twitter.com/edgarasben/status/1683906847000887305

> When navigating or refreshing page jumps. I would add overflow: scroll instead of overflow: auto. Unless there is a better solution.

https://github.com/vercel/commerce/assets/446260/175ea25b-922a-4eb6-af6b-99fa2eaa6cfb

**Comment by manovotny** [comment]
@leerob second opinion... Can you reproduce this?

**Comment by leerob** [comment]
Hmm, I also can't 😢
