### ISSUE TITLE
First clicks response slower

### ISSUE THREAD

**Issue by rondo10** [vercel/commerce#1118]
I was rebased from  [Update to a new design.](https://github.com/vercel/commerce/pull/1103) commit to [Set color-scheme in dark mode](https://github.com/vercel/commerce/pull/1113)
And the website got much slower.
It happens on first clicks before there is something cached.

**Comment by leerob** [comment]
Can you provide more details?

**Comment by manovotny** [comment]
I've tried a few things and can't seem to reproduce. I created #1136 to test this out and see no difference between https://demo.vercel.store and https://commerce-shopify-git-repro-1118-vercel-solutions-vtest314.vercel.app/.

@rondo10 if you can provide a video or some steps to reproduce, that'd be helpful and we can reopen and investigate.
