### ISSUE TITLE
SHOPIFY_REVALIDATION_SECRET env' variable?

### ISSUE THREAD

**Issue by fucha-co** [vercel/commerce#1119]
hello.

- love this offering and trying to test it out 🤩
- how/where does the SHOPIFY_REVALIDATION_SECRET get generated?

**Comment by impartdan** [comment]
I'm lost as well. I hope someone that knows the process to create/locate these keys can contribute to the documentation.

**Comment by impartdan** [comment]
Nevermind. It's here: https://github.com/vercel/commerce and very thorough.

**Comment by vogdev** [comment]
@impartdan please where did you find it bucuse the link you provided takes to the repo

**Comment by impartdan** [comment]
https://vercel.com/docs/integrations/shopify

**Comment by manovotny** [comment]
Even more specifically, here: https://vercel.com/docs/integrations/shopify#create-a-secret-for-secure-revalidation
