### ISSUE TITLE
Authorization and My Account

### ISSUE THREAD

**Issue by osseonews** [vercel/commerce#1121]
First of all, the new design looks excellent is a great improvement. My issue is whether there is any intention to add Authorization - Login/Logout to this repo? It was in V1, but is not here. Also, what is missing here is a separate section for My Account which would be available only to a Authorized User, so they can see their order history. Perhaps for Auth, you can choose one Auth provider to build off of and then people can fork it, to add their own Auth provider. A good provider to use is Clerk, b/c they are a NextJS first auth provider. Thanks.

**Comment by alexhawkins** [comment]
@osseonews was wondering the same thing. Why not NextAuth?

**Comment by leerob** [comment]
We're not planning to add auth here, but this is definitely something you could implement in your own forked version!
