### ISSUE TITLE
Add light / dark theme toggle

### ISSUE THREAD

**Issue by danieldanielecki** [vercel/commerce#1145]
It would be great to have a toggle to switch between light theme (needs implementation) & dark theme (currently available).

**Comment by ManishDait** [comment]
Hi, @manovotny I would like to work on these feature

**Comment by manovotny** [comment]
@ManishDait you're more than welcome to give it a shot and submit a PR. The only guidance I'll give is... We did try [next-themes](https://www.npmjs.com/package/next-themes) and ran into issues with RSCs and hydration. We are aware of workarounds listed in issues on the repo, but we were not able to come up with a solution we were happy with, so we skipped it for now. Ideally, it would be finding and fixing a solution in `next-themes` so many projects could benefit from it.

**Comment by leerob** [comment]
Going to close this one out, as I'm happy with the current light/dark mode setup 👍

**Comment by xpek20** [comment]
Is there any way to force light mode instead of defaulting to the system preference?
