### ISSUE TITLE
Dark mode doesn't update the Vercel SVG color

### ISSUE THREAD

**Issue by leerob** [vercel/commerce#115]
Very small bug 😄 

![image](https://user-images.githubusercontent.com/9113740/101368560-e84e4880-386c-11eb-974e-bc5ca7b0fbc2.png)

**Comment by okbel** [comment]
Looking forward to your PR 😛

**Comment by okbel** [comment]
haha thanks for reporting! On it!!

**Comment by okbel** [comment]
Solved here! https://github.com/vercel/commerce/pull/118
