### ISSUE TITLE
[Question/Discussion]: asynchronous `startTransition()` usage

### ISSUE THREAD

**Issue by roch-numbered** [vercel/commerce#1153]
Hi,

While checking latest updates, I noticed in the codebase the use of `useTransition()`/`startTransition()`. I start reading the doc to gather more informations, details and understanding about the purpose of this hook and I noticed that:

> The function you pass to `startTransition` must be synchronous.

From react.dev [`startTransition` caveats](https://react.dev/reference/react/useTransition#starttransition-caveats).

But in this codebase ([add-to-cart.tsx](https://github.com/vercel/commerce/blob/faa7491a55a9177b0be6e34f50cff649eca649eb/components/cart/add-to-cart.tsx#L39-L53) & [delete-item-button.tsx](https://github.com/vercel/commerce/blob/faa7491a55a9177b0be6e34f50cff649eca649eb/components/cart/delete-item-button.tsx#L17-L28)), `startTransition` callbacks *are* async so I'm wondering:

- Why this usage?
- Does it present any interest?
- Isn't nullifying the purpose of the `startTransition` function?

Note: as there isn't any 'Discussions' tab in this repo, I posted an issue but this might not be an actual bug in the codebase 👍 

Cheers

**Comment by Fredkiss3** [comment]
the function `startTransition` returned from `useTransition` can work with async functions in the canary version of react which next uses.

**Comment by manovotny** [comment]
@Fredkiss3 is correct. The React docs are correct for the current release of React. Async `startTransition` is only supported in the experimental builds, which you can enable by turning on the experimental `serverActions` flag in Next.js.
