### ISSUE TITLE
Grammar - Change Preposition

### ISSUE THREAD

**Issue by therealharish** [vercel/commerce#1167]
[_Line 226:_](https://github.com/vercel/commerce/blob/e8c0ee04fce690349116ba929b27f8a1acb858b7/README.md?plain=1#L226) "want **to** people you share the url with" should be " want **for** people you share the url with."

**Comment by NextThread** [comment]
hey, I'd like to work on this issue

**Comment by manovotny** [comment]
@therealharish @NextThread thanks for the issue. I am going to close it though because we're about to release a major overhaul of the README and I don't want anyone to waste time on it. I'll in corporate the change in the update. Thanks for bringing it to our attention.
