### ISSUE TITLE
Select Option Drop Down inconsistent with dark mode

### ISSUE THREAD

**Issue by dhairyamodi2** [vercel/commerce#1168]
Steps:

- Add Items to cart
- Proceed to checkout
- Select State

![image](https://github.com/vercel/commerce/assets/104882015/15e81f6a-4b32-4e54-8bfb-a0afa39bd5fe)

**Comment by manovotny** [comment]
@dhairyamodi2 can you provide more information? Like OS and Browser? For example, Safari and Chrome on Mac look good to me.

![CleanShot 2023-08-14 at 14 25 24@2x](https://github.com/vercel/commerce/assets/446260/0be4f98e-4b49-4f92-85d6-61dac2c90681)

![CleanShot 2023-08-14 at 14 25 33@2x](https://github.com/vercel/commerce/assets/446260/ec829bc8-ab66-4688-aa51-eaa1c971f19f)

**Comment by DanielPintilei** [comment]
The OS is definitely Windows. For this current theme the app should have `color-scheme: dark;` applied, in order for the native controls and scrollbar to look good on Windows. Also the select menu inherits it's `background` and `color` so on Windows the menu has a white background and text color. I'd be interested to give this a go and open a PR.

**Comment by dhairyamodi2** [comment]
> @dhairyamodi2 can you provide more information? Like OS and Browser? For example, Safari and Chrome on Mac look good to me.
> 
> ![CleanShot 2023-08-14 at 14 25 24@2x](https://user-images.githubusercontent.com/446260/260552251-0be4f98e-4b49-4f92-85d6-61dac2c90681.jpg)
> 
> ![CleanShot 2023-08-14 at 14 25 33@2x](https://user-images.githubusercontent.com/446260/260552262-ec829bc8-ab66-4688-aa51-eaa1c971f19f.jpg)

Operating System: Ubuntu Linux
Browser: Chrome

**Comment by DanielPintilei** [comment]
> @manovotny Operating System: Ubuntu Linux Browser: Google Chrome

If I zoomed in a little bit I would have seen it's not Windows but it looks extremely similar. I checked it on Windows and the same issues are present.
