### ISSUE TITLE
Add support for subscriptions

### ISSUE THREAD

**Issue by manovotny** [vercel/commerce#1176]
We haven’t really thought about subscriptions up to this point, however, I do see that there is a `sellingPlanGroups` connection (ie. subscriptions) on the Product model. Like we connect to and return `variants` on the, I assume we could return subscriptions as well.

Thinking out loud here… But I think we’d need to:

* Return `sellingPlanGroups` on the product model
* Possibly conditionally render `variants` or `sellingPlanGroups` on product details and cart
* Modify `addToCart` to accept different types of line items (ie. variants or subscriptions)

There will obviously be kinks to work out there, but I’d start with:

* Setting up a subscription product to test with
* Use Postman / Insomnia / RapidAPI to run the GraphQL query and see what the model looks like and go from there

Resources: 

* [Manage subscription products on storefronts](https://shopify.dev/docs/custom-storefronts/building-with-the-storefront-api/products-collections/subscriptions#step-4-create-a-cart-and-a-subscription-line-item)
* [Product Connections → SellingPlanGroup](https://shopify.dev/docs/api/storefront/2023-07/objects/Product#connections)

**Comment by fucha-co** [comment]
yes please a-thousand-times over! 🙏🏾🥳

**Comment by mrruby** [comment]
🙏🏾🙏🏾🙏🏾🙏🏾

**Comment by coopbri** [comment]
Hey there, curious if this is implemented and I am missing it? I saw this was closed as completed. This would be a major feature for me.

If not implemented, does anyone have production code with this working in Next.js Commerce via e.g. the `sellingPlanGroups` API?
