### ISSUE TITLE
Unhandled Runtime Error Error: Error: [object Object]

### ISSUE THREAD

**Issue by RanaRabees** [vercel/commerce#1181]
> ##  I forked the commerce: https://github.com/vercel/commerce
repo and installed all dependencies using `yarn`. 

However, when I run the project using `yarn dev`, I get the following error:
>
> ```
> Unhandled Runtime Error
> Error: Error: [object Object]
> ```
>

> The error message indicates that the `/api/2023-01/graphql.json` URL is malformed. This URL should be an absolute URL, not a relative URL.
>

> ##  I have tried the following to fix the issue:
>
> * I have checked the `next.config.js` file and ensured that the `apiBaseUrl` property is set to an absolute URL.
> * I have cleared the `node_modules` directory and re-run `yarn install`.
> * I have tried running the project using `yarn start` instead of `yarn dev`.
>

> ## Here are some additional information about my error that might be helpful for understanding my error:

>  PS E:\My Projects\commerce> yarn dev
> yarn run v1.22.19
> warning @: The engine "pnpm" appears to be invalid.
> $ next dev
> - warn You have enabled experimental feature (serverActions) in next.config.js.
> - warn Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
> 
> - ready started server on 0.0.0.0:3000, url: http://localhost:3000
> - event compiled client and server successfully in 2s (20 modules)
> - wait compiling...
> - event compiled client and server successfully in 1255 ms (20 modules)
> - wait compiling /page (client and server)...
> - event compiled client and server successfully in 9.3s (1938 modules)
> - error {
>   cause: 'TypeError [ERR_INVALID_URL]: Invalid URL',
>   status: 500,
>   message: 'URL is malformed "/api/2023-01/graphql.json". Please use only absolute URLs - https://nextjs.org/docs/messages/middleware-relative-urls',
>   query: '\n  query getMenu($handle: String!) {\n    menu(handle: $handle) {\n      items {\n        title\n        url\n      }\n    }\n  }\n'
> }
> - error [Error: Error: [object Object]] { digest: '2479588004' }
> - error {
>   cause: 'TypeError [ERR_INVALID_URL]: Invalid URL',
>   status: 500,
>   message: 'URL is malformed "/api/2023-01/graphql.json". Please use only absolute URLs - https://nextjs.org/docs/messages/middleware-relative-urls',
>   query: '\n  query getCollectionProducts(\n    $handle: String!\n    $sortKey: ProductCollectionSortKeys\n    $reverse: Boolean\n  ) {\n    collection(handle: $handle) {\n      products(sortKey: $sortKey, reverse: $reverse, first: 100) {\n        edges {\n   
>        node {\n            ...product\n          }\n        }\n      }\n    }\n  }\n  \n  fragment product on Product {\n    id\n 
>    handle\n    availableForSale\n    title\n    description\n    descriptionHtml\n    options {\n      id\n      name\n      values\n    }\n    priceRange {\n      maxVariantPrice {\n        amount\n        currencyCode\n      }\n      minVariantPrice {\n     
>    amount\n        currencyCode\n      }\n    }\n    variants(first: 250) {\n      edges {\n        node {\n          id\n        
>   title\n          availableForSale\n          selectedOptions {\n            name\n            value\n          }\n          price {\n            amount\n            currencyCode\n          }\n        }\n      }\n    }\n    featuredImage {\n      ...image\n  
>   }\n    images(first: 20) {\n      edges {\n        node {\n          ...image\n        }\n      }\n    }\n    seo {\n      ...seo\n    }\n    tags\n    updatedAt\n  }\n  \n  fragment image on Image {\n    url\n    altText\n    width\n    height\n  }\n\n  \n 
>  fragment seo on SEO {\n    description\n    title\n  }\n\n\n'
> }
> - error {
>   cause: 'TypeError [ERR_INVALID_URL]: Invalid URL',
>   status: 500,
>   message: 'URL is malformed "/api/2023-01/graphql.json". Please use only absolute URLs - https://nextjs.org/docs/messages/middleware-relative-urls',
>   query: '\n  query getCollectionProducts(\n    $handle: String!\n    $sortKey: ProductCollectionSortKeys\n    $reverse: Boolean\n  ) {\n    collection(handle: $handle) {\n      products(sortKey: $sortKey, reverse: $reverse, first: 100) {\n        edges {\n   
>        node {\n            ...product\n          }\n        }\n      }\n    }\n  }\n  \n  fragment product on Product {\n    id\n 
>    handle\n    availableForSale\n    title\n    description\n    descriptionHtml\n    options {\n      id\n      name\n      values\n    }\n    priceRange {\n      maxVariantPrice {\n        amount\n        currencyCode\n      }\n      minVariantPrice {\n     
>    amount\n        currencyCode\n      }\n    }\n    variants(first: 250) {\n      edges {\n        node {\n          id\n        
>   title\n          availableForSale\n          selectedOptions {\n            name\n            value\n          }\n          price {\n            amount\n            currencyCode\n          }\n        }\n      }\n    }\n    featuredImage {\n      ...image\n  
>   }\n    images(first: 20) {\n      edges {\n        node {\n          ...image\n        }\n      }\n    }\n    seo {\n      ...seo\n    }\n    tags\n    updatedAt\n  }\n  \n  fragment image on Image {\n    url\n    altText\n    width\n    height\n  }\n\n  \n 
>  fragment seo on SEO {\n    description\n    title\n  }\n\n\n'
> }
> - error {
>   cause: 'TypeError [ERR_INVALID_URL]: Invalid URL',
>   status: 500,
>   message: 'URL is malformed "/api/2023-01/graphql.json". Please use only absolute URLs - https://nextjs.org/docs/messages/middleware-relative-urls',
>   query: '\n  query getMenu($handle: String!) {\n    menu(handle: $handle) {\n      items {\n        title\n        url\n      }\n    }\n  }\n'
> }
> - error [Error: Error: [object Object]] { digest: '2479588004' }
> - error [Error: Error: [object Object]] { digest: '2479588004' }
> - error [Error: Error: [object Object]] { digest: '2479588004' }

> ## Here are some additional information that might be helpful:

```
* The version of Next.js I am using is 13.4.13.
* The version of React.js I am using is 18.2.0.
* The error message is occurring in the `getMenu` query in the `pages/api/menu.js` file.
```

> ## However, I am still getting the same error.
>
> I would appreciate if any one will help me in fixing this issue.
>

**Comment by manovotny** [comment]
> This URL should be an absolute URL, not a relative URL.

@RanaRabees this is correct. It's relative because it's expecting a `SHOPIFY_STORE_DOMAIN` environment variable and it's not set. 

Please follow [these instructions](https://vercel.com/docs/integrations/shopify#configure-environment-variables) and you should be good.

**Comment by RanaRabees** [comment]
> Hi @manovotny 


**_Thank you_ so much for your help with my issue!**

Your instructions were very helpful That you provided and I was able to set the **environment variable**  _successfully_. 

The errors are now gone and my code is working as expected.

I really appreciate your quick and helpful response. It was very clear and easy to follow.

Thanks again for your help!

I am very **Thankful** for Your **Help**


> **_Best_**,
> @RanaRabees

**Comment by manovotny** [comment]
@RanaRabees good! I'm glad we were able to figure it out.
