### ISSUE TITLE
Why state is not changed at first click on mobile 

### ISSUE THREAD

**Issue by Faizsultan1** [vercel/commerce#1182]
https://github.com/vercel/commerce/assets/118690205/c8751915-affd-45c2-9974-b1df8aad16be

**Comment by RanaRabees** [comment]
**_@Faizsultan1_**

I think your mobile looks **slow/heavy** or any other **_problem_** in **code**

**Comment by Faizsultan1** [comment]
it’s Fixed now

**Comment by RanaRabees** [comment]
**_what was the problem please define me "why its fixed now"_**
