### ISSUE TITLE
Hide Scrollbars in the Related Products section

### ISSUE THREAD

**Issue by sumanth-botlagunta** [vercel/commerce#1186]
The horizontal scrollbar in the related products looks weird and doesn't fit into website UI. Add arrows to move horizontally and remove those scroll bars.

![image](https://github.com/vercel/commerce/assets/86908741/77b6e483-452e-40f0-a6b4-4b552f52627f)

**Comment by leerob** [comment]
This is operating system dependent, I believe, but can also be changed with CSS. I'm open to community PRs!
