### ISSUE TITLE
Uncaught (in promise) TypeError: Expected "nextInternalLocale" to be a string

### ISSUE THREAD

**Issue by stevencmh** [vercel/commerce#119]
Hi,

Error occurs when using the All Categories and All Designers filter at the bottom left of the home page.

<img width="1183" alt="Screenshot 2020-12-09 at 10 49 35" src="https://user-images.githubusercontent.com/35059438/101620285-3f3e5400-3a0c-11eb-9dbc-c55335b45726.png">

**Comment by markcmurphy** [comment]
I experienced this when searching while changing the locale to ES. This thread helped me fix the issue: https://github.com/vercel/next.js/issues/19521 and it looks like they've addressed it in a canary release: https://github.com/vercel/next.js/pull/19766

**Comment by stevencmh** [comment]
Hi,

Thanks! … I'll just pulled and merged canary but it's still throwing the same error.

Just looking on the demo site, and the filter on the right-hand side also results in an error.
