### ISSUE TITLE
SHOPIFY_REVALIDATION_SECRET ?

### ISSUE THREAD

**Issue by vogdev** [vercel/commerce#1194]
i spent + 3h looking for this key i can't find it in shopify where is it located ?

**Comment by manovotny** [comment]
The secret is something you create and set within Shopify when setting up your webhooks. 

https://vercel.com/docs/integrations/shopify#create-a-secret-for-secure-revalidation

**Comment by AP-monkey** [comment]
Has the status of this answer now changed with the added information in Shopify under webhooks -> Your webhooks will be signed with: "Shopify code"?

**Comment by enterpriseSoftware** [comment]
> Has the status of this answer now changed with the added information in Shopify under webhooks -> Your webhooks will be signed with: "Shopify code"?

I came here for this same question!  ????

**Comment by pguardiario** [comment]
is this optional? (if we're not using webhooks)
