### ISSUE TITLE
Issue while building the site from vercel while deploying the project

### ISSUE THREAD

**Issue by chandanitme** [vercel/commerce#1197]
![image](https://github.com/vercel/commerce/assets/49269952/d83928dd-0520-4958-a50d-4bc3f4b80e4a).

**Comment by manovotny** [comment]
This is because the `SHOPIFY_STORE_DOMAIN` environment variable isn't set. You can read more about it in our [Shopify integration guide](https://vercel.com/docs/integrations/shopify#configure-environment-variables).

**Comment by chandanitme** [comment]
@manovotny 
below are the environment variables I am passing.
COMPANY_NAME="Vercel Inc."
TWITTER_CREATOR="@vercel"
TWITTER_SITE="https://nextjs.org/commerce"
SITE_NAME="Next.js Commerce"
SHOPIFY_REVALIDATION_SECRET=""
SHOPIFY_STOREFRONT_ACCESS_TOKEN=""
SHOPIFY_STORE_DOMAIN="[ordercloudchandan].myshopify.com"
Please correct me if anything wrong.Please let me know how to get the below values.

SHOPIFY_REVALIDATION_SECRET=""
SHOPIFY_STOREFRONT_ACCESS_TOKEN=""

**Comment by manovotny** [comment]
@chandanitme remove the brackets from `SHOPIFY_STORE_DOMAIN`. The value should be `ordercloudchandan.myshopify.com`.

**Comment by chandanitme** [comment]
I did that but still the issue comes

Thanks. Chandan

**Comment by chandanitme** [comment]
@manovotny .I have made the change but still the error.
![image](https://github.com/vercel/commerce/assets/49269952/2a7b78ad-ec0f-4ee2-b30b-2e600e462222)

COMPANY_NAME="Vercel Inc."
TWITTER_CREATOR="@vercel"
TWITTER_SITE="https://nextjs.org/commerce"
SITE_NAME="Next.js Commerce"
SHOPIFY_REVALIDATION_SECRET=""
SHOPIFY_STOREFRONT_ACCESS_TOKEN=""
SHOPIFY_STORE_DOMAIN="ordercloudchandan.myshopify.com"

**Comment by manovotny** [comment]
@chandanitme then it's because `SHOPIFY_STOREFRONT_ACCESS_TOKEN` is missing. As I mentioned before, the [Shopify integration guide](https://vercel.com/docs/integrations/shopify#configure-environment-variables) instructs you how to get this in your Shopify admin.

**Comment by chandanitme** [comment]
Hi I have a query,
Since we are using sitecore order cloud then why to create account in
Shopify and create access toke.

Thanks
Chandan

**Comment by manovotny** [comment]
@chandanitme if you're using Sitecore, then I am not sure how to help you here. This is a Shopify based theme and [there isn't an official provider for Sitecore based on this theme](https://github.com/vercel/commerce#providers).
