### ISSUE TITLE
Navigation not showing up

### ISSUE THREAD

**Issue by davidherreradev** [vercel/commerce#1199]
Products and pages are showing up but not my navigation. I have the handle as "next-js-frontend-header-menu" but it doesn't seem to be working.

**Comment by davidherreradev** [comment]
Update. The navigation is showing up when I run it locally but it isn't showing up on the deployed vercel instance. Anyone have any idea why that could be?

**Comment by StevenJBorik** [comment]
Having the exact same problem.

**Comment by adloram** [comment]
@davidherreradev how did you manage to have them show up?

**Comment by leerob** [comment]
Hey there, it's hard for us to provide assistance on this issue without more details. Please ensure you walk through all of the setup instructions as well. If you are still seeing the issue, please open a new issue with more details.

**Comment by pytsx** [comment]
same problem!

**Comment by michaelmerrill** [comment]
If it's showing up in local development you might need to clear your vercel cache for the deployed site. You can do this in the vercel settings for your project.

**Comment by danieldanielecki** [comment]
> same problem!
> 
> The issue here is when you create the menu after deploying on Vercel. For some reason the menu is not updating after the deployment, so you need to set the menu and then publish your project.

this didn't help me :(

**Comment by manuelcostilla** [comment]
> If it's showing up in local development you might need to clear your vercel cache for the deployed site. You can do this in the vercel settings for your project.

I resolved the issue with this one, but for god knows reason in localhost:3000 its still the same and the navigation doesn't show up
