### ISSUE TITLE
Missing optimistic updaters or a better UX on Mutations

### ISSUE THREAD

**Issue by jaburx** [vercel/commerce#12]
For example, when we delete an item from the cart here: https://demo.vercel.store/cart

Apps gets stuck/frozen instead of optimistically delete it like a facebook button like click.

Facebook does that by optimisticUpdater: https://relay.dev/docs/en/mutations

**Comment by mamal72** [comment]
I was thinking about this when I tried changing (removing) some items from the cart sidebar view. I was going to create an issue but searched first and found it here.

I'd like to work on this. I'm not sure about the starting point but I believe it should be related to these two hooks used [here](https://github.com/vercel/commerce/blob/master/components/cart/CartSidebarView/CartSidebarView.tsx#L7) and [here](https://github.com/vercel/commerce/blob/master/components/cart/CartSidebarView/CartSidebarView.tsx#L8).

BTW, I've made a simple zero dep hook for implementing optimistic UI before. The repo is [here](https://github.com/mamal72/react-optimistic-ui-hook).

I appreciate if someone from the core team helps me and answer these questions:

- Should/can I use the mentioned hook in this project? I obviously will update the hook and the dev deps there beforehand.
- Was my assumption correct about those hooks mentioned in the first two links?
- Can you assign this issue to me, so no rework by anyone else in the community?

**Comment by mamal72** [comment]
Oh. I think the hooks used in [this file](https://github.com/vercel/commerce/blob/master/components/cart/CartItem/CartItem.tsx) are the ones to update.

**Comment by lfades** [comment]
Closing for now a we have some basic optimistic updates but don't want to invest to much on improving it until we have a very strong foundation for every provider
