### ISSUE TITLE
Tests?

### ISSUE THREAD

**Issue by sgoodrow** [vercel/commerce#1203]
I've found many examples NextJS apps across the Internet but they're all only partial representations of a real application, often leaving out necessary patterns like tests.

I know NextJS itself doesn't have an opinion about which testing libraries to use, but I worry that the lack of dogfooding of test libraries is causing a sizable gap in compatibility and accessibility.

Please consider adding tests to this example.

Thanks!

**Comment by leerob** [comment]
Hey! We have some examples of testing + Next.js here for reference https://nextjs.org/docs/pages/building-your-application/optimizing/testing.

**Comment by sgoodrow** [comment]
Hi Lee - yes, I'm familiar with these examples, but they're incredibly trivial and don't demonstrate patterns that manage the challenges that emerge in real applications, such as how to organize tests or test complex server behaviors.

It would be immensely valuable to include examples that accurately reflect real application requirements.

**Comment by tkrotoff** [comment]
@leerob

- Out of 343 [examples](https://github.com/vercel/next.js/tree/v13.5.4/examples) only 3 (!) of them come with tests (and these are the most basic examples one could come up with)

Also,
- Current solution for mocking routing is a 3rd party (!) package that [does not support `next/navigation`](https://github.com/scottrippey/next-router-mock/issues/67)
- Next.js breaks MSW: https://github.com/vercel/next.js/discussions/56446

<br>

https://github.com/vercel/next.js/discussions/28173#discussioncomment-7208318
