### ISSUE TITLE
Products in Carousel Collection are not fetching with the real name as in the Shopify Collections.

### ISSUE THREAD

**Issue by hamzaadil56** [vercel/commerce#1204]
![image](https://github.com/vercel/commerce/assets/72699020/687419f4-7909-4acc-8fab-a68bff359eec)

See this is the name of carousel items as mention in the [vercel integration guide](http://vercel.com/docs/integrations/shopify). And I was trying to fetch the products with **"hidden-homepage-carousel"** as mentioned in the repository. But this error was occuring "`No collection found for hidden-homepage-carousel`".

So in order to find the solution, I click on the view button as shown below:
![image](https://github.com/vercel/commerce/assets/72699020/28eca5be-bece-4dc4-b5b5-2dd9d869c4e8)

This was navigating to this url:
![image](https://github.com/vercel/commerce/assets/72699020/a3ab4ab5-4509-4255-b696-873411a12a9d)

Which means that the collection was creating with the name of "`frontpage`" instead of  "`hidden-homepage-carousel`". Then I fetch the products with "`frontpage`" and it worked.

**So can anyone tell why this is happening? @wentsul @leerob**

**Comment by mbaranovski** [comment]
Probably the url slug is created when u first create the collection. After it's created and renames it does not update.

**Comment by rolandin** [comment]
Same happening to me..

this is what works `const products = await getCollectionProducts({ collection: 'frontpage' });`

**Comment by leerob** [comment]
^ Thank you for sharing back that solution @rolandin!
