### ISSUE TITLE
Unable to load product and collection in vercel commerce.

### ISSUE THREAD

**Issue by shavejshaikh** [vercel/commerce#1205]
I'm trying to integrate Shopify with the next commerce and add everything which is required for the **env** file but still unable to load data inside the pages.

Followed the documentation of vercel with Shopify still haven't found any solution yet.

**Comment by hamzaadil56** [comment]
Is there any error occurring or not?

**Comment by shavejshaikh** [comment]
![image](https://github.com/vercel/commerce/assets/43640329/2a589deb-d911-424f-81b6-8ce25a916b92)

I'm not facing any error still unable to load a collection and product

**Comment by hamzaadil56** [comment]
The reason behind is that you probably have entered incorrect name of collection or products

Can you please share ss of shopify collections?

**Comment by shavejshaikh** [comment]
I have 3 collection 
![image](https://github.com/vercel/commerce/assets/43640329/c8c743cd-06d7-48e9-b6e5-87184665745b)
Follow the documentation of vercel integration shopify https://vercel.com/docs/integrations/shopify#

**Comment by nexusprime-here** [comment]
The same here.

I received some logs:
```
No collection found for `hidden-homepage-featured-items`
No collection found for `hidden-homepage-carousel`
```

**Comment by hamzaadil56** [comment]
Did you guys have created web hooks for the collections?

And the most important thing is that you can see the collection by clicking on the view button inside the collection. There is a bug in the vercel. integration for the carousel collection. It is not creating with the same name.Instead for the carousel collection it is creating with 'frontpage' name.

For the featured collection, it is completely fine, if you have created the web hooks..

**Comment by admdus** [comment]
[nexusprime-here] I also struggled a little bit but after adding third item into featured items the widget finally appeared

**Comment by Apezdr** [comment]
The homepage featured items requires currently at least 3 items to render, not a great design overall but that's how it works. If you add more items, put them into the channel for headless, and add the items to the collection `hidden-homepage-featured-items` it should show up for you.

**Comment by nexusprime-here** [comment]
> The same here.
> 
> I received some logs:
> 
> ```
> No collection found for `hidden-homepage-featured-items`
> No collection found for `hidden-homepage-carousel`
> ```

resolved in: https://github.com/vercel/commerce/issues/1207

**Comment by adloram** [comment]
do all the functions need to be edited the same way?

**Comment by leerob** [comment]
^ This is resolved per https://github.com/vercel/commerce/issues/1205#issuecomment-1751818893
