### ISSUE TITLE
Sorting causes an unexpected page error .

### ISSUE THREAD

**Issue by b-emini** [vercel/commerce#121]
After selecting a category and afterwards changing the sorting type it just shows the results for a split second and then gives and error. 
To Reproduce click this link : https://demo.vercel.store/search/shop-all?sort=price-asc
Or : Go to homepage then select Shop All , afterwards change the sorting type and wait for the error.
It seems to be a server error.
![Screenshot from 2020-12-14 16-36-21](https://user-images.githubusercontent.com/44677789/102101143-8bcdc900-3e2a-11eb-941d-e60e9d1fa339.png)
![Screenshot from 2020-12-14 16-36-34](https://user-images.githubusercontent.com/44677789/102101148-8cfef600-3e2a-11eb-9940-e5754652acf6.png)

**Comment by okbel** [comment]
You are adding an / to the URL. The correct URL would be `http://localhost:3000/search?q=hello&sort=price-desc` **no slash**.

**Comment by b-emini** [comment]
Try and visit this URL , the issue persists and gives a 404 error. 
https://demo.vercel.store/search/designers/acme?sort=price-desc
I have selected all and them the ACME from the designers section and after selecting sorting type it gives the error.
