### ISSUE TITLE
Feature Request: Optimistic Updates for Cart Operations

### ISSUE THREAD

**Issue by rondo10** [vercel/commerce#1214]
## Problem Statement
Currently, the cart operations (add, remove, update quantity) wait for the server response to update the UI. This can lead to a less responsive user experience, especially when the server is slow.

## Proposed Solution
It would be great to have optimistic updates for cart operations. With optimistic updates, the UI would update immediately, assuming that the server operation will succeed. If the operation fails, the UI can then revert back to the previous state.

## Benefits
Improved user experience due to immediate feedback.
Reduced perceived latency.

**Comment by leerob** [comment]
Hey! You can achieve this with `useOptimistic`: https://nextjs.org/docs/app/building-your-application/data-fetching/forms-and-mutations#optimistic-updates

**Comment by marcusforsberg** [comment]
@leerob It would be helpful to have an official example on how to use useOptimistic outside of the basic form example. It would make sense for this repo to utilize optimistic loading to show how to implement it in the real world. For example, with the Cart being in an entirely separate component from the Add to cart button, I'm struggling to wrap my head around how to use useOptimistic to make the add to cart action appear faster - ideally you'd want the cart modal to open immediately with the item already there in the cart while the server action fires in the background. Do you have any pointers on how one could do that or plans to expand the docs? 😊
