### ISSUE TITLE
Issue with cookies in NextJS version `13.4.13-canary.15`

### ISSUE THREAD

**Issue by Apezdr** [vercel/commerce#1216]
```powershell
⨯ Error: Invariant: cookies() expects to have requestAsyncStorage, none available.
    at Cart (./components/cart/index.tsx:15:73)
    at stringify (<anonymous>)
```

It seems the version shipped with commerce `13.4.13-canary.15` is causing errors in a local development environment and when following the steps here: [https://github.com/vercel/commerce](https://github.com/vercel/commerce)

It seems this has been identified as an issue with the NextJS repo after version `13.4.7` please see here: [https://github.com/vercel/next.js/issues/55013#issuecomment-1712330213](https://github.com/vercel/next.js/issues/55013#issuecomment-1712330213)

```
Looks like this was introduced in [next@13.4.8](https://github.com/vercel/next.js/releases/tag/v13.4.8) since 13.4.7 works without error.

I'm guessing the issue is somewhere in [webpack-config.ts](https://github.com/vercel/next.js/blob/canary/packages/next/src/build/webpack-config.ts) but I haven't found the root cause.

Update: narrowed it down to [next@13.4.8-canary.1](https://github.com/vercel/next.js/releases/tag/v13.4.8-canary.1)
```

This error causes me to be unable to run the project locally however after downgrading my nextjs version to `13.4.7` I am able to run the project. It may be necessary to downgrade the version until this is resolved in NextJS.

**Comment by karlthomaas** [comment]
I have the exact same issue.

**Comment by jbonn2002** [comment]
I am having the same issue while trying to deploy locally, have you or anyone figured it out?

**Comment by karlthomaas** [comment]
> I am having the same issue while trying to deploy locally, have you or anyone figured it out?

Downgrading Nextjs version to 13.4.7 fixed it for me.

**Comment by jbonn2002** [comment]
I just upgraded to nextjs 14, and I am having no issues, just had to remove experimental server actions from next config and update imports for useFormState and useFormStatus.

**Comment by leerob** [comment]
Should be fixed!
