### ISSUE TITLE
Pulling .env.local from vercel sets wrong api store url

### ISSUE THREAD

**Issue by stevejhiggs** [vercel/commerce#122]
I was having the "login / create user returns 500's" issue others are seeing and was trying to figure out whats going on. While tracing through I noticed that my BIGCOMMERCE_STOREFRONT_API_URL in the .env.local file I downloaded from vercel contained:

https://store-u8hj8zwtsi-511411.mybigcommerce.com/graphql

But that my graphql explorer linked to:

https://mynicepharmacy.mybigcommerce.com/graphql

Changing my storefront api url and regenerating the tokens using the steps outlined in https://github.com/vercel/commerce/issues/39 made login return 200's

**Comment by sabraham** [comment]
Unfortunately this doesn't work for me. Changing the BIGCOMMERCE_STOREFRONT_API_URL as described here produces 401 errors when building.

**Comment by derardeek** [comment]
Having the exact same issue

**Comment by pgvercel** [comment]
Having the same issues with Sign Up & Login. Has someone managed to resolve this?

**Comment by stevejhiggs** [comment]
I think there may be several connected issues with login. It might be interesting to see if the issues are caused by the vercel -> bigcommerce auto setup or not.

In my case it was a brand new site set up via vercel using https://vercel.com/#get-started

**Comment by Nick-Achee** [comment]
https://github.com/bigcommerce/storefront-data-hooks/issues/13#issuecomment-749758395


leaving this here in the event you still haven't figured it out..

**Comment by stevejhiggs** [comment]
Issue is better represented by https://github.com/bigcommerce/storefront-data-hooks/issues/13#issuecomment-749726984
