### ISSUE TITLE
 error: { message: '', extensions: { code: 'ACCESS_DENIED' } },

### ISSUE THREAD

**Issue by JunRod** [vercel/commerce#1220]
### Hello! When I try to use commerce locally I get this error:

` ⨯ {
  error: { message: '', extensions: { code: 'ACCESS_DENIED' } },
  query: '\n  query getMenu($handle: String!) {\n    menu(handle: $handle) {\n      items {\n        title\n        url\n      }\n    }\n  }\n'
}
 ⨯ {
  error: { message: '', extensions: { code: 'ACCESS_DENIED' } },
  query: '\n  query getCollectionProducts(\n    $handle: String!\n    $sortKey: ProductCollectionSortKeys\n    $reverse: Boolean\n  ) {\n    collection(handle: 
$handle) {\n      products(sortKey: $sortKey, reverse: $reverse, first: 100) {\n        edges {\n          node {\n            ...product\n          }\n        
}\n      }\n    }\n  }\n  \n  fragment product on Product {\n    id\n    handle\n    availableForSale\n    title\n    description\n    descriptionHtml\n    opti
ons {\n      id\n      name\n      values\n    }\n    priceRange {\n      maxVariantPrice {\n        amount\n        currencyCode\n      }\n      minVariantPric
e {\n        amount\n        currencyCode\n      }\n    }\n    variants(first: 250) {\n      edges {\n        node {\n          id\n          title\n          a
vailableForSale\n          selectedOptions {\n            name\n            value\n          }\n          price {\n            amount\n            currencyCode\
n          }\n        }\n      }\n    }\n    featuredImage {\n      ...image\n    }\n    images(first: 20) {\n      edges {\n        node {\n          ...image\
n        }\n      }\n    }\n    seo {\n      ...seo\n    }\n    tags\n    updatedAt\n  }\n  \n  fragment image on Image {\n    url\n    altText\n    width\n    
height\n  }\n\n  \n  fragment seo on SEO {\n    description\n    title\n  }\n\n\n'
}
 ⨯ [Error: Error: [object Object]] { digest: '193452068' }
 ⨯ [Error: Error: [object Object]] { digest: '193452068' }
 ⨯ {
  error: { message: '', extensions: { code: 'ACCESS_DENIED' } },
  query: '\n  query getCollectionProducts(\n    $handle: String!\n    $sortKey: ProductCollectionSortKeys\n    $reverse: Boolean\n  ) {\n    collection(handle: 
$handle) {\n      products(sortKey: $sortKey, reverse: $reverse, first: 100) {\n        edges {\n          node {\n            ...product\n          }\n        
}\n      }\n    }\n  }\n  \n  fragment product on Product {\n    id\n    handle\n    availableForSale\n    title\n    description\n    descriptionHtml\n    opti
ons {\n      id\n      name\n      values\n    }\n    priceRange {\n      maxVariantPrice {\n        amount\n        currencyCode\n      }\n      minVariantPric
e {\n        amount\n        currencyCode\n      }\n    }\n    variants(first: 250) {\n      edges {\n        node {\n          id\n          title\n          a
vailableForSale\n          selectedOptions {\n            name\n            value\n          }\n          price {\n            amount\n            currencyCode\
n          }\n        }\n      }\n    }\n    featuredImage {\n      ...image\n    }\n    images(first: 20) {\n      edges {\n        node {\n          ...image\
n        }\n      }\n    }\n    seo {\n      ...seo\n    }\n    tags\n    updatedAt\n  }\n  \n  fragment image on Image {\n    url\n    altText\n    width\n    
height\n  }\n\n  \n  fragment seo on SEO {\n    description\n    title\n  }\n\n\n'
}
 ⨯ [Error: Error: [object Object]] { digest: '193452068' }
 ⨯ {
  error: { message: '', extensions: { code: 'ACCESS_DENIED' } },
  query: '\n  query getMenu($handle: String!) {\n    menu(handle: $handle) {\n      items {\n        title\n        url\n      }\n    }\n  }\n'
}
 ⨯ [Error: Error: [object Object]] { digest: '193452068' }`

**Comment by kels-graner** [comment]
I'm having the same issue...

**Comment by leerob** [comment]
Are you sure you have your environment variables set up correctly to talk to Shopify?

**Comment by leerob** [comment]
I'd recommend running through this again https://vercel.com/docs/integrations/shopify 🙏
