### ISSUE TITLE
Support for Nested Menus

### ISSUE THREAD

**Issue by rondo10** [vercel/commerce#1227]
## Description:
There's a potential area for enhancement in the store: the support for nested menus. Should be integrated with the nested menus of shopify.

## Rationale and Benefits:
Improved Navigation: By incorporating nested menus, users would have the ability to easily traverse through product categories and subcategories, making their shopping experience more streamlined and efficient.

Enhanced Organization: For store owners, nested menus offer a structured way to categorize products, allowing for a clearer representation of product hierarchies and relationships.

Optimized UI/UX: From a design perspective, nested menus can declutter the interface, providing users with a cleaner look and a more intuitive browsing experience.

**Comment by leerob** [comment]
Hey! We aren't planning to add this, but definitely could be made in people's forks of this starter template!
