### ISSUE TITLE
Running the dev server with Turbo using Next 14 results in errors

### ISSUE THREAD

**Issue by TimRuiterkamp1** [vercel/commerce#1228]
## Issue
I forked the repo and started the dev server using `next dev --turbo`. This resulted in the following error message:

```
Error resolving EcmaScript Modules request
unable to resolve module "components" with subpath "/grid/three-items"
It was not possible to find the requested file.
    Parsed request as written in source code: module "components" with subpath "/grid/three-items"
    Path where resolving has started: [project]/app/page.tsx
    Type of request: EcmaScript Modules request
    Import map: No import map entry
```

Note that this error occurred for all the base paths that were used in the code. 

## Other
I did not change anything other than adding `--turbo` to the dev server. 

## Fix
I fixed it by adding the paths to the `tsconfig.json` but I am not sure if this issue is experienced by more people. If it is, here is the fix:

```
tsconfig.json

{
  "compilerOptions": {
  ...standard compiler options
     "baseUrl": "./",
    "paths": {
      "components": ["components/*"],
      "lib": ["lib/*"],
      "pages": ["pages/*"],
      "public": ["public/*"],
      "styles": ["styles/*"]
      // Add more paths as needed
    }
  },
 ... rest of the config
}
```

**Comment by leerob** [comment]
Seems to be working on the latest `canary` version now!

https://github.com/vercel/commerce/pull/1236
