### ISSUE TITLE
It's possible to add to cart unavailable items on demo

### ISSUE THREAD

**Issue by gbonumore** [vercel/commerce#1235]
On the demo, even if the T-Shirt color "White" and size "L" is not selectable through the UI, creating a URL in order to select this combination like: https://demo.vercel.store/product/acme-geometric-circles-t-shirt?image=1&color=White&size=L results in the possibility to add this item to cart, looks like there is no initial check on combination availability.

**Comment by leerob** [comment]
Open to a community PR to address this if you want 😄
