### ISSUE TITLE
Search with same query

### ISSUE THREAD

**Issue by mehmetuken** [vercel/commerce#1256]
Hello, after performing a search, when I go back and press Enter in the search bar to search for the same thing again, nothing changes. For example, on https://demo.vercel.store/search?q=Acme+Circless, if I go there and press Enter directly in the search bar, there is no change on the page.

**Comment by Seventoor** [comment]
Can you elaborate? Circless does not exist, Did you mean Circles (just one s)?

**Comment by mehmetuken** [comment]
Hello, when you press Enter in the search box and then press Enter again without changing the search, nothing happens.

![Kapture 2023-12-11 at 12 08 23](https://github.com/vercel/commerce/assets/9348193/a4264dec-33d3-493d-99ae-ec95f2ca985f)

**Comment by Seventoor** [comment]
But why should something change when the same search will result in the same results?

**Comment by leerob** [comment]
This is intended. Since the search value is the same, pressing enter should not trigger another search with the same value.
