### ISSUE TITLE
Multi-store configuration / example

### ISSUE THREAD

**Issue by lapidus** [vercel/commerce#1258]
There was an earlier example demonstrating “multi-store” capabilities, combining the Vercel Platform patterns and NextJs Commerce: 
https://github.com/vercel/commerce/issues/478

Are there any more recent developments in this area supporting the Shopify (default) approach or other vendors? 

Thanks!

**Comment by leerob** [comment]
Hey! There aren't any that I'm aware of, but it should be doable (just requires hooking the latest versions together).
