### ISSUE TITLE
How to add Shopify's dynamic checkout feature?

### ISSUE THREAD

**Issue by jonrhmn** [vercel/commerce#1263]
I want to add a dynamic checkout button to product page so customers can use fast checkout options like Apple Pay, Google Pay, or Shop Pay etc.

How do I extend the current Shopify integration to include the dynamic checkout feature?

Any insights would be greatly appreciated. 🙏

**Comment by leerob** [comment]
Thank you for the suggestion! While we aren't planning on adding that, it could be a nice feature to add in your forked version of this starter repo 😄
