### ISSUE TITLE
Auth/Accounts

### ISSUE THREAD

**Issue by GabeCloud94** [vercel/commerce#1265]
It would be cool to see the customer accounts API being leveraged in this template.

**Comment by TotomInc** [comment]
Looks like Shopify has officially released a GQL Storefront API to manage this: https://shopify.dev/docs/api/customer

Would be awesome if integrated into the repository, however I guess it should be not too much complex to build this in top of the existing commerce solution.

**Comment by AP-monkey** [comment]
Did anyone manage to get the template to work with the Customer Account API? Any way to share the source code? 👍

**Comment by leerob** [comment]
Combining with https://github.com/vercel/commerce/issues/1270

https://github.com/vercel/commerce/pull/1305
