### ISSUE TITLE
Feature Request: Shopify stores support videos for items. Should add video to the product page?

### ISSUE THREAD

**Issue by rolandin** [vercel/commerce#1267]
Shopify stores support videos for items. Should add video to the product page?

<img width="1786" alt="Screenshot 2024-01-03 at 11 27 04 PM" src="https://github.com/vercel/commerce/assets/25238359/99c9d343-b744-4f3e-9fb0-6c69b7127742">

<img width="1547" alt="Screenshot 2024-01-03 at 11 28 03 PM" src="https://github.com/vercel/commerce/assets/25238359/e7065b5b-d687-48cc-abd1-d82056e476e9">

**Comment by leerob** [comment]
Thank you for the suggestion! While we aren't planning on adding that, it could be a nice feature to add in your forked version of this starter repo 😄
