### ISSUE TITLE
Vercel domain -> my domain redirect

### ISSUE THREAD

**Issue by danieldanielecki** [vercel/commerce#1274]
I have a shop on https://shop.ditectrev.com, but it redirects to https://shopify-ditectrev.vercel.app, which I think is fine from a technical point of view (webhooks are working), but I'd prefer the customer to see https://shop.ditectrev.com in the URL.

Is it somehow possible? Below is what I can see in domains on Vercal & Shopify.

<img width="1528" alt="Screenshot 2024-01-10 at 20 14 31" src="https://github.com/vercel/commerce/assets/12736263/13d1181e-4809-4bbf-985e-b0f13f1fe83e">

<img width="1664" alt="Screenshot 2024-01-10 at 20 12 57" src="https://github.com/vercel/commerce/assets/12736263/2df39afd-ea30-4c15-a82a-e95595f19a07">

**Comment by danieldanielecki** [comment]
Update: I've tried with instead of `shops.myspotify.com` by following https://vercel.com/docs/projects/domains/add-a-domain and the effect is the same, tried in storefront `hostname` values of my domain and Vercel's domain as well as different options to redirect via https://vercel.com/../settings/domains

<img width="1169" alt="Screenshot 2024-01-21 at 19 21 35" src="https://github.com/vercel/commerce/assets/12736263/9e93e159-d836-4f91-a32c-45751e48788d">

**Comment by Jwakers** [comment]
@danieldanielecki You aught to remove the redirect. If you are redirecting to the shopify URL, you are making the other one un reachable.

**Comment by danieldanielecki** [comment]
I had this setup, but it looks like there was/is some kind of long cache, because navigation started working as well as explained in https://github.com/vercel/commerce/issues/1281#issuecomment-1919599823.

I'm closing this issue, https://shop.ditectrev.com is up, and I removed the redirect on `Vercel`, it works. On Shopify, my custom domain is not connected (can't delete it btw, no idea why). I'm closing this issue, and leaving my domain setup on screenshots for others.
<img width="1414" alt="Screenshot 2024-01-31 at 18 44 25" src="https://github.com/vercel/commerce/assets/12736263/d3fcc058-3cb6-455f-b7d0-0b08adb1b34b">
<img width="837" alt="Screenshot 2024-01-31 at 18 45 08" src="https://github.com/vercel/commerce/assets/12736263/7e288573-fc7b-4eef-a4af-d116ceb6b337">

**Comment by vitustockholm** [comment]
you shop is working @danieldanielecki , but home page is still missing products and featured products slide

**Comment by danieldanielecki** [comment]
> you shop is working @danieldanielecki , but home page is still missing products and featured products slide

Yes, I opened different issues for that #1300, #1301.
Do you have some knowledge @vitustockholm to help me fix the issue with products and featured products slide?

**Comment by vitustockholm** [comment]
yes but i need to see code or repo, because now i commented on #1300 didnt see this, we need to know if You were following the guidelines from https://vercel.com/docs/integrations/cms/shopify ?

**Comment by danieldanielecki** [comment]
@vitustockholm commented in #1300. Let's keep it there!
