### ISSUE TITLE
Cannot Customize Checkout - Redirecting

### ISSUE THREAD

**Issue by simpslandyy** [vercel/commerce#1276]
I followed the instructions [here](https://vercel.com/docs/integrations/shopify) in the documentation, but whenever I go to customize the checkout page, I get this screen:

![image](https://github.com/vercel/commerce/assets/12716559/a7daddaa-ed0b-4f78-97ef-e57c87edd1eb)

The hostname is pointed to my vercel deployment hostname but nothing shows up.
I'm not too sure what I'm doing wrong. 

T_T Please help, thank you.

**Comment by leerob** [comment]
Hey there, unfortunately I am not able to reproduce this issue. Could you please try running through the set up / docs again? Sorry about this.
