### ISSUE TITLE
Pretty much everything is exceeding Vercel Edge function Size limits

### ISSUE THREAD

**Issue by Alick1997** [vercel/commerce#1277]
Deployed project as directed with vercel and received errors of the form:

`Error: The Edge Function "[page].rsc" size is 2.04 MB and your plan size limit is 2 MB. Learn More: https://vercel.link/edge-function-size`

These are not isolated to one function as one would expect, initially it was an index function, then it was the opengraph-image function which I fixed by commenting out font importation as follows:

`
...
    {
      width: 1200,
      height: 630
      /* fonts: [
        {
          name: 'Inter',
          data: await fetch(new URL('../fonts/Inter-Bold.ttf', import.meta.url)).then((res) =>
            res.arrayBuffer()
          ),
          style: 'normal',
          weight: 700
        }
      ]*/
    }
  );
}
`

I see that similar issues were fixed back in July 2023 among hobby users with a limit of 1MB, yet they seem to persist while I am using a PRO plan with edge function limit of 2MB.

**Comment by leerob** [comment]
We'll soon be moving to Partial Prerendering which runs on Node.js https://github.com/vercel/commerce/pull/1236
