### ISSUE TITLE
Missing Content: Home, Navigation, Settings (password protection), Pages & Branding changes not reflecting

### ISSUE THREAD

**Issue by danieldanielecki** [vercel/commerce#1281]
I followed the entire tutorial https://vercel.com/docs/integrations/shopify#configure-shopify and got working everything apart from the home content I can see on https://demo.vercel.store, navigation isn't showing up, when I tried to disable the shop with password protection - it didn't reflect, custom pages, and branding didn't update. I need clarification because whenever I update a product, it works perfectly fine.

Working deployments, continuously generated from https://github.com/Ditectrev/shop
<img width="1665" alt="Screenshot 2024-01-16 at 16 12 08" src="https://github.com/vercel/commerce/assets/12736263/ecd95092-d7c1-489f-96c6-8a6d36d348e7">

Regarding navigation I found a similar issue https://github.com/vercel/commerce/issues/1199, but [this comment](https://github.com/vercel/commerce/issues/1199#issuecomment-1871245121) didn't help. I tried to also deactivate the shop and redeploy again. My shop is available at https://shop.ditectrev.com (it redirects to Vercel's domain, still need to fix https://github.com/vercel/commerce/issues/1274).
<img width="1669" alt="Screenshot 2024-01-16 at 16 27 15" src="https://github.com/vercel/commerce/assets/12736263/42b5504c-3165-4136-b581-4a1f01b20a47">
<img width="1474" alt="Screenshot 2024-01-16 at 16 29 52" src="https://github.com/vercel/commerce/assets/12736263/27cfc062-d3ee-4b7c-addf-9e1bcfb4eed1">

With regards to branding, I could see a new favicon (remaining content was simply `Redirecting...`) before I re-connected a domain again after deactivation. However, when updated it in the storefront settings like on the screenshot below, I can't see the new favicon anymore.
<img width="1660" alt="Screenshot 2024-01-16 at 16 23 12" src="https://github.com/vercel/commerce/assets/12736263/f9733048-88b9-4194-a83e-f3dc9e4ffd92">

About the home, might it be related to issue https://github.com/vercel/commerce/issues/1207?

About custom page return `500`: https://shopify-ditectrev.vercel.app/pages/home & https://shopify-ditectrev.vercel.app/pages/contact

<img width="1667" alt="Screenshot 2024-01-16 at 16 27 01" src="https://github.com/vercel/commerce/assets/12736263/dcfef04e-5292-4035-ba7f-95342ae8e602">

I tried to add 2 new webhooks: `Shop update` and `Theme update`, but it didn't help to solve this issue. For me, it looks like some missing info from the docs to enable sync all stores settings, apart collections & products, which, as wrote earlier -  are working 100% fine thanks to webhooks (=webhooks are configured okay).

**Comment by danieldanielecki** [comment]
Regarding footer, the docs isn't correct showing 2 menus: https://vercel.com/docs/integrations/shopify#navigation-menus.

as per https://community.shopify.com/c/shopify-discussions/how-do-you-delete-a-menu/m-p/515524, it's not possible to delete the `footer` menu, but Vercel's docs suggests there should be just `vercel`-related handle menus.

**Comment by tonytangdev** [comment]
I had the same issue. I tried to look for the place where we fetch the menus and it is here : https://github.com/vercel/commerce/blob/main/lib/shopify/index.ts#L340

I added `cache: 'no-cache``to disable the cache and then I got my menus showing. If that does work for you, I think you should revert back the value before deploying.

**Comment by danieldanielecki** [comment]
> I had the same issue. I tried to look for the place where we fetch the menus and it is here : https://github.com/vercel/commerce/blob/main/lib/shopify/index.ts#L340
> 
> I added `cache: 'no-cache'` to disable the cache and then I got my menus showing. If that does work for you, I think you should revert back the value before deploying.

where did you add `cache: 'no-cache'`?

**Comment by danieldanielecki** [comment]
I haven't done absolutely anything and now I can see the navigation on https://shop.ditectrev.com (before custom domain was working, also on shopify URL), pages are still broken tho. Restricting users to password is also not helpful. It looks like the software is highly unstable for custom domains setups (other issue https://github.com/vercel/commerce/issues/1274). My most important problem was the navigation so closing the issue. I'll try to find a solution for the broken pages in other issues, but hopefully Vercel will make it more stable (again?).

**Comment by danieldanielecki** [comment]
PS. Branding also doesn't work as we can see on https://shop.ditectrev.com

**Comment by danieldanielecki** [comment]
Closing this issue, as I've created an issue for every problem I'm still facing: #1295 #1300 #1301.
