### ISSUE TITLE
Combine with pages router?

### ISSUE THREAD

**Issue by MrUltimate** [vercel/commerce#1288]
Hi,

I'm using Next 14 for an e-commerce site I'm building for a client. I've used this repository as a basis for what I've built so far. Unfortunately, the client wants page transitions in the site, for which I'm using `framer-motion` for. `framer-motion` is currently broken with the `app` router and therefore I've elected to use the `page` router instead.

As I understand it, both the `app` and `pages` routers can be used in conjunction. I'm trying to understand what's the best way to do so with this implementation. The `v1` branch of this repository seems to be outdated and much different approach then what this repository does, as far as I understand.

In an idea world, I can still use my currently built pages that use the `page` router and then pull in Shopify data from the `app` router. Any help or advice would be greatly appreciated.

**Comment by vitustockholm** [comment]
after a lot of issues i would love to use v1 version , but is it possible to find it at this time ? i got the production version of v2 deployed but its not what i expected , hardcoded lots and cms has gone, and then You loose the point to make a production version where you never come back to edit and leave 100% for a client to use cms as it was in disclaimer, v1 was better to go for production. not sure whats he question about using framer-motion , let us know particular parts of code used with framer-motion instead. it's possible to leave router alone and use framer-motion

**Comment by leerob** [comment]
If you are looking for the complete Pages Router version, you can still use v1 here: https://github.com/vercel/commerce/tree/v1
