### ISSUE TITLE
Search Page: Incorrect Sorting Order of Items

### ISSUE THREAD

**Issue by krishna-santosh** [vercel/commerce#1291]
When selecting the 'All' category on the search page and sorting by 'price' (either Low to High or High to Low), the displayed items (Bag) appear in the incorrect order. Here's the [URL](https://demo.vercel.store/search?q=black&sort=price-asc).

![image](https://github.com/vercel/commerce/assets/75202541/11242397-f92e-4e02-853c-0a1fa20ae2b7)

**Comment by sumon1991** [comment]
It's working perfectly fine now.

**Comment by leerob** [comment]
Woohoo!

**Comment by krishna-santosh** [comment]
It is still the same.

![image](https://github.com/user-attachments/assets/2db3bb30-d46a-4dce-8335-c471d79874aa)
