### ISSUE TITLE
Getting error on - pnpm dev

### ISSUE THREAD

**Issue by theDheerajjha** [vercel/commerce#1294]
Hi, I am trying to run project **locally** and getting this error - 
<img width="670" alt="image" src="https://github.com/vercel/commerce/assets/52864945/69bcf9b6-53b2-48fc-a841-e04539c94d2b">

I would be thankful for any help. Thanks!!

**Comment by manovotny** [comment]
It looks like you haven't [configured your environment variables](https://vercel.com/docs/integrations/shopify#configure-environment-variables) correctly or pulled them down locally from Vercel. Specifically the `SHOPIFY_STORE_DOMAIN` environment variable.
