### ISSUE TITLE
Policies have broken link: 500 error

### ISSUE THREAD

**Issue by danieldanielecki** [vercel/commerce#1295]
Policies from `Settings` -> `Policies` (https://admin.shopify.com/store/123456/settings/legal) aren't correctly displayed.

I tried to have them included in my footer, but those are redirecting to pages with `500` error code:
- https://shop.ditectrev.com/policies/contact-information
- https://shop.ditectrev.com/policies/legal-notice
- https://shop.ditectrev.com/policies/privacy-policy
- https://shop.ditectrev.com/policies/refund-policy
- https://shop.ditectrev.com/policies/shipping-policy
- https://shop.ditectrev.com/policies/terms-of-service

<img width="1176" alt="Screenshot 2024-02-07 at 14 34 06" src="https://github.com/vercel/commerce/assets/12736263/5c9615c8-e04a-4453-bca0-63bdf4d79804">
<img width="844" alt="Screenshot 2024-02-07 at 14 36 28" src="https://github.com/vercel/commerce/assets/12736263/febb6060-5588-4ede-873c-ade523a63c37">
<img width="988" alt="Screenshot 2024-02-07 at 14 36 45" src="https://github.com/vercel/commerce/assets/12736263/67139655-885a-4688-881b-187a1714a835">

**Comment by leerob** [comment]
This is because the "CMS" like pages, e.g. https://demo.vercel.store/shipping-return-policy, are at the root path.

You can view the code here: https://github.com/vercel/commerce/blob/main/app/%5Bpage%5D/page.tsx

If you would like to change that path, you could change to `app/policies/[page]/page.tsx`.

**Comment by danieldanielecki** [comment]
@vitustockholm, what do you think about the answer? You know more about all the bugs this repo has, esp. around routing.

**Comment by danieldanielecki** [comment]
Those are all working, but on the checkout page. Would be good to mention it somewhere!

**Comment by coopbri** [comment]
As @danieldanielecki mentioned above, this should be documented imo (at least in https://vercel.com/docs/integrations/ecommerce/shopify)

**Comment by danieldanielecki** [comment]
> As [@danieldanielecki](https://github.com/danieldanielecki) mentioned above, this should be documented imo (at least in https://vercel.com/docs/integrations/ecommerce/shopify), since Shopify sets these routes by default (https://help.shopify.com/en/manual/checkout-settings/refund-privacy-tos#add-policies-to-your-store-menus, https://help.shopify.com/en/manual/checkout-settings/refund-privacy-tos#add-links-to-your-policies-within-pages-or-on-social-media)

cc: @leerob
