### ISSUE TITLE
Overflowed Search on Tablet

### ISSUE THREAD

**Issue by danieldanielecki** [vercel/commerce#1306]
The search doesn't look good if there are 4 items in the menu, shop.ditectrev.com for live demo

![Screenshot 2024-03-11 at 18 26 37](https://github.com/vercel/commerce/assets/12736263/64f7bf28-4a2f-458b-a035-674b60e5804c)

**Comment by leerob** [comment]
Hey there, you can likely modify this with some CSS in your application (maybe decrease the size of the search?).

**Comment by danieldanielecki** [comment]
lol, it should stay as an improvement
