### ISSUE TITLE
How to add product metafield data

### ISSUE THREAD

**Issue by mhlauf1** [vercel/commerce#1307]
I've added rich text custom data to my products, labeled 'included'. product.metafields.custom.included - how do I add this into my product data on the frontend?

**Comment by osseonews** [comment]
I just actually did this in our custom implementation. You can read how to do it here: 
[How To Create and Use Shopify Metafields in Next.js Commerce](https://www.dalicommerce.com/docs/nextjs/create-and-use-shopify-metafields-nextjs)

**Comment by leerob** [comment]
Thanks @osseonews!
