### ISSUE TITLE
View Page/Product always gives 500

### ISSUE THREAD

**Issue by danieldanielecki** [vercel/commerce#1309]
The `pages` URL seems to be broken and instead of redirecting to `https://shop.ditectrev.com/products/amazon-web-services-certified-aws-certified-cloud-practitioner-clf-c02-practice-tests-exams-questions-answers` we should have `https://shop.ditectrev.com/product/amazon-web-services-certified-aws-certified-cloud-practitioner-clf-c02-practice-tests-exams-questions-answers`. Next, instead of redirecting to `https://shop.ditectrev.com/pages/contact` we should have `https://shop.ditectrev.com/contact`. Shocking amount of bugs as for Vercel standards.

**Comment by leerob** [comment]
Did you follow through https://vercel.com/docs/integrations/cms/shopify? 

https://github.com/vercel/commerce/issues/1285#issuecomment-2028752080

**Comment by danieldanielecki** [comment]
Yes, of course.
This repo has lots of routing-related problems.

**Comment by danieldanielecki** [comment]
@vitustockholm knows lots about bugs related to broken routes.
