### ISSUE TITLE
[Feature] Manage multi currency, with default value like i18n

### ISSUE THREAD

**Issue by djodjo02130** [vercel/commerce#131]
This option should be added for international shops.

- Like i18n customer can change currency in avaiblable list. 
- Default currency associate with domain like i18n: ".uk" -> GBP, ".fr" -> EUR ... etc
- Default currency associate with locale: en_gb -> GBP, fr_fr -> EUR ...etc

**Comment by manovotny** [comment]
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: #966
