### ISSUE TITLE
build erros

### ISSUE THREAD

**Issue by SergGrey1992** [vercel/commerce#1329]
Good afternoon!

Encountered this problem when building your template =(
[build_error.pdf](https://github.com/vercel/commerce/files/15095152/build_error.pdf)

I realized that TS doesn't understand the type of request graphql

my dependencies are exactly the same as in your repository

Can you tell me how I can fix this? 

because these errors prevent me from deploying my tutorial application. 

thank you for your help and future replies ))

**Comment by manovotny** [comment]
@SergGrey1992 notice all the `UNAUTHORIZED` messages in the GraphQL queries? That likely means your [environment variables](https://vercel.com/docs/integrations/cms/shopify#configure-environment-variables) are missing or incorrect.
