### ISSUE TITLE
How to translate products?

### ISSUE THREAD

**Issue by AmazingTurtle** [vercel/commerce#133]
**What's happening?**
My products are in english when I'm navigating through a spanish store.

**What do I expect?**
I want my products to be spanish. But I also have my store in english, so the same product should also remain to be available in english.

**Storytime** aka rant
So I am experimenting with this for a couple of hours now and I tried to add a new product in big commerce. I noticed, that when I switch from english to spanish, the **initially provided demo products are translated**. But what about a **custom product that I have created** just now? I can't find a single indicator about localization -- not in big commerce, not in this repository. What's even more confusing is that the used bigcommerce storefront data hooks make use of **undocumented graphql parameters**: https://github.com/bigcommerce/storefront-data-hooks/blob/f1be99f00f68c8c23e17e5ac0d7f1fa0e4ad4f8d/src/api/operations/get-product.ts#L9

So there must be two options on what's going on:
- I am literally retarded
- The documentation ~sucks~ leaves much to be desired

Can anyone help with this?

**Comment by okbel** [comment]
Hey, use friendlier language, please. Idk if you are familiar with open source, but be kind and respectful. It's an implicit rule.

**Comment by okbel** [comment]
And this is related to BigCommerce not to Next.js Commerce. @RayeEThompson

**Comment by nikitasol** [comment]
@okbel Hi! Is it possible that there is something missing on the bigcommerce end when creating a development storefront following easy setup option here: https://nextjs.org/commerce?

Dev docs for BigCommerce state that each language should have a separate storefront. From what I can see there is only 1 vercel storefront and there is no possibility to add additional ones, which is great as I would prefer managing all language at the same place, but at the same time there is no access to locales anywhere at the BC backend. I have tried creating another store as a trial to check if the option was locked to full accounts, but couldn't find anything there.

It's pretty clear how to translate pages, but how to translate products at the moment is not very clear. If you could point at the right direction would be great. Thanks

**Comment by AmazingTurtle** [comment]
After digging into the code I found that you can access overrides for fields like title and description for each language via the Product metadata (only accessible via API, no GUI). The namespace for the product metadata is the locale, e.g. en or de.

**Comment by nikitasol** [comment]
Thanks for the update @AmazingTurtle. Will have a look.

**Comment by manovotny** [comment]
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: #966
