### ISSUE TITLE
I have removed my configuration by accident - how do I bring it back?

### ISSUE THREAD

**Issue by AmazingTurtle** [vercel/commerce#134]
Let's make it short. I hit the small red button and now it's gone.

![image](https://user-images.githubusercontent.com/2357438/103033812-aeb35800-4563-11eb-9db9-716040d4ef23.png)

I know that this integration has provided environment variables. But here we go:

- Which environment variables are we talking about? And what are their values?
- How do I add the integration again? I can't find it on the marketplace.
- Why is nextjs promoting [commerce](https://nextjs.org/commerce) when the bigcommerce integration used in their demo hasn't been review by vercel yet?

**Comment by leo** [comment]
Hey!

> Which environment variables are we talking about? And what are their values?
> How do I add the integration again? I can't find it on the marketplace.

At the moment, the integration is designed to only be installed via the [Next.js Commerce](https://nextjs.org/commerce) flow.

To add it back, I recommend using the flow to create a new Vercel Project and then replace the Git repository that it's connected to with the old one in the Project Settings. You can also tweak the name of the Project there.

We're working on making sure the integration doesn't render this banner and making it possible to install the integration outside of the [Next.js Commerce](https://nextjs.org/commerce) flow.

I hope this helps. Thank you so much for your feedback!
