### ISSUE TITLE
Feature: rating/review

### ISSUE THREAD

**Issue by danieldanielecki** [vercel/commerce#1347]
It's currently not possible to review & rate the products.

I've tried to integrate it with the most popular Shopify's Review plugin `Judge.me Reviews`, but the setup fails due to not existing file `templates/product.liquid editor` it requires.

It'd be great to have it, the products would rank higher in `Google Shopping` & it'd be possible to have it integrated in `Google Customer Reviews.`

<img width="1661" alt="Screenshot 2024-06-23 at 19 45 02" src="https://github.com/vercel/commerce/assets/12736263/b784ef1c-c92f-492a-b1e9-1363c2f39888">
<img width="1667" alt="Screenshot 2024-06-23 at 19 46 09" src="https://github.com/vercel/commerce/assets/12736263/8f2d9811-d702-4f4b-960e-67fbb5af6352">

**Comment by leerob** [comment]
Thanks for the suggestion! While we don't plan to add it to this template, it's possible someone could fork this and add it there 😄

**Comment by coopbri** [comment]
@danieldanielecki if it helps, I got this working well with Junip (free tier has unlimited reviews and it works perfectly with headless): https://junip.co/

If interested in this, follow these docs: https://help.junip.co/en/articles/4607115-custom-html-installation

Not affiliated in any way, just seemed to be one of the more seamless Shopify headless integrations.

**Comment by danieldanielecki** [comment]
> [@danieldanielecki](https://github.com/danieldanielecki) if it helps, I got this working well with Junip (free tier has unlimited reviews and it works perfectly with headless): https://junip.co/
> 
> If interested in this, follow these docs: https://help.junip.co/en/articles/4607115-custom-html-installation
> 
> Not affiliated in any way, just seemed to be one of the more seamless Shopify headless integrations.

Would you mind to share a link to your shop with that integration?

**Comment by coopbri** [comment]
> > [@danieldanielecki](https://github.com/danieldanielecki) if it helps, I got this working well with Junip (free tier has unlimited reviews and it works perfectly with headless): [junip.co](https://junip.co/)
> > If interested in this, follow these docs: [help.junip.co/en/articles/4607115-custom-html-installation](https://help.junip.co/en/articles/4607115-custom-html-installation)
> > Not affiliated in any way, just seemed to be one of the more seamless Shopify headless integrations.
> 
> Would you mind to share a link to your shop with that integration?

Oh, sure thing. Note my shop is brand new, so I don't have any reviews yet, but here's the link: https://store.aerialbiotechnics.com. **IMPORTANT:** Junip, by default, doesn't display review-related content if a product doesn't have any reviews (I am still working through customizing this, I *want* to show that a product has no reviews and make a CTA to review).

With that said, you can force Junip to show fake, sample data with the `junip-preview-mode=true` query param, e.g. https://store.aerialbiotechnics.com/product/beetroot?junip-preview-mode=true **(again, this data is completely fake)**

Long-term, I'd like to use a FOSS implementation for reviews, I don't like using these Shopify apps at all, just nice for bootstrapping. So I'm not partial to Junip at all, it's just solving the problem right now. I'm huge on launching and iterating.

Btw @danieldanielecki, I keep seeing you on issues in this repo that you and me are aligned in. Let's connect bro! Reach out to me on https://www.linkedin.com/in/coopbri, https://x.com/0xcoop, or whatever you prefer, I am more than happy to discuss headless commerce approaches with Shopify and issues I've run into. I also have experience with this, Saleor, Medusa, Vendure, and working on my own FOSS ecom platform so we can talk about any of that if helpful.
