### ISSUE TITLE
Product URL segment

### ISSUE THREAD

**Issue by karlthomaas** [vercel/commerce#1349]
I noticed that this project uses the "product" URL segment instead of "products" like Shopify does. Consequently, without additional configuration, URLs of the form "https://abcde-fg.myshopify.com/products/abc" redirect to "https://store.vercel.app/products/abc," resulting in a 404 error. This is because this template uses "product" instead of "products."

Is there any benefit or particular reason for using "product"?

**Comment by fjohanssondev** [comment]
Not that I'm aware of. We switched over to use the _/products_ segment instead and has worked flawlessly. Just remember to change it where it's needed (SEO, handles etc).

**Comment by leerob** [comment]
^ Indeed, we recommend using `products` 😄
