### ISSUE TITLE
Access denied for menu field. Required access: `unauthenticated_read_content` access scope.

### ISSUE THREAD

**Issue by mikejw** [vercel/commerce#1350]
Hi there,

I'm pretty sure I've followed all the necessary steps for running with Shopify but I'm getting this error when attempting to load the index page.  I'm quite certain that I've created a storefront api app correctly enabled this access scope.

Any ideas where I can start to diagnose this issue?

Many thanks.

**Comment by Yaucrates** [comment]
Try to set env.example to env.local

**Comment by neilk17** [comment]
Were you able to find a fix to this? I'm facing the same
