### ISSUE TITLE
Add Theme Switcher Feature in Navbar

### ISSUE THREAD

**Issue by abdellatif-laghjaj** [vercel/commerce#1359]
### Description

A theme switcher feature in the navbar would significantly improve the user experience by allowing users to toggle between light and dark modes. This feature is especially useful for users who prefer a specific theme for better readability or to reduce eye strain.

### Feature Request

- Add a theme switcher (light/dark mode) toggle button in the navbar.
- Ensure the selected theme persists across sessions.
- Implement smooth transitions between themes for a seamless user experience.
- Make the design of the switcher intuitive and accessible.

### Benefits

- Enhances accessibility by providing a dark mode option for users.
- Improves user experience by allowing personalization based on user preferences.
- Keeps the design modern and up-to-date with current web trends.

**Comment by davialano** [comment]
Hi @abdellatif-laghjaj, I'm interested in this issue, can I colaborate it?

**Comment by abdellatif-laghjaj** [comment]
> Hi @abdellatif-laghjaj, I'm interested in this issue, can I colaborate it?

Yeah sure, feel free my friend

**Comment by leerob** [comment]
I'd like to keep this focused on system/light/dark auto-detection. I don't think the additional code for the auto theme switcher is something we're interested in adding, but if it's a feature you want, please feel free to add in your fork!
