### ISSUE TITLE
Image slider shows all images when navigating from product page to product page.

### ISSUE THREAD

**Issue by tkapitein** [vercel/commerce#136]
https://user-images.githubusercontent.com/37157784/103277396-2d2b5200-49c9-11eb-8891-a2f842ec533d.mov

Used browser: Google Chrome

When you visit a product page and visit another product page via the shoppingcart, all product images will show in the slider.  It seems that the product slider components acts on the props of the previous productpage.

**Comment by okbel** [comment]
Amazing thank you
