### ISSUE TITLE
showcase page links to old version

### ISSUE THREAD

**Issue by thenbe** [vercel/commerce#1371]
The [showcase](https://vercel.com/templates/next.js/nextjs-commerce) page for this template mentions app router, but the "code" hyperlink points to an old [branch](https://github.com/vercel/commerce/tree/v1) (`v1`), which does not use the app router.

**Comment by leerob** [comment]
The code link is on the callout that says "Looking for v1?" (It's from the README here).

**Comment by thenbe** [comment]
> the callout that says "Looking for v1?"

Oops. I really need to start reading sentences from the beginning.
