### ISSUE TITLE
How to get product translations?

### ISSUE THREAD

**Issue by steinarbragi** [vercel/commerce#1373]
I have a site in two languages using next-intl. I have the same two languages configured in Shopify and have translated some products. How can I fetch the translations?

**Comment by 6ichem** [comment]
To translate products you use Translate & Adapt app from Shopify, for the coding side you can do as mentioned here in the docs https://shopify.dev/docs/storefronts/headless/building-with-the-storefront-api/markets/multiple-languages

You need to add the `@inContext()` handle in each query and pass the language to it with a variable, like the following `@inContext(language: LanguageCode)` set the variable to the language code like EN for English, FR for French etc

Example for products query:
```
export const getProductQuery = /* GraphQL */ `
  query product($language: LanguageCode) @inContext(language: $language) {
    product(handle: $handle) {
      ...product
    }
  }
  ${productFragment}
`;
```

You can have a value hardcoded for the language but if you're using next-intl with some language switching logic in the front-end then pass a variable to the query

**Comment by leerob** [comment]
Thank you @6ichem 🙏
