### ISSUE TITLE
Cant Connect BigCommerce, Vercel Connection Down?

### ISSUE THREAD

**Issue by ozeitis** [vercel/commerce#1376]
Using the template "Connect BigCommerce Integration" button, I get the error "The page URL is invalid. Please contact Vercel support for assistance."

I have tried on different browsers and devices even. No luck same error.

**Comment by leerob** [comment]
Would you mind opening an issue on their repo if you are still having problems? 🙏 

https://github.com/bigcommerce/nextjs-commerce
