### ISSUE TITLE
Product not deleting after clicking 'x' in cart

### ISSUE THREAD

**Issue by tsgc1422** [vercel/commerce#1384]
Hi team, first of all, thank you for this e-commerce template!

We've run into an UI issue where the cart is not clearing item(s) from the cart after clicking the 'x' button (please see video attached). The functionality works fine but the UI is glitching like this sometimes, not all the time. I'd appreciate any ideas on how this could be fixed.

https://github.com/user-attachments/assets/4765326a-da85-4f4e-9f36-ae241f2147cf

Thank you!

**Comment by leerob** [comment]
Hey there, I'm not sure we are able to help here as we cannot reproduce this issue on `main` here.

My assumption would be there's some server error happening, which is making `useOptimistic` reset. I would suggest checking your terminal output for errors and adding some logging to see where the issue might be 🙏
