### ISSUE TITLE
Update to Next.js 15 with Typed App Router, Data Fetching, and Shopify Client Organization

### ISSUE THREAD

**Issue by humbernieto** [vercel/commerce#1401]
Description:

Upgrade project to Next.js 15 and implement the new typed App Router.
Refactor data fetching to align with the latest Next.js practices.
Improve the organization and structure of the Shopify client to enhance maintainability and performance.
Tasks:

Upgrade Next.js to version 15.
Update routing to use the typed App Router.
Refactor data-fetching methods for improved consistency.
Reorganize Shopify client structure for better code clarity and efficiency.
Notes:
Ensure backward compatibility where necessary and optimize for any breaking changes introduced in Next.js 15.

**Comment by leerob** [comment]
This is on Next 15 and the recommended patterns!
