### ISSUE TITLE
Do i have to use Graphql?

### ISSUE THREAD

**Issue by abdokouta** [vercel/commerce#141]
hello, i would like to ask if i want to build my own Commerce API provider same as the example of big commerce do I have to use graphql or rest API will be just fine?

**Comment by JusticeBringer** [comment]
I would also like to know the answer for this question.

**Comment by elhe26** [comment]
Any updates?

**Comment by cpv123** [comment]
You are not required to use GraphQL, a REST API will also work fine.

Although some providers use GraphQL (like BigCommerce as you mention), there are also some providers that are using REST APIs such as OrderCloud and Saleor. 

https://github.com/vercel/commerce/tree/main/framework
