### ISSUE TITLE
cross-site cookies are not allowed when working locally

### ISSUE THREAD

**Issue by lerer00** [vercel/commerce#142]
Hello, there seems to be a  problem with same-site cookies when developing locally. My BigCommerce store is fresh out the box and I just cloned this repo. All configurations in the .env.local are updated and everything is working fine. The only thing is that I can't log in when working locally. When I deploy in "prod" everything is working fine. Here's a screenshot of the chrome debug tool.

![chrome_2021-01-02_00-05-24](https://user-images.githubusercontent.com/20174549/103451310-487bb300-4c90-11eb-85a5-da5800c4e407.png)

Is it something wrong with my BigCommerce store? 
Is there a 'development' setting that I need to add somewhere? 

Step to reproduce.
- clone repo
- change configurations in .env.local
- yarn
- yarn dev
- sign up (create a dummy user)
- login

Any help would be cool.

**Comment by stevejhiggs** [comment]
I had a pr merged into https://github.com/bigcommerce/storefront-data-hooks/releases/tag/v.1.0.3 to fix exactly this issue. Unfortunately a new version of the package does not appear to have been released to npm yet.

**Comment by manovotny** [comment]
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: #966
