### ISSUE TITLE
[QUESTION] Roadmap & current status of project

### ISSUE THREAD

**Issue by agcty** [vercel/commerce#143]
I'm checking back and forth if there is any change in this repo because there is no way to know how far advanced development is. 

E.g I'd be really interested in a shopify integration and would even be willing to help build but I just don't know what the current status of this project is. How much development still needs to be done for "Modules for external providers" #2 ?

I really would love to help but without knowing what has to be done or how far the progress is I can't really help.

Is there any kind of roadmap of features that I don't know about? The GitHub kanban board has last been updated in November...

**Comment by huuphongnguyen** [comment]
Total agreed with you. This project looks like abadoned by Vercel team (*look like). Shopify integration is needed.

**Comment by markfranco** [comment]
It seems like to me they are relying on the open-source community to do the integrations, based on how they have put here in https://github.com/vercel/commerce-framework. The 3rd of December is the last commit in that repo.

> This repository serves as a model to build your own hooks for Next.js Commerce. We encourage contributors and teams to build their own hooks under a separate package with the corresponding configuration. An example of using this repository as a seed are the hooks we built with BigCommerce.

I'm only assuming once someone has put forward a PR to replicate @okbel's example for BigCommerce that's all that needs to be done for that said integration.

**Comment by lachlanjc** [comment]
I'm not from Vercel, but it seems like between https://github.com/vercel/commerce/commit/7401f4e4176fdcfae2dceca115905a40ca011147 & #140, they're making daily progress toward other providers (https://twitter.com/okbel/status/1326534978759319552?s=20). Even this morning: https://twitter.com/rauchg/status/1346837297853992960?s=20

**Comment by petermekhaeil** [comment]
For Shopify integration, see https://github.com/vercel/commerce/issues/2#issuecomment-755450563.

**Comment by okbel** [comment]
https://github.com/vercel/commerce/issues/2#issuecomment-755496891

Just added this comment here, I hope this clears things out 🙏 

@lfades is actively working on the Shopify Integration.
