### ISSUE TITLE
Robots.txt and sitemap.xml

### ISSUE THREAD

**Issue by Maaasyn** [vercel/commerce#153]
As far as I can tell, robots.txt and sitemap.xml are not implemented in this project. Could you add those files on each build? Also, it would be nice to have this feature backed in nextjs, as it allow search engine to understand structure of our pages.

**Comment by manovotny** [comment]
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: #966
