### ISSUE TITLE
RFC: Real World Commerce Example

### ISSUE THREAD

**Issue by timuric** [vercel/commerce#159]
It would be great to see a more complete picture how would Next.js can be used with multi currency, multi country store (different stock sources) with a larger catalogue with at least 20 categories of products with amount of products enough to demonstrate pagination, dynamic filtering etc. While current demo does demonstrate the basics it does not give a glimpse to a real world solution and approaches to scaling it. I believe such demo would be more pursue more developers to take next.js in consideration when building an online store.

**Comment by okbel** [comment]
Absolutely, are you willing to draft the spec with me?

**Comment by timuric** [comment]
> Absolutely, are you willing to draft the spec with me?
Sure, currently I am working on porting a store to Next.js that has all of the above mentioned features and more. So I can hopefully can contribute by sharing my experience so far.

**Comment by amesas** [comment]
As a reference: https://www.vuestorefront.io

**Comment by okbel** [comment]
@timuric Golden, feel free to use this space. Will open an RFC soon.

**Comment by timuric** [comment]
Cool. I would brake down all features in separate comments. 

Feature: **Multi country store**

Any store that operates in multiple regions would have a country selector which would have an impact on at least few essential things:

• Currency & Price
• Delivery info
• Stock availability

Similar the way Next.js handles language preferences it would be necessary to detect default country the user is based and apply these settings in cookies and reflect them in the URL path. Similar to language it would be necessary to automatically select appropriate country without having it explicitly in the URL.

Consider a case where a product is featured in social media ads or a tweet, customers normally would be automatically directed to a relevant store for their region. 
As an example a link on social media would look like: ```https://demo.vercel.store/product/lightweight-jacket``` and would redirect users to something like this ```https://demo.vercel.store/[country]/[language]/product/lightweight-jacket```

Country detection is not as trivial as a language locale which sent by the browser, however some CDNs like Cloudflare do provide country info in headers when proxying the request to the application server, hopefully this can be achieved with Vercel as well.

**Comment by timuric** [comment]
Example of **dynamic and static data on the page**:

Consider a product page where mostly data is static with few exceptions like **Wishlist** aka **Favorite button**
A straightforward solution would be to use ```getServerSideProps``` to get user specific state of that button, however that would downplay all static generation benefits that most of us like about in Next.js.

At this point there is no guide about how to best mix dynamic and static data and perhaps it is something that yet to come in form of a new feature, but it would be great to at least have an example that can be used as reference. 

Here is a reference to a relevant discussion:
https://github.com/vercel/next.js/discussions/11424#discussioncomment-281713

**Comment by timuric** [comment]
Consider a case when navigation and footer have elaborate data structures with images and lots of categories. For example: [https://www.gucci.com/ ](https://www.gucci.com/ )
How would one decide to fetch such components, with current setup it would mean that navigation and footer data would be fetched with every page request, which is pretty wasteful.

**Comment by eclipse3161** [comment]
Hi

I'm building Multi currency and Multi language store using vercel and Big commerce. the only issue currently I'm having is nextJS is blocking calls to location API so multi-currency and multi-language are not working see link below
https://commerce-hupmzfomo.vercel.app/

**Comment by codemem** [comment]
> Hi
> 
> I'm building Multi currency and Multi language store using vercel and Big commerce. the only issue currently I'm having is nextJS is blocking calls to location API so multi-currency and multi-language are not working see link below
> https://commerce-hupmzfomo.vercel.app/

Nextjs is not blocking you. It's browser behaviour. If you access geoip by https (you are using http). It will work

**Comment by johnbwu** [comment]
@eclipse3161  did you ever get your multi-currency working?

**Comment by eclipse3161** [comment]
Yes  ---- On Sun, 13 Jun 2021 14:14:38 -0700  ***@***.***  wrote ----
@eclipse3161  did you ever get your multi-currency working?

**Comment by johnbwu** [comment]
> Yes  ---- On Sun, 13 Jun 2021 14:14:38 -0700 ***@***.*** wrote ---- @eclipse3161 did you ever get your multi-currency working? —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

How did you get the cart to work? With bigcommerce my cart always returns in the default currency

**Comment by manovotny** [comment]
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: #966
