### ISSUE TITLE
Integration with Typesense for Instant Search?

### ISSUE THREAD

**Issue by jasonbosco** [vercel/commerce#16]
Hello, 

Thank you for putting this commerce starter kit together. At my previous role in an [ecommerce startup](https://www.verishop.com/), we used Next.js and we basically had to figure out most of these patterns and integrations ourselves. Something like this would have sped up our discovery and development process.  So I really appreciate your work!

I currently work on an open source alternative to Algolia, called [Typesense](https://github.com/typesense/typesense) and I'd love to build an integration that showcases how to use Typesense to power site search on Next.js commerce sites. Would you be open to including this integration as part of the commerce starter kit?

The search experience would be similar to what you see [here](https://www.verishop.com/search?q=pant), but built with a Typesense backend.

**Comment by manovotny** [comment]
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: #966
