### ISSUE TITLE
Provider: CommerceTools

### ISSUE THREAD

**Issue by okbel** [vercel/commerce#163]
Ecommerce Provider: https://commercetools.com/

**Comment by MitchStarkTekton** [comment]
We're considering utilizing CommerceTools for an ecommerce backend and wanted to check-in on this. Is anyone known to be working on this integration, or are there any plans of a timeline for this?

**Comment by MitchStarkTekton** [comment]
@okbel - I'm _considering_ creating this. I took a look at the "Adding a new provider" docs (https://github.com/vercel/commerce/blob/main/framework/commerce/new-provider.md) and noticed that there's a TODO related to a PR that has already been merged. Do the docs need updating, or am I good to follow those instructions for adding a new provider?

**Comment by PeterKDex** [comment]
Did anyone ever build something out for CommerceTools? Needing it as well.

**Comment by Fedeorlandau** [comment]
What about this? https://github.com/vercel/commerce/pull/403/files

**Comment by rm-sf** [comment]
any update on commercetools?

**Comment by MitchStark10** [comment]
Looks like there's a PR open for a starting point with commercetools (though it _seems_ there's still some work remaining): https://github.com/vercel/commerce/pull/774

**Comment by manovotny** [comment]
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: #966
