### ISSUE TITLE
Provider: Salesforce Commerce Cloud

### ISSUE THREAD

**Issue by okbel** [vercel/commerce#164]
## Provider: Salesforce Commerce Cloud
Commerce Provider: https://www.salesforce.com/products/commerce-cloud/ecommerce/

### Features 
-  **Catalog**
- [x] getProduct
- [x] getProducts
- [x] usePrice
- [x] useSearch
-  **Cart**
- [ ] useCart
- [ ] useAddItem
- [ ] useUpdateItem
- [ ] useRemoveItem
- **Authentication**
- [ ] useSignup
- [ ] useLogin
- [ ] useLogout
- **Customer**
- [ ] useCustomer
- **Wishlist**
- [ ] useWishlist
- [ ] useAddItem
- [ ]  useRemoveItem

**Comment by cellmanguney** [comment]
Hi @okbel Yes I can take the Salesforce Commerce Cloud implementation part!

**Comment by okbel** [comment]
Lovely!! Thank you. 
- We need these (utilities)[https://github.com/vercel/commerce/tree/agnostic#structure] 
- Submit a PR adding a folder under `/framework` that exposes those functions.
- Once `agnostic` branch is merged, everybody will be able to use this provider.
- Let me know if you have any questions. Also reacheable at Twitter @okbel.

**Comment by delros** [comment]
Hi @okbel, @cellmanguney
Do we have already any progress in the scope of SFCC provider integration? If this can be possible, I would like to join the integration efforts and contribute there

**Comment by cellmanguney** [comment]
Hi @delros 
I have started the integration roughly, set a on-demand Sandbox with commerce API ready with ShopAPI user. Which can connect now.
I couldn't find a time for deep dive yet ), any effort would be more than welcome.

**Comment by delros** [comment]
@cellmanguney ok, that's sounds good enough :) let's start and try to collaborate then. Can we have short call or chat? Where can I contact you?

**Comment by Trimud** [comment]
Hi @cellmanguney, do you need any help with this? We will be starting a new project soon and I don't want to reinvent the wheel :)

**Comment by MarkiyanPyts** [comment]
@cellmanguney , @delros Did you have a chance to sync up on this? I am from same company with @Trimud here and we have experience in sfcc headless refapps dev would be great to have SFCC provider in Next Commerce as well. Please let us know how we can contribute and what is current status on your side.

**Comment by cellmanguney** [comment]
hi @MarkiyanPyts , @Trimud 
That would be great if you can participate the development, so far I couldn't make time to dive in, you can take the lead.
Also I'm fine to take part of code-reviews and fix some parts.

do you have access to Vercel Slack  ? if not @okbel can we invite @MarkiyanPyts @Trimud @delros to Vercel Slack?
We can create a channel there and keep in touch more and follow up all the process, maybe have some meetings.

**Comment by MarkiyanPyts** [comment]
Hello, @cellmanguney thanks for answering, 

No we don't have access to slack yet but would be great to have access to be able to better follow what's going on,

Then, let's see where we are,
short status meeting would be good to see what is the current Repo branches and so on

**Comment by cellmanguney** [comment]
@Trimud 
I will try to send invite to Slack, if not probably @okbel can fix that.
Meanwhile let's make a hangout call for plan. I will send you an email (the one at your github landing page)
so we can continue from there

**Comment by ugurtemiz** [comment]
Hi @cellmanguney and @okbel ,
I would be happy to contribute as well. Can I also join to the team/slack channel etc?

**Comment by okbel** [comment]
Absolutely, can you hand me your emails through Twitter DMs? @okbel @MarkiyanPyts @ugurtemiz @Trimud

**Comment by Trimud** [comment]
Hi @okbel I hope you have received my message in Twitter?

**Comment by Trimud** [comment]
Hi @okbel do you have any updates?

**Comment by fncmedia** [comment]
@okbel ,  @cellmanguney  Is there already a timeline that you have in mind?

**Comment by okbel** [comment]
We're actively working on this but if there's any available contributor who wants to help ping me. @okbel.

**Comment by Trimud** [comment]
Hi @okbel 

I believe I have pinged you several times already but I didn't get anything back from you :)

**Comment by okbel** [comment]
@trimud ;) check your twitter messages
