### ISSUE TITLE
Provider: Tiendanube

### ISSUE THREAD

**Issue by leidison** [vercel/commerce#165]
Ecomerce Provider: https://github.com/TiendaNube/api-docs

**Comment by okbel** [comment]
@leidison : Are you able to work on it?

**Comment by sveggiani** [comment]
I think we have a good opportunity to contribute to this while we build the foundations of the technological platform for https://litt.com.ar/.

I'm currently working on those definitions during these days and I would like to know if you have some things in mind to this regard @okbel . Thanks!

**Comment by manovotny** [comment]
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: #966
