### ISSUE TITLE
Bigcommerce Hooks: setting basePath in next.config.js

### ISSUE THREAD

**Issue by Crelloc** [vercel/commerce#168]
I am currently testing for using a basePath with vercel commerce.

For example: setting basePath in next.config.js should route localhost:3000/blog to localhost:3000/some-base-path/blog

Setting basePath causes issues with Bigcommerce webhooks or data search to not function properly. 

However, basePath is working as expected for each 'next/Link'
  
I have only tested, "adding a product to cart" and "clicking on a category , and  searching for a product".  I'm sure other webhooks don't function properly as well.

The webhooks in index.tsx work properly, as the products can be viewed on the homepage. And when clicking a product from the homepage, the product appears on product page. And when viewing a product page, clicking on "add to cart" doesn't add product to cart.

Also, from the homepage, clicking on a category or searching for a product, the searching/query webhook doesn't properly retrieve products and causes the search to hang.

**Comment by Crelloc** [comment]
To be more precise, the following is a log of the error:

ready - started server on http://localhost:3000
event - compiled successfully
event - build page: /next/dist/pages/_error
wait  - compiling...
event - compiled successfully
Error occurred proxying http://localhost:4000/shop/_next/image?url=https%3A%2F%2Fcdn11.bigcommerce.com%2Fs-nhkhnjet1i%2Fimages%2Fstencil%2Foriginal%2Fproducts%2F133%2F446%2Fmockup-ae9a83b0__49881__78743.1604116316.png&w=3840&q=85 Error: socket hang up
    at connResetException (internal/errors.js:609:14)
    at Socket.socketCloseListener (_http_client.js:401:25)
    at Socket.emit (events.js:326:22)
    at TCP.<anonymous> (net.js:675:12) {
  code: 'ECONNRESET'
}

**Comment by okbel** [comment]
Looks like this should be solved already.
