### ISSUE TITLE
Provider: Local API Routes

### ISSUE THREAD

**Issue by janus-reith** [vercel/commerce#169]
It would be possible to create a self-contained provider which works based on api routes and requires no communication with a third party ecommerce solution.
I'd like to discuss wether this would be within the scope of this project, also if submissions for something like that would be accepted in general.

**Comment by madroneropaulo** [comment]
Yeah, it would be nice to have a clean typescript interface that can be attached to any API.

**Comment by manovotny** [comment]
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: #966
