### ISSUE TITLE
Deployment failed

### ISSUE THREAD

**Issue by jheyer159** [vercel/commerce#17]
Attempting to deploy a production site results in the following error.

> queryA ENOTFOUND store-...-....mybigcommerce.com at QueryReqWrap.onresolve [as oncomplete] (dns.js:203:19)

Vercel app is installed on BigCommerce and Vercel bot is connected to my Github account.   Tried removing the apps and re-deploying, but hit the same issue.  BigCommerce subscription is active. 

Is there something else that needs to be configured?

**Comment by okbel** [comment]
Hey Jeremy, we already reported BC Team about this. Have you tried running it locally just in case?
 
By adding, `.env.local`

```sh
BIGCOMMERCE_STOREFRONT_API_URL=<>
BIGCOMMERCE_STOREFRONT_API_TOKEN=<>
BIGCOMMERCE_STORE_API_URL=<>
BIGCOMMERCE_STORE_API_TOKEN=<>
BIGCOMMERCE_STORE_API_CLIENT_ID=<>
```
Let me know!

**Comment by jheyer159** [comment]
Ran `vercel env pull .env.local` - the file looks like the one above.
`yarn dev` -> opening `localhost:3000` still seeing the same error locally.

I noticed that the Vercel integration was showing as 'inactive' in the Channel Manager on BigCommerce.  I've tried toggling it to active, it disappears, but it doesn't change the error.

**Comment by okbel** [comment]
Any updates here? Do you have the same issue now? We updated our README - So if you deployed and integrated with Vercel then you should be able to pull the env vars. I'll recommend to erase all and start fresh if you still can't make it work. LMK!

**Comment by jheyer159** [comment]
Still getting the same error.  I tried going through the deployment process again with a separate Github, Vercel, and BigCommerce account with no issues.  

The main differences that happened between successful and failed deployment
 - I tried linking Vercel to a GH org account, which caused an error and I had to delete  / re-create the Vercel project because the redirect was stuck. 
- I already had a BigCommerce account and went through the `Sign In` flow rather than the `Sign Up` flow. 

My credentials are still resulting in a store that's not found, but starting fresh with the `Sign Up` flow resulted in a successful deployment.  I'm assuming the failed credentials are stale because I had to delete / re-create the connections.
