### ISSUE TITLE
Provider: Reaction Commerce

### ISSUE THREAD

**Issue by janus-reith** [vercel/commerce#170]
I would like to have an Integration with [Reaction Commerce](https://reactioncommerce.com/).
https://github.com/reactioncommerce/reaction

I can't commit to building it right now, but I'd love to find the time for it someday.

**Comment by loan-laux** [comment]
For anyone interested, I'm currently working on a provider for RC... I have the home page, categories page and PDP working. Still very much a WIP, the cart and checkout system isn't wired up yet for example. I'll post updates when I have more.

https://user-images.githubusercontent.com/45489203/110637588-fe9ad600-81c6-11eb-9cf6-3eb08cb29bde.mov

**Comment by manovotny** [comment]
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: #966
