### ISSUE TITLE
Feature API

### ISSUE THREAD

**Issue by okbel** [vercel/commerce#175]
# Feature API

Merging the new `agnostic` branch will require to ensure feature parity to maintain a consistent UI. Some providers do not offer features like `wishlist`, `cart` or `recommendations`, among others. 

Developing a Feature API will enable Commerce to turn off and on parts of the UI based on the selected provider.
There are some caveats for this approach:

- Bundle should ship with all needed for the selected provider.
- Possibly, each provider should expose a `config.json` at their root to show what they are capable of.

[WIP]

**Comment by mohammadou1** [comment]
Exporting a config.json is good idea
Maybe we should create a template for it

But first we will need to see what every provider may or may not have as a default feature

**Comment by robbieaverill** [comment]
A schema for config.json might be nice too, to keep everyone in line!

**Comment by okbel** [comment]
https://github.com/vercel/commerce/pull/199
