### ISSUE TITLE
How is the content translated on the demo?

### ISSUE THREAD

**Issue by magicspon** [vercel/commerce#198]
https://demo.vercel.store/es

Where is the spanish translations defined? 

I can't see anything in bigcommerce, and i'm struggling to find anything in this code base.

thanks

**Comment by petermekhaeil** [comment]
Next.js has built-in support for internationalized (i18n) routing:
https://nextjs.org/docs/advanced-features/i18n-routing
https://github.com/vercel/commerce/blob/master/next.config.js#L10

BigCommerce (the backend provider behind the demo) supports locale according to the APIs to fetch the products:
https://github.com/vercel/commerce/blob/master/framework/bigcommerce/api/operations/get-all-products.ts#L12

Pages urls for each products are generated here using `getStaticPaths`:
https://github.com/vercel/commerce/blob/master/pages/product/%5Bslug%5D.tsx#L41
