### ISSUE TITLE
Is there a way to just use the frontend of this repo with our own custom APIs?

### ISSUE THREAD

**Issue by AdityaAnand1** [vercel/commerce#200]
The design and cart/order flows of this repo are an excellent starting point, would be great if we could just utilize the frontend theme alone to build custom e-commerce stack. 

Is there a way to do this?

(Context: I'm not using BigCommerce, but working on something that would output stores such as BigCommerce/Shopify, so one level up the stack)

**Comment by AdityaAnand1** [comment]
@okbel @lfades any thoughts?

**Comment by lfades** [comment]
@AdityaAnand1 We're aiming to take the project there, where it can support different providers and it's agnostic to whatever provider you choose
