### ISSUE TITLE
Is there a way to view dummy data/components alone?

### ISSUE THREAD

**Issue by AdityaAnand1** [vercel/commerce#201]
Trying to decouple and re-use the frontend components from this repository. Is there a recommended way of viewing all the components with various states in a UI, say such as story book?

Any other recommendations for doing something like this?

**Comment by AdityaAnand1** [comment]
@okbel @lfades any thoughts?

**Comment by lfades** [comment]
We currently don't have anything set up for this. But I'm welcome to hear some ideas 👀
