### ISSUE TITLE
Improve README/setup instructions

### ISSUE THREAD

**Issue by AdityaAnand1** [vercel/commerce#202]
This is an incredibly knowledge dense repository, I'd love to learn more about it, not just to use it but also how to work my way through it, make modifications and contributions etc.

Ideas for better documentation:

1. Add a wiki
2. Explain folder structure
3. High level architectural decisions
4. Tech stack and libraries used
5. Extended contribution guidelines
6. Showcase agnostic UI modularity -> A way to view raw react components used in the projects independently 
7. Add FAQs

**Comment by lewis52ravens** [comment]
I would also add: setup instructions that do NOT require the use of Vercel.

**Comment by jerlam06** [comment]
1 year later and still 0 documentation.

**Comment by manovotny** [comment]
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: #966
