### ISSUE TITLE
multi-currency and multi-language are not working in production

### ISSUE THREAD

**Issue by eclipse3161** [vercel/commerce#204]
I can't seem to get NexSJ to work with multi-currency and multi-language are not working on production. For some reason nextJS is blocking calls to location API so multi-currency and multi-language. see video
https://www.dropbox.com/s/4jtn3juqh4vfluk/locale%20test.mkv?dl=0

any help is appreciated

**Comment by manovotny** [comment]
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: #966
