### ISSUE TITLE
Customer Group wise discount not available/working 

### ISSUE THREAD

**Issue by ahmadsyed** [vercel/commerce#207]
I am trying to show the original price(strikethrough) and discounted price both on the product page based on the customer groups. This feature is working fine at the bigcommerce provided storefront but in this storefront, I can only see one price. Am I missing anything here? Is this feature is not available? is there any way to achieve the same?

**Comment by Quinten-6wines** [comment]
Hi @ahmadsyed, I was struggling with the same problem. I found that the results when you request product info only provided: 

1. price 

The price set as the default price or sale price when you edit your product  the price set in the price list. 

They overwrite eachother. so: picelist price->salePrice-> defaultPrice.

2. salePrice

That is the price after all discounts (Set by Marketing->Promotions)

3. retailPrice

This can be set when you edit a product. Advanced Pricing->MSRP, This could be used to make the comparison to an original price.

So far, I did not find another way of doing this.

Unfortunately, the retailprice is not present on a 'CartItem' so it can not be used there.

**Comment by ahmadsyed** [comment]
Hi @Quinten-6wines 
Thanks for the feedbacks, Actually there are two ways (as I found till now) to show discount on the storefront, 
1- you can add different prices on each product as you mentioned (Most probably your last solution will work in this case)
2- You can add customer groups (like dealer/retail) to apply a default discount on products/product-category/all products etc based on the customer type. This is my case , And I have got it working by some changes(custom discount logic) in search.tsx page.
let me know if I got you right.

**Comment by manovotny** [comment]
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: #966
