### ISSUE TITLE
Provider: Strapi

### ISSUE THREAD

**Issue by prophet1996** [vercel/commerce#208]
[https://strapi.io/](https://strapi.io/)
I can contribute as well.
Regards and Thanks for this great project.

**Comment by Jbmanllr** [comment]
> https://strapi.io/
> I can contribute as well.
> Regards and Thanks for this great project.

Hey, any news about a Strapi connector?

**Comment by prophet1996** [comment]
i have picked it up. can expect a PR in a few weeks

**Comment by Jarrodsz** [comment]
Interesting any updates on this? Willing to help.

**Comment by manovotny** [comment]
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: #966

**Comment by prophet1996** [comment]
godspeed!
