### ISSUE TITLE
[BUG] - Total of the Cart not corresponds with the number of items

### ISSUE THREAD

**Issue by nsantos16** [vercel/commerce#21]
In the cart section, the number of items doesn't alter the total sum of the purchase.
<img width="466" alt="Screen Shot 2020-10-27 at 18 14 10" src="https://user-images.githubusercontent.com/9642510/97362794-49532b80-1880-11eb-97bd-b0d55a837531.png">

Awesome work guys, I can take this issue if you want 😄

**Comment by okbel** [comment]
LOL. haha yes! If you'd like this would be a good first pr (:

**Comment by buty619** [comment]
@okbel  @nsantos16  hehe nice job also i see that we have an issue whit the selection of the different options for example if you chose different color or size you always gonna see on the cart the first one selection, is that expected? or if you select a different characteristics of the same item it should be a different element on the cart list?
