### ISSUE TITLE
No mobile navigation

### ISSUE THREAD

**Issue by jeanmaried** [vercel/commerce#214]
Correct me if I'm wrong but there doesn't seem to be any mobile navigation. Is there a plan to add a hamburger/drawer menu?

**Comment by okbel** [comment]
Will add this to the kanban! Thanks!

**Comment by Blaze349** [comment]
Is there any update on this?

**Comment by ninecodes** [comment]
> Is there any update on this?

I implemented the mobile menu so we now have a mobile sidebar 🔥 [PR](https://github.com/vercel/commerce/pull/540)

**Comment by ViktorYermak** [comment]
This mobile menu, like mobile menus in general, is part of an outdated paradigm. A modern ui should be as visually simple as possible; no hamburgers, no drawers. Therefore, the mobile menu should be optional!
