### ISSUE TITLE
Get orders

### ISSUE THREAD

**Issue by jorgemasta** [vercel/commerce#215]
I'm working in the **BigCommerce** provider and we want to be able to fetch the orders (right the Orders page is empty)

I was looking #2 and #199 but I can't decide on a solution. Possible solutions:
1. Add the `orders` in the `useCustomer` hook
2. Create a new hook `useOrders`

What do you recommend? @okbel @lfades

**Comment by lfades** [comment]
A new hook for `useOrders`. Feel free to create a PR that adds the hook and a UI for it 👍 . We're currently working in making the demo very agnostic but new features are welcome.

**Comment by manovotny** [comment]
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: #966
