### ISSUE TITLE
Warning: Expected server HTML to contain a matching <span> in <span>.

### ISSUE THREAD

**Issue by OuthBack** [vercel/commerce#217]
![image](https://user-images.githubusercontent.com/65133825/110188898-1f94ad00-7dfc-11eb-8f20-81abeaa84947.png)
![image](https://user-images.githubusercontent.com/65133825/110188922-39ce8b00-7dfc-11eb-9c76-be1042ea8abe.png)

**Comment by Blaze349** [comment]
so how did you fix it

**Comment by OuthBack** [comment]
I didn't fix. I just reported

**Comment by manovotny** [comment]
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: #966
