### ISSUE TITLE
Color/Size Swatches should change displayed image

### ISSUE THREAD

**Issue by okbel** [vercel/commerce#22]

**Comment by nsantos16** [comment]
I can take this @okbel 😄

**Comment by tnishikata** [comment]
any updates?

**Comment by drugan** [comment]
I suggest add optional **variantId** property to the **ProductImage** type and then sort product.images based on the currently selected variant.

```
export type ProductImage = {
  url: string
  alt?: string
  variantId?: ProductVariant['id']
}
```

This might be done as a follow up on this issue: #508

**Comment by manovotny** [comment]
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: #966
