### ISSUE TITLE
Provider: Vendure

### ISSUE THREAD

**Issue by s1njar** [vercel/commerce#220]
E-commerce Provider: https://www.vendure.io

Regards and Thanks
for this great project.

**Comment by michaelbromley** [comment]
The PR got stale after a bunch of updates to the `agnostic` branch. I'm actually working on an updated PR right now!

**Comment by zohra-alt** [comment]
Hi! 
Is there a possibility to use Next.js Commerce with Vendure provider?

**Comment by s1njar** [comment]
Many thanks to @michaelbromley for working on vendure provider for nextjs commerce.

Running PR in https://github.com/vercel/commerce/pull/223

**Comment by Zwergal** [comment]
Would love to see vendure officially supported by nextjs commerce!

**Comment by agustif** [comment]
Can't wait to see this through
