### ISSUE TITLE
Unify the Node.js API for providers

### ISSUE THREAD

**Issue by lfades** [vercel/commerce#224]
Currently we have API methods that work under `/api/bigcommerce/*` that applies for all providers. The API used for the Node.js side of the commerce demo should be unified in a similar way of the agnostic provider we currently have for the UI hooks.

**Comment by Vandivier** [comment]
@lfades I support this but let's also think one step higher in abstraction: There are some API that go beyond providers and would be used for any back end. For example, `isAllowedMethod`.

ref: https://github.com/vercel/next.js/discussions/25599

As a side note, I find the higher-order hook implementation like `swell/.../use-signup.tsx` to be really hard to reason about. Just a note that 'unify the API' doesn't need to be done with a compositional approach. isAllowedMethod, for example, could simply be pasted in `framework/utils` and the other files could directly import it without composition.

**Comment by lfades** [comment]
@Vandivier `isAllowedMethod` was moved to be inside `commerce` so that's already the case, on the note about compositional approach that's a requirement because providers don't match each other's features, each provider adds what they can do
