### ISSUE TITLE
When going through the UI (to clone and deploy) bigcommerce has to be selected

### ISSUE THREAD

**Issue by FBosler** [vercel/commerce#226]
Would it make sense to include Shopify here also? I understand it's fairly new. But I think it's an amazing addition.

![image](https://user-images.githubusercontent.com/14016698/110771972-67cc2900-825b-11eb-95f9-1c9c9af5d720.png)

**Comment by devmiro** [comment]
Of course, I'm looking for shopify integration, it's best for Brazilian market.

**Comment by FBosler** [comment]
Is there any news on this?

**Comment by okbel** [comment]
Yeah, we're going to add them all. Can't give an ETA today, but definitelly.
