### ISSUE TITLE
[BUG] Error to remove last item from the cart

### ISSUE THREAD

**Issue by vczb** [vercel/commerce#228]
When I went to remove the last item from the cart this error happened

![cart-error](https://user-images.githubusercontent.com/51221635/110880083-d1305400-82bc-11eb-8367-ad2c6125d5c3.png)

*console:*

![cart-console-error](https://user-images.githubusercontent.com/51221635/110880257-1a80a380-82bd-11eb-8f71-f04b7dbf4f82.png)

I made a video showing the problem

https://www.loom.com/share/6f34f25137544dc4a95f178cf03faef7

**Comment by okbel** [comment]
Why is everything in uppercase? 🤔  https://demo.vercel.store/product/lightweight-jacket

**Comment by vczb** [comment]
Hello, I don't know why everything is in uppercase, but debugging on the console I found a property that when I remove it comes out of the uppercase

```
html {
    height: 100%;
    box-sizing: border-box;
    touch-action: manipulation;
    font-feature-settings: "case" 1,"rlig" 1,"calt" 0; //this property makes the uppercase in my browser
}
```
My Google Chrome is version 87.0.4280.141 64 bits

Linux Mint 20 Xfce 64 bits

About the cart item, I tried it on firefox too and the item doesn't come out

I'm going to make a short video to help

https://www.loom.com/share/9cc9de86c85b4196a933afe4ab38b361

Thank you very much for your time and attention

Sincerely 

:blush:

**Comment by ozan-altinbas-emakina** [comment]
It looks Vercel team is not responsive. Let's search for alternatives.

**Comment by Blaze349** [comment]
Do you know any other alternatives?

**Comment by okbel** [comment]
Looks like this has been solved already!
