### ISSUE TITLE
Cannot find name `AppProps`

### ISSUE THREAD

**Issue by gr-qft** [vercel/commerce#23]
I have a local copy and localhost is running but inside `_app.tsx` there's a couple of warnings about using `AppProps` (**Cannot find name `AppProps`**)

**Comment by gr-qft** [comment]
I'd really appreciate it if a comment is given. I still don't know what to do. Thanks!

**Comment by okbel** [comment]
This error looks rather odd because the only place we use AppProps is at _app.tsx with
import type { AppProps } from 'next/app'

I'd recommend start fresh, delete folder, again, pull env vars and run yarn. Let me know!! Sorry for closing that earlier

**Comment by gr-qft** [comment]
Ok thanks the info, I'm not too concerned about this warning at the moment, but at some point I'll try what you suggested and let you know.
