### ISSUE TITLE
THEMES!

### ISSUE THREAD

**Issue by okbel** [vercel/commerce#241]
We should discuss Theming. 🤔

**Comment by amesas** [comment]
Tailwind themes is enough for our scenario.

My idea for Next Commerce, is more a: create your own frontend-store, quick and easy with powerful tools.WooCommerce idea of: use our plugins / templates, where everything looks more or less the same, and customizing is not that easy. Cause then you have to track upstream plugins/templates.

**Comment by DanielHirunrusme** [comment]
In a Shopify scenario, this means everyone uses the Debut theme and changes the styles. This would be extremely limiting. 

For one example, the vercel/commerce theme is a 2 column layout with a slideshow. What if the user wants a single column and no slideshow? They could change @components/ProductView, but would run into upstream merge conflicts. Then, the more customization to the @components the more merge conflicts overtime right?

I'm approaching theming right now by creating a "theme/" folder in the root. Then I copy and paste the @component elements I want to customize into this folder. When I merge upstream, I can check if there are any updates to the original component that I want to frankenstein into my custom one. The advantage I see here (in the future) is being able to promote professional custom themes like Squarespace and Shopify. Not sure if this is the goal and/or the best method, but it would really invite a larger audience of users imo.

**Comment by BayCo** [comment]
Hey @DanielHirunrusme , i would like to use the same approach, could you kindly describe the exact steps
