### ISSUE TITLE
[BUG] Shopify | Checkout working localhost but not production

### ISSUE THREAD

**Issue by DanielHirunrusme** [vercel/commerce#245]
Test website: https://commerce-seven-tawny.vercel.app/

The website goes to Shopify hosted checkout fine on localhost. However, I'm getting a 404 on production (using Vercel).

I can see the shopify_checkoutUrl cookie being created with correct checkout url. Not sure why the next redirect is not triggering. Any thoughts here? @okbel / @cond0r ?

Thanks.

**Comment by cond0r** [comment]
@DanielHirunrusme  Looks like the provider is not set to shopify in commerce.config.json for that deployment. 
It works on mine on vercel, works on https://shopify.demo.vercel.store & on your other test site (https://shopify-test-danielhirunrusme.vercel.app).

**Comment by DanielHirunrusme** [comment]
@cond0r Thank you for the reply. Just checked and it looks like the commerce.config.json is set to Shopify on my end. =/

Just finished another build with commerce.config.json with wishlist false and Shopify provider on in every commerce.config.json.

Indeed strange it works on the demo store and test I created, but not this build. Trying to figure out why.

**Comment by cond0r** [comment]
@DanielHirunrusme yes, very strange... if you go directly to https://commerce-bl8j1r3uj-danielhirunrusme.vercel.app/api/bigcommerce/checkout the redirect to checkout works... but on your deployment, the rewrite  from /checkout to /api/bigcommerce/checkout doesn't happen.

**Comment by DanielHirunrusme** [comment]
@cond0r could it have something to do with next.config.js?

These are my setting right now. The below files should be up-to-date with the master branch

next.config.js

```javascript

const commerce = require('./commerce.config.json')
const withCommerceConfig = require('./framework/commerce/with-config')

const isBC = commerce.provider === 'bigcommerce'
const isShopify = commerce.provider === 'shopify'

module.exports = withCommerceConfig({
  commerce,
  i18n: {
    locales: ['en-US', 'es'],
    defaultLocale: 'en-US',
  },
  rewrites() {
    return [
      (isBC || isShopify) && {
        source: '/checkout',
        destination: '/api/bigcommerce/checkout',
      },
      // The logout is also an action so this route is not required, but it's also another way
      // you can allow a logout!
      isBC && {
        source: '/logout',
        destination: '/api/shopify/customers/logout?redirect_to=/',
      },
      // Rewrites for /search
      {
        source: '/search/designers/:name',
        destination: '/search',
      },
      {
        source: '/search/designers/:name/:category',
        destination: '/search',
      },
      {
        // This rewrite will also handle `/search/designers`
        source: '/search/:category',
        destination: '/search',
      },
    ].filter((x) => x)
  },
})

```
commerce.config.json
```javascript
{
  "provider": "shopify",
  "features": {
    "wishlist": false,
    "customCheckout": false
  }
}
```
with-config.js
```javascript
/**
 * This file is expected to be used in next.config.js only
 */

const merge = require('deepmerge')

const PROVIDERS = ['bigcommerce', 'shopify']

function getProviderName() {
  // TODO: OSOT.
  return process.env.BIGCOMMERCE_STOREFRONT_API_URL ? 'bigcommerce' : null
}

module.exports = (nextConfig = {}) => {
  const commerce = nextConfig.commerce || {}
  const name = commerce.provider || getProviderName()

  if (!name) {
    throw new Error(
      `The commerce provider is missing, please add a valid provider name or its environment variables`
    )
  }
  if (!PROVIDERS.includes(name)) {
    throw new Error(
      `The commerce provider "${name}" can't be found, please use one of "${PROVIDERS.join(
        ', '
      )}"`
    )
  }

  const commerceNextConfig = require(`../${name}/next.config`)
  const config = merge(commerceNextConfig, nextConfig)

  config.env = config.env || {}

  Object.entries(config.commerce.features).forEach(([k, v]) => {
    if (v) config.env[`COMMERCE_${k.toUpperCase()}_ENABLED`] = true
  })

  return config
}
```

**Comment by cond0r** [comment]
@DanielHirunrusme you have the vercel.json on root folder, where you config the rewrite... I think that overwrites the rewrites from next.config.js

put there { source: '/checkout', destination: '/api/bigcommerce/checkout'}

**Comment by DanielHirunrusme** [comment]
@cond0r wow, bingo! That was exactly the issue. All checks out fine now. Thank you very much for the help here, much appreciated!!! 

Excited to share the store in a few weeks if it helps. Will include Sanity + Algolia + ReCharge subscription + more Shopify-based customer profile actions (saw Sanity in the kanban).

**Comment by cond0r** [comment]
> @cond0r wow, bingo! That was exactly the issue. All checks out fine now. Thank you very much for the help here, much appreciated!!!
> 
> Excited to share the store in a few weeks if it helps. Will include Sanity + Algolia + ReCharge subscription + more Shopify-based customer profile actions (saw Sanity in the kanban).

Nice... by the way, you can remove vercel.json completly (you don't need for next.js on vercel)
https://vercel.com/docs/next.js/overview#no-configuration-required
