### ISSUE TITLE
latest changes not showing up from big-commerce data hooks

### ISSUE THREAD

**Issue by ahmadsyed** [vercel/commerce#247]
Hi,

I am having some bugs/feature-requests like (persist session on checkout, a bug in a logout, etc). I saw in the bigcommerce-data-hook repo, they have pushed a new release [store-front-data-hooks release](https://github.com/bigcommerce/storefront-data-hooks/releases/tag/v1.2.0) to fix those and more,  I need those changes in my project, will this repo be updated any time soon?  How may I get the latest changes from [storefront-data-hooks repo](https://github.com/bigcommerce/storefront-data-hooks)? Am I missing anything obvious here?

**Comment by okbel** [comment]
Hello @ahmadsyed! We have locked the version for BigCommerce here, but if those hooks are more up-to-date feel free to pull those into a new provider under /framework/`new-bigcommerce` and use those instead. 

We haven't had the chance to test them out yet but we could definitely add them as a dependency, and remove the ones we have here. Let us know!

**Comment by ahmadsyed** [comment]
Hi @okbel , Thanks for the update, As a workaround, I have replaced the hooks folder from that repo. It would also be very helpful if it can be added as dependencies, as A few essential changes like  SSO,  session management in the checkout, these types of features have been added in the official repo.
