### ISSUE TITLE
Custom provider not being recorgnised

### ISSUE THREAD

**Issue by SaidiAli** [vercel/commerce#248]
Am trying to make my own provider but when I make all the necessary changes according to  this https://github.com/vercel/commerce#how-to-change-providers, it is still not recognised.
I get this error: `The commerce provider "mycommerce" can't be found, please use one of "bigcommerce, shopify"`
How can I continue?

**Comment by cond0r** [comment]
> Am trying to make my own provider but when I make all the necessary changes according to this https://github.com/vercel/commerce#how-to-change-providers, it is still not recognised.
> I get this error: `The commerce provider "mycommerce" can't be found, please use one of "bigcommerce, shopify"`
> How can I continue?

open framework/commerce/with-config.js and add your provider there, like: 
`const PROVIDERS = ['bigcommerce', 'shopify', 'mycommerce']`

**Comment by SaidiAli** [comment]
Thank you so much @cond0r .
I feel like this is missing in the README so I have created a [pull request](https://github.com/vercel/commerce/pull/250) for it. Hopefully it will considered.
