### ISSUE TITLE
Does this work with Shopify?

### ISSUE THREAD

**Issue by nicksarafa** [vercel/commerce#25]
If so, what's the setup process? I only see BigCommerce mentioned in the documentation

Thanks! And congrats on the push!

**Comment by a-eid** [comment]
it seems that this project was done in collaboration with BigCommerce, but I'd like to see if there are other options other than using BigCommerce.

**Comment by agcty** [comment]
I'm also really curious when the shopify integration will land, right now it seems that only bigcommerce is supported but other integrations will follow soon (there's some really small text on next.js/commerce saying other integrations will follow soon).

**Comment by maartenjongerius** [comment]
I'm interested in this as well, and willing to contribute. Our company is planning on using this for Shopify projects as soon as it's possible. Who do I contact to contribute on this?

**Comment by nicksarafa** [comment]
@maartenjongerius yes, we would also be open to contributing to a Shopify fork

**Comment by okbel** [comment]
https://github.com/vercel/commerce/issues/2

Absolutely. We're currently working on it. Stay tuned for that PR.
