### ISSUE TITLE
Add cloning for Shopify demo

### ISSUE THREAD

**Issue by nikushx** [vercel/commerce#253]
Hey Vercel Team, first off thank you for releasing the Shopify provider for Next Commerce, we've been really looking forward to this!

I noticed that you cannot clone into Vercel with the Shopify demo, you are forced to install BigCommerce. Is the demo for Shopify available somewhere that lets us clone it into Vercel?

It would be great to link it up to a development store and have a good starting point.

Thanks!

**Comment by ahrenpradhan** [comment]
well you can use this [shopify demo](https://shopify.demo.vercel.store/)

but I'd recommend to fork the project and deploy on vercel yourself
happy coding

**Comment by nikushx** [comment]
@ahrenpradhan The crux of my issue is that I do not think the demo you provided has its own repo so that we can clone the code..

**Comment by nikushx** [comment]
@ahrenpradhan yes, but to clone the repo you still need to install BigCommerce for some reason. I am also not sure about using the shopify branch as it is hundreds of commits ahead of master, so I am afraid it is not ready for production use

**Comment by ahrenpradhan** [comment]
You are right
And we are supposed to use the main master where we change the `@framework path` to choose Shopify framework folder
And after that remove the once you don't need and remove the package one after another, check if anything breaks

See if this works
If we only have to ignore some files and folders then I can create a PR for build script for any of the existing framework

But it all depends if this even works.

**Comment by nikushx** [comment]
@ahrenpradhan Good to hear. I will be exploring this in a week or two from now if Vercel team has no further input. It is possible they are expecting us to do what you have mentioned, retrofit their BC example for Shopify as it is a easy switch thanks to the agnostic adapter.

**Comment by okbel** [comment]
Hello @nikushx ! Thank you for the kind words!

The integration for Vercel is pretty close to be done, we need an approval on Shopify's Marketplace because this is an official public app. So, this will land hopefully soon!

**Comment by nikushx** [comment]
@okbel Are you able to provide any insight as to what the App will do? As far as I can see, Next Commerce can pull from all the data it needs via Storefront API. What will the App allow us to do additionally? Trying to see how this all fits into using Next.js to host a Shopify frontend.
