### ISSUE TITLE
Question about frontend structure 

### ISSUE THREAD

**Issue by seloner** [vercel/commerce#254]
Hello I am following this project from the beginning . Now that the project supports more data providers like shopify how would this affect the frontend code ? For example for one provider the product type maybe is different compared to the default product . How is possible to handle specific provider type differences ? Is the solution having a single trust of truth?

**Comment by seloner** [comment]
Yes but for example I want to display it for shopify but not for big commerce . I know that you can just check if the property exists and then display something if exists but I dont feel that is the best solution to handle model differences in the frontend

**Comment by okbel** [comment]
Indeed! 

**Provider** brings **data** -> Helpers **normalize** it -> **UI renders**.

If you want to support something specific for only **one provider** just use env vars in the frontend to show stuff on and off, make sure that you ignore certain files if not every provider should use them! Exactly like we do for **Wishlist** Bigcommerce Supports it, Shopify doesn't. We only build what's necesary based on the provider.

**Comment by okbel** [comment]
I'll recomend you to check how we build Wishlist utilities and how we ignore them through the code to build for a specific provider and build more functionality.
