### ISSUE TITLE
Support for OAuth

### ISSUE THREAD

**Issue by loan-laux** [vercel/commerce#257]
@CristianCucunuba, @janus-reith and I are building a provider for Reaction Commerce (see issue #170). One caveat of RC compared to Shopify and BigCommerce is that it requires users to sign in through an OAuth flow. There's currently no built-in support for OAuth on Next Commerce.

A few things need to be taken into account to pre-wire Next Commerce for OAuth (in case individual providers require it):

- Add a boolean config flag (`oauth: true` for example) which, when set by a provider, would make the `LoginView` display a simple "Login" button instead of a username/password form.
- This "Login" button with no username/password form would still call the `@framework/auth/use-login` hook. There, it would be up to the provider's developers to decide how to handle the OAuth flow.

Aside from these relatively minor UI considerations, we need to chose a library to actually handle the OAuth redirection, callback etc. We prefer `next-auth` as it's more of a "Next-native" solution than `passport`... But the choice is not just ours to make.

If we add `next-auth` to the project's dependencies as part of the Reaction provider PR, `next-auth` will be part of the dependencies whether users choose to use the Reaction provider or not. Developers who will work on their own provider implementations and who might need OAuth support will have `next-auth` pre-installed and will likely have to use it too as I assume we don't want to have a bunch of authentication libraries living under the same roof.

So here goes my question: if we're implementing OAuth support, do @okbel and the team agree with our choice of `next-auth`? Or should we use something else? Should we pre-wire anything and build an API to make it easier for provider developers to use `next-auth`? Eager to hear what the community thinks too.

At a higher level, I think this prompts for a discussion about provider-specific `package.json` and dependency support, as well as a way to add API routes from within a provider without touching the `pages/` directory.

**Comment by okbel** [comment]
Hello @loan-laux !

There's no support for integrations to select provider here, because that part is being handled by Vercel (or the support system deploying a Next.js Commerce). We support the OAuth dance there when you deploy a Next.js Commerce. This storefront should not ship with any additional code, more than the storefront configuration needed.

But to your point, if you'd like to work on an integration for Vercel, let me know!

**Comment by loan-laux** [comment]
Thanks for the response @okbel! I'm afraid there might be some confusion here... I was referring to letting end-users (customers) log in with an OAuth flow.

Reaction Commerce does not have a GraphQL mutation or REST route that takes a username and a password. Instead, to authenticate users, the storefront would have to support OAuth, hence my initial writeup.

Now, thanks to your comment, I just discovered that there is this OAuth flow (currently just for BigCommerce?) to authenticate the merchant while deploying on Vercel. Reaction Commerce only needs a shop ID for a client to query the catalog, categories etc, so we won't need anything like this.

Sorry for not making that initial post clear enough. Any thoughts on how to approach OAuth for customers?

**Comment by adithyaakrishna** [comment]
> Hello @loan-laux !
> 
> There's no support for integrations to select provider here, because that part is being handled by Vercel (or the support system deploying a Next.js Commerce). We support the OAuth dance there when you deploy a Next.js Commerce. This storefront should not ship with any additional code, more than the storefront configuration needed.
> 
> But to your point, if you'd like to work on an integration for Vercel, let me know!

Hey @okbel 
If its okay, I would really love to work on the Integration for Vercel 👀
But I'm still a learner though, and this would be a great opportunity

**Comment by loan-laux** [comment]
@okbel sorry to insist, I imagine you're quite busy, but do you have any thoughts on approaching this?

**Comment by loan-laux** [comment]
>If its okay, I would really love to work on the Integration for Vercel 👀

@adithyaakrishna for Reaction specifically? As far as I know, there's no need for OAuth authentication at the merchant level.

**Comment by loan-laux** [comment]
It turns out that someone at Reaction has published a WIP implementation of authentication over GraphQL. This means we won't need OAuth support for Reaction Commerce. I'm still leaving this issue open though, as it only a matter of time before someone wants to build a provider for a commerce API that requires OAuth.

**Comment by adithyaakrishna** [comment]
> It turns out that someone at Reaction has published a WIP implementation of authentication over GraphQL. This means we won't need OAuth support for Reaction Commerce. I'm still leaving this issue open though, as it only a matter of time before someone wants to build a provider for a commerce API that requires OAuth.

Okay 👀

Also Yeah, I had thought that, but Ig it's not needed anymore for Reaction :(
Would love to work on some starter issues at first and then move to tougher ones 👨‍🔧
@loan-laux If it's okay, do lmk some I would try to work on them

**Comment by loan-laux** [comment]
> Would love to work on some starter issues at first and then move to tougher ones 👨‍🔧
> 
> @loan-laux If it's okay, do lmk some I would try to work on them 

If you mean to get involved in the development of Reaction, then I would suggest looking at issues on their GitHub repos and chatting with the community on our Gitter channel.

Pretty sure it's off-topic on this issue though, so let's keep it clean and focused on OAuth support for customers.

**Comment by manovotny** [comment]
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: #966
