### ISSUE TITLE
When will the shopify provider be available on vercel.com ?

### ISSUE THREAD

**Issue by achadee** [vercel/commerce#265]
Hi there,

Im trying to install the shopify provider on Vercel but I get the following screen:

![Screen Shot 2021-04-09 at 12 08 00 pm](https://user-images.githubusercontent.com/5952918/114118484-3d3dc080-992c-11eb-8d8f-a1289d50f8aa.png)

Is there a way I can do it without going through a wizard? I can't find the docs.

**Comment by DanielHirunrusme** [comment]
@achadee See https://github.com/vercel/commerce/issues/253

**Comment by FBosler** [comment]
@achadee  also see (#226)[https://github.com/vercel/commerce/issues/226]
