### ISSUE TITLE
Is shopify lite enough?

### ISSUE THREAD

**Issue by THPubs** [vercel/commerce#266]
Shopify have a lite plan for just 9 USD ([https://www.shopify.com/lite](https://www.shopify.com/lite)) which only offers the basics. Will this be enough for NextJS Commerce platform?

**Comment by cond0r** [comment]
@THPubs Yes, it works. You have the order & product management on Shopify Dashboard with the Lite plan, and you have access to Storefront API that NextJS Commerce uses.

**Comment by THPubs** [comment]
Awesome! Thanks @cond0r !
