### ISSUE TITLE
How does getStaticPaths handle new products / collections / blogs being added

### ISSUE THREAD

**Issue by achadee** [vercel/commerce#268]
We have a lot of products/collections and are adding close to 10/15 a week.

I notice that to load the paths you use `getStaticPaths`

Does this mean that we need to redeploy the app every time a new product/collection/blog is added? so it can load paths etc

If this is the case would the best solution be to build some sort of CRON job on a lambda to rebuild the client on its current commit? Is this documented/tutorialised anywhere on vercel?

Thanks in advance

**Comment by cond0r** [comment]
@achadee If you host your site on Vercel, you benefit from [Incremental Static Regeneration](https://nextjs.org/docs/basic-features/data-fetching#incremental-static-regeneration). When you post a new product it will regenerate homepage and product pages while users visit your site.  Also pages like this https://demo.vercel.store/search?q=clothes grabs latest data with [SWR](https://swr.vercel.app/#overview). If there is a new product and user clicks on it, is being generated on the fly, you don't need to rebuild.

**Comment by achadee** [comment]
Thats actually so good! Im so relieved that I don't need to code that!

**Comment by mxdi9i7** [comment]
@cond0r What are some in-code solutions for sites not deployed with vercel?
