### ISSUE TITLE
Add more platforms and add PWA support

### ISSUE THREAD

**Issue by ninecodes** [vercel/commerce#271]
Extend the setup to have also an example for:

- Magento
- Shopware (Here's an [example](https://demo.storefrontcloud.io) of the shopware vue storefront)

Also would be great to have PWA support
Here's also an [example](https://shopware-pwa.storefrontcloud.io) by those same guys who made the Vue storefront how they implemented a pwa version for it too.

Love the whole next commerce project and I believe it can be extended so that people can create for the upper two commerce platforms which are booming in the DACH region (Germany, Austria, Switzerland)

**Comment by manovotny** [comment]
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: #966
