### ISSUE TITLE
please activate Discussions for this repo

### ISSUE THREAD

**Issue by mariusa** [vercel/commerce#276]
Hi, I have a question and README doesn't say where to ask.

Would you please activate Discussions for this repo?

Q: I see images hardcode width/height in 
https://github.com/vercel/commerce/blob/d838f34c73dc1fb6a44965750024d2cb934907be/components/product/ProductCard/ProductCard.tsx#L39
shouldn't these be in (S)CSS? And maybe responsive per device? Can't be the same on phone & monitor.

**Comment by okbel** [comment]
Done! Thank you for suggesting it!
