### ISSUE TITLE
Project fails to build

### ISSUE THREAD

**Issue by kimdichi** [vercel/commerce#278]
I am trying to set up a local dev environment for customizing the base Shopify theme but I am running into errors which are not really helpful. I followed the the instructions to setup the environment referenced in Readme of project.

-  Forked the repository to my GitHub account and cloned to my laptop.
-  Created a new branch git checkout -b MY_BRANCH_NAME
-  Installed yarn: npm install -g yarn
- Duplicated .env.template and rename it to .env.local
-  Added Shopify store values to .env.local
-  Ran yarn dev to build and watch for code changes

Upon running the dev server, I got this error.

![now](https://user-images.githubusercontent.com/82526829/114738275-40d4ab80-9d61-11eb-837f-743e0c7ffa63.png)

Unfortunately, the errors on console are also not very helpful. 

![console_error](https://user-images.githubusercontent.com/82526829/114738719-aaed5080-9d61-11eb-9caf-b83b3cb4edfc.png)

I am using Ubuntu 20.04 with node v14.16.1 if that helps. 

Any ideas what is happening here?

**Comment by cond0r** [comment]
@kimdichi it's a DNS Resolver problem, it cannot resolve Shopify's domain so it cannot communicate with it:

https://askubuntu.com/questions/1319815/having-dns-issue-with-ubuntu-20-04
https://askubuntu.com/questions/1040595/dns-at-systemds-127-0-0-53-is-ignoring-some-lookups
https://www.linuxbabe.com/ubuntu/set-up-local-dns-resolver-ubuntu-20-04-bind9.

**Comment by kimdichi** [comment]
That is strange, I am using it on my local machine and I am able to query Shopify's API on my machine without any problem. If were a DNS problem, I wouldn't be able to do it.

**Comment by cond0r** [comment]
@kimdichi yes it is strange, it has something to do with your machine. And this is what i got from the error above, and a quick search (where I found similar issues with the exact error for other things like MongoDB Atlas connection on Ubuntu 20.04). 

You was able to query with a Node.js app running on localhost ?

Also what errors or logs appear in terminal window, after you typed 'yarn dev'.

**Comment by kimdichi** [comment]
@cond0r 

I am using a Insomnia to query Shopify's API. 

I am connecting with a test account on Shopify so the credentials are not critical, in case it helps you see the problem. These are the credentials. 

 X-Shopify-Storefront-Access-Token : b8806f6825e64c55efe4ebbbe075bc28
Storefront_url:      https://test-bench-1.myshopify.com/api/2021-01/graphql.json

**Comment by cond0r** [comment]
@kimdichi if you put at NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN the url above that's the issue and that's why it could not be resolved

In .env.local put this: 
NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN=test-bench-1.myshopify.com
NEXT_PUBLIC_SHOPIFY_STOREFRONT_ACCESS_TOKEN=b8806f6825e64c55efe4ebbbe075bc28

**Comment by kimdichi** [comment]
@cond0r 

Thanks! It is working. 

I think it would be a good idea to document it. The documentation is practically non existent which can trip up people.
