### ISSUE TITLE
Quesiton about integrated providers

### ISSUE THREAD

**Issue by FlushBG** [vercel/commerce#279]
Hello, 
If I decide to use Shopify or BigCommerce as the backend provider, how flexible could this storefront be? If I remember correctly, Shopify doesn't let you have your own checkout page, but needs you to redirect to theirs.
And BigCommerce doesn't let you have a faceted search ( by size, color, etc... ). 
Are these limitations still there and are these features available in Vercel Commerce?

**Comment by kimdichi** [comment]
I was wondering about that myself, with starters like this project. The role of backend is diminished to a CMS which is only required at build time (I am assuming this is how it is working since there I couldn't find any documentation). 

How can they even enforce restriction of any customization on front end when they don't control it?

**Comment by FlushBG** [comment]
They don't expose some endpoints publically. If I go and try create a storefront from scratch, I will probably not be able to use faceted search in BigCommerce. But in some cases of partnership, those endpoints are exposed and I am wondering if BigCommerce lets Vercel use the entire functionality

**Comment by okbel** [comment]
Hello @FlushBG ! 

We don't have support for Custom Checkout yet, but it's under development -- We have all the designs and components ready. We need to make the api for it flexible before standarizing it.
So, the idea is that you can add it yourself (components and everything) by forking the starter. You'll need to create a new provider `shopify_stripe`, for example to unlock more capabilities on the checkout if needed.

**Comment by FlushBG** [comment]
Thnks @okbel !
Thanks for the reply! What about BigCommerce, do they allow a custom checkout and using the faceted search?

**Comment by okbel** [comment]
Last time I check, they didn't support custom checkout! But, don't take my word for it: check the docs and each sites. They are usually super updated :)
