### ISSUE TITLE
Where does the shopify/shema.d.ts come from?

### ISSUE THREAD

**Issue by FBosler** [vercel/commerce#284]
Love the repo! I'd like to potentially use the "Shopify GraphQL admin API" instead of the Storefront API though, for this I'd have to create a new schema potentially. Could you elaborate where the current one comes from/how it is generated?

**Comment by cond0r** [comment]
@FBosler schemas are created using [graphql-codegen](https://github.com/dotansimha/graphql-code-generator). created a #285 to add the command used to generate that.

**Comment by muhammad-saleh** [comment]
@cond0r will #285 cover generating definitions as well? or will that be in separate PR?

**Comment by jenniferhail** [comment]
Hi @FBosler. Did you ever switch to the Admin API? I'm currently trying to figure out how to build an orders page that shows past and current orders for a logged in customer, and I'm thinking I might be limited by the Storefront API.

**Comment by FBosler** [comment]
@jenniferhail For some parts, you kinda have to. For orders, you don't have to necessarily though. It's pretty straightforward to make this accessible to logged-in only users. (as you can use a storefront query to retrieve customer access token). 

**1. First get the customer access token like so:**
<img width="969" alt="image" src="https://user-images.githubusercontent.com/14016698/184582401-466e41c1-a797-43d5-9225-c700d2a5e385.png">

**2. Use the token to retrieve customer information (including orders) like so:**
<img width="884" alt="image" src="https://user-images.githubusercontent.com/14016698/184583135-3cb69954-ddad-49ad-a6e4-e9614a3aa7d8.png">

You can also play around with the explorer to see what's possible and what isn't. See [here](https://shopify.dev/custom-storefronts/tools/graphiql-storefront-api).

**Comment by jenniferhail** [comment]
@FBosler Your reply was just what I needed to get unstuck. Thank you!!

For some reason, the Shopify GraphiQL App doesn't match up with the explorer link you sent, so I was querying for a few fields that didn't actually exist.

**Comment by manovotny** [comment]
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: #966
