### ISSUE TITLE
Shopify Customer Login

### ISSUE THREAD

**Issue by kenobivan** [vercel/commerce#286]
Hello!

I successfully setup Next Commerce with Shopify locally by setting the correct provider details in an .env.local file.
For my project I'd like to use the customer login/register functionalities?

How can I activate this?
Is it part of the features in the commerce.config.json?
Is there any documentation about the features?

Many thanks!

**Comment by kenobivan** [comment]
Sorry my fault...
I simply forgot to activate user accounts in Settings -> Checkout.
But maybe someone stumbles over the same issue

**Comment by GodwinEbikwo** [comment]
Hey @kenobivan have issues with customer login functionality. Okay where can I activate i from. Thanks in advance
