### ISSUE TITLE
[ISSUE] can't add products to cart

### ISSUE THREAD

**Issue by buty619** [vercel/commerce#29]
## Description

* On my local all actions related to mybigcommerce (for example add to cart) always return Error `[BigcommerceApiError]: Big Commerce API error (404)`, maybe im missing some configuration?

## Img

<img width="1245" alt="Screen Shot 2020-10-27 at 10 08 09 PM" src="https://user-images.githubusercontent.com/36422189/97386017-f047bf80-18a0-11eb-9fb3-24372666904c.png">

**Comment by enarankhuu** [comment]
Hey, I wanna show your .env.local file. I dunno which env file to use!!

**Comment by okbel** [comment]
.env.template was added! Keep in mind that this is tightly coupled with BigCommerce so you'll need env vars to run it locally.

**Comment by buty619** [comment]
hello @okbel  thanks for all you help but im still having same issue i already create the .ev.local file whit the key get from versel, there is something else im missing? maybe local env should be different to the once generate on versel?

<img width="1263" alt="Screen Shot 2020-10-28 at 5 13 42 PM" src="https://user-images.githubusercontent.com/36422189/97502588-6a2f8580-1941-11eb-8488-463e48147065.png">

<img width="339" alt="Screen Shot 2020-10-28 at 5 14 17 PM" src="https://user-images.githubusercontent.com/36422189/97502598-6ef43980-1941-11eb-9f6e-1ff45dca704f.png">

**Comment by Abdulsalam0001** [comment]
I am  having the same issue...

**Comment by Julianwan** [comment]
Has anyone found a solve for this? Just curious... I'm having a similar set of issues
