### ISSUE TITLE
[next/image] (1) Saving image original filename (2) Shopify CDN configuration (3) Custom loader solution

### ISSUE THREAD

**Issue by DanielHirunrusme** [vercel/commerce#292]
**( 1 ) Saving image original filename issue**
On demo store, all products images save as _image.png_. I tried searching next/image docs but was unable to find a solution here. Basically, I believe images should be able to save as original filename for archival and shareable purposes. You can see I made a workaround with a next/image custom loader on my store [here](https://shop.spikeartmagazine.com/ ). Customer loader code below.

**( 2 ) Shopify CDN configuration**
On demo store, Shopify images are loaded in like:
`https://shopify.demo.vercel.store/_next/image?url=https://cdn.shopify.com/s/files/1/0434/0285/4564/products/image.png?v=1617053250&w=3840&q=85`

However, it doesn't look like it's working correctly. See this for example https://shopify.demo.vercel.store/product/black-shoes. If you right click the image, you get the 3840 size on a tablet which is huge. Expecting it to be either 1200 or 1920 based on next/image [device sizes](https://nextjs.org/docs/basic-features/image-optimization#device-sizes). It seems that images are loading much larger everywhere, or the 3840 size.

**( 3 ) Custom loader solution**
After building my own customer loader for Shopify, it seems to solve both saving image as original filename and loading in images at the correct size. [Store URL](https://shop.spikeartmagazine.com/ )

See customer loader here:

```javascript
const myLoader = ({ src, width, quality }) => {
  let newSrc = src
    .split('.jpg')
    .join(`_${width}x@2x.progressive.jpg`)
  return `${newSrc}`
}
```

Not sure if I'm misunderstanding something. Appreciate any insight here.

**Comment by DanielHirunrusme** [comment]
Confirmed this is still not working well with Shopify CDN. It's loading the largest size image. 

As a quick solution example, this works better:

```javascript
const myLoader = ({ src, width, quality }) => {
  let newSrc = src
    .split('.jpg')
    .join(`_${width}x@2x.progressive.jpg?w=${width}&q=${quality || 75}`)
  newSrc = newSrc
    .split('.png')
    .join(`_${width}x@2x.png?format=jpg&w=${width}&q=${quality || 75}`)
  return `${newSrc}`
}

<Image
                    loader={myLoader}
                    src={image.url!}
                    alt={image.alt || 'Product Image'}
                    width={600}
                    height={750}
                    quality="85"
                    layout="responsive"
                  />
```

**Comment by bastienrobert** [comment]
Shopify CDN has npw some params you can pass to define the width/height & crop/crop padding.

Read more: https://cdn.shopify.com/

**Comment by manovotny** [comment]
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: #966
