### ISSUE TITLE
Static export, /checkout gives 404

### ISSUE THREAD

**Issue by muhammad-saleh** [vercel/commerce#295]
Hi!
I'm trying to statically export this project using `next export`, I'm currently using Shopify as a provider
Currently the biggest issue that I have is that checkout doesn't work, The `Proceed to checkout` CTA points to `/checkout` which doesn't work and gives 404. Any help with this? (it works with yarn dev and yarn start)

I have set the provider to Shopify in commerce.config.json
```json
{
  "provider": "shopify",
  "features": {
    "wishlist": false,
    "customCheckout": false
  }
}
```
Is there a way to get this to work in a static export?

Thanks!

**Comment by cond0r** [comment]
@muhammad-saleh  open CartSidebarView.tsx  add: `import Cookies from 'js-cookie'` change current checkout buton to:
`<Button  href={Cookies.get('shopify_checkoutUrl')}  Component="a" width="100%"> Proceed to Checkout</Button>`

**Comment by muhammad-saleh** [comment]
@cond0r Works perfectly! Thank you.
