### ISSUE TITLE
Content Security Policy Failure: The page’s settings blocked the loading of a resource at inline (“script-src”).

### ISSUE THREAD

**Issue by Crelloc** [vercel/commerce#296]
There's a script tag that's dynamically embedded in <head> that causes my CSP to fail. I need to figure out how to add a nonce value to this tag.
 
Can anybody find where the following script tag is generated in the code?:

<script>!function(){try {var e=localStorage.getItem('theme');if(!e)return localStorage.setItem('theme','light'), void document.documentElement.setAttribute('data-theme', 'light');if("system"===e){var t="(prefers-color-scheme: dark)",m=window.matchMedia(t);m.media!==t||m.matches?document.documentElement.setAttribute('data-theme', 'dark'):document.documentElement.setAttribute('data-theme', 'light')}else document.documentElement.setAttribute('data-theme', e)}catch(e){}}()</script>

**Comment by johnbwu** [comment]
@Crelloc did you ever figure this one out? Im trying to do the same thing with BigCommerce embedded checkout

**Comment by Crelloc** [comment]
Because the code isn't compliant with CSP, I believe the only way to fix
this is to do a "static html export (
https://nextjs.org/docs/advanced-features/static-html-export)." Then have
server eject nonce value for each script tag (
https://karlstoney.com/2017/03/26/secure-your-site-with-nginx/).  However,
static html export will pose a problem with this project because of dynamic
routes for the product pages. "If you have dynamic routes, instead of using
getStaticPaths you'll need to configure the exportPathMap parameter in your
next.config.js file to let the exporter know which HTML files it should
output.(https://nextjs.org/docs/advanced-features/static-html-export). "

There may be a way to still do it without having to do a static html export
but you may have to modify (remove or comment out) the code where it
injects the script tag.  A few months ago, i was debugging this issue while
following along with the following discussions:
https://github.com/vercel/next.js/discussions/18451?sort=old

To avoid debugging, the easiest thing to do (but more of a headache) is to
just start this project over from scratch and follow the CSP policy.

Good Luck.

**Comment by manovotny** [comment]
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: #966
