### ISSUE TITLE
[BUG] - Wishlist Button not working in the grid

### ISSUE THREAD

**Issue by okbel** [vercel/commerce#3]

**Comment by vindecodex** [comment]
@okbel hello, i would like to grab this issue, but can i ask if how to get `.env.local variables` ?

**Comment by orivelton** [comment]
@vindecodex  you can start a project and pull de .env.local variable using the vercel CLI, just run  `vercel env pull .env.local` https://vercel.com/blog/environment-variables-ui

**Comment by vindecodex** [comment]
@okbel i already run the project in my local machine can you help me explain what was the bug is :bow:
