### ISSUE TITLE
Not able to add products to cart

### ISSUE THREAD

**Issue by danielbixel** [vercel/commerce#301]
Hello world. 
super psyched about this repo. But unfortunately I ran into some issues I couldn't figure out the entire day.

Neither on a on vercel hosted project with a bigcommerce connection, neither on local host connected to shopify I am able to add products to the basket. 

On local host with shopify as a provider I am getting
My headers go through with 200 and a nice looking query as a payload. But the 2 responses I am getting when trying to add an article to the basket look like this:

{message: "Variable $customerAccessToken of type String! was provided invalid value",…}
extensions: {value: null, problems: [{path: [], explanation: "Expected value to not be null"}]}
locations: [{line: 2, column: 21}]
message: "Variable $customerAccessToken of type String! was provided invalid value"

and

{data: {node: null}}
data: {node: null}
node: null

On the vercel hostes version with bigcommerce provider I am getting a 500 with:
{"data":null,"errors":[{"message":"An unexpected error ocurred with the Bigcommerce API"}]}

By now I am clueless. Hope someone has any good Ideas! :)
Thanks

**Comment by danielbixel** [comment]
By now I got it working on the deployed version. I commented out the .env.local file in the gitignore.
But when I am running the same app on my localhost i am still not able to add products to the basket and get this return in the response header: 

{data: {node: null}}
data: {node: null}
node: null

Thanks for your help!

**Comment by danielbixel** [comment]
wow .. turned out it just didnt work in chrome, but also only when running localhost. The deployed app was working great.
Safari worked great local and deployed.

**Comment by rickyPanzer** [comment]
same with shopify ^^, why do we think that is? 

Does this app have PWA features built in? I've had trouble with PWAs caching things in the past

**Comment by okbel** [comment]
Looks like this has been fixed already!
