### ISSUE TITLE
[BUG] - BigCommerce provider doesn't support products with more than 10 variants

### ISSUE THREAD

**Issue by lewis52ravens** [vercel/commerce#303]
I can't speak to whether this issue exists with Shopify, but I know that when using BigCommerce as a provider the following issue exists on products that have more than 10 variants.

**Issue:**
The different option Swatches will still appear on the product page, but only the first 10 variants will work. Meaning that if you select options corresponding to variant 12 and then click "Add to cart", the first (default) variant will be added.

**Cause:**
The GraphQL query to the BigCommerce API requests `variants`, but doesn't specify a value for `first`, which means it defaults to 10 and only returns the first 10 variants (see [framework/bigcommerce/product/get-product.ts, line 20](https://github.com/vercel/commerce/blob/a4f56d15496c837a73d83281cb0ff55fd95520e1/framework/bigcommerce/product/get-product.ts#L20)).

**Possible Solutions:**
A quick solution would to be change line 20 of the BigCommerce get-product file to `variants(first: 100)` which would support up to a hundred variants. However that isn't a very good solution, and still puts a limit on the number of supported variables.
I think a better solution would be to use pagination to continue querying the BigCommerce API until all the variants have been received. This would require separating the logic of the [getProduct](https://github.com/vercel/commerce/blob/a4f56d15496c837a73d83281cb0ff55fd95520e1/framework/bigcommerce/product/get-product.ts#L88) function so that it makes one query for the product info without variant information, then continuously queries for the variant info until it has all the variants, before finally combining the variant info back together with the rest of the product.

**Comment by Florian-crg** [comment]
I get the same problem. Regarding my logs it comes from `/components/product/helpers.ts`
