### ISSUE TITLE
Best strategy for implementing Checkout Notes / Custom Attributes

### ISSUE THREAD

**Issue by achadee** [vercel/commerce#312]
Hey team,

I noticed you don't have hooks available for notes / custom attributes. Is this the best way to go about it? I've never written a hook from scratch before - but it can't be too hard, right?

Thanks in advance - ill keep posting here with updates to potentially help others facing the same issue

**Comment by joshbedo** [comment]
Wondering the same thing trying to add order notes or use order metafields on Shopify

**Comment by MM-Othman** [comment]
having the same issue here too

**Comment by manovotny** [comment]
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: #966
