### ISSUE TITLE
Improve lighthouse score / page speed insights scores 

### ISSUE THREAD

**Issue by chandan-reddy-k** [vercel/commerce#32]
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdemo.vercel.store%2F&tab=mobile

The scores are not up to the mark. Is everyone seeing the same score of around 50-60? 😅

![Screenshot 2020-10-28 at 10 40 39 AM](https://user-images.githubusercontent.com/43699825/97395108-2ec59480-190a-11eb-907c-c19f409b075b.png)
![Screenshot 2020-10-28 at 10 40 48 AM](https://user-images.githubusercontent.com/43699825/97395100-2a00e080-190a-11eb-94f1-9b705f82771e.png)

**Comment by matigda** [comment]
Right now I'm getting around 78 on mobile. Yesterday I got higher results.

**Comment by leerob** [comment]
Let's check Next.js Analytics for a more true test of speed (not synthetic scores) 🔥

**Comment by leerob** [comment]
![image](https://user-images.githubusercontent.com/9113740/97445347-29148280-18fb-11eb-8ba9-6e874c454d58.png)
🎉🎉🎉

**Comment by chandan-reddy-k** [comment]
@leerob sorry I’m confused now. Isn’t page speed insights the correct measure for web vitals? 

I know the lighthouse test in chrome dev tools differs from device to device but https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdemo.vercel.store%2F&tab=mobile should return same results anywhere in the world irrespective of the device being tested on right? 🤔 

And isn’t Vercel’s next js analytics an extension of google page speed insights?

**Comment by madchester** [comment]
Same here issue is reproducible.
I got a score of 65 on Desktop based from the vercel analytics.

<img width="1027" alt="vercel-analytics" src="https://user-images.githubusercontent.com/7464673/97452532-cd381100-196f-11eb-8eba-1c7164a03638.png">

Is it because of the template?  🤔

**Comment by SalahAdDin** [comment]
I got even worst:
![image](https://user-images.githubusercontent.com/5034215/97476517-880be300-195f-11eb-9c58-19ac19413f3b.png)
![image](https://user-images.githubusercontent.com/5034215/97476639-b2f63700-195f-11eb-8c4f-d5545b0c0f6b.png)

But all is okay with desktop tests.

**Comment by okbel** [comment]
Thank you all for the feedback. We're currently tracking a bug here: https://github.com/vercel/next.js/issues/18416 
This could possibly be the one to blame, *fingers crossed*

**Comment by luke-denton-aligent** [comment]
Hi @okbel, I can see that the attached bug has been closed, but the Lighthouse scores are still in the orange for the Demo instance. Has that bug fix been deployed yet?

**Comment by chandan-reddy-k** [comment]
@okbel any updates here?

I still see the same level of scores and don't think #18416 solved the issue 😅
![Screenshot 2020-12-08 at 11 53 20 AM](https://user-images.githubusercontent.com/43699825/101447827-ffb03300-394b-11eb-958c-5d888344169f.png)

**Comment by b-emini** [comment]
According to lighthouse test , it seems that one of the issue resides with the images not being properly sized. I mean they were supposed to be sized automatically as it was a new feature added to nextjs if i am not wrong  but it doesnt seem to work on this case.
