### ISSUE TITLE
Wishlist is not working with shopify

### ISSUE THREAD

**Issue by ezatla** [vercel/commerce#331]
Hey fellows, I've run the project locally and I used Shopify as CMS,
The store runs fine, I get the products and everything else from Shopify, but
The **Wishlist** button doesn't seem to be working, it doesn't trigger anything and Wishlist page shows no items.

I have Wishlist config enabled in my _commerce.config.json_

**Comment by cond0r** [comment]
@ezatla Shopify provider doesn't have the Wishlist feature, please disable it from commerce.config.json
