### ISSUE TITLE
Add loading state for /wishlist

### ISSUE THREAD

**Issue by lfades** [vercel/commerce#332]
Right now the wishlist page shows "Your wishlist is empty" before showing your wishlist items, that should be a loading state instead.

**Comment by kursademirtas** [comment]
Hello, anyone works on it?

**Comment by lfades** [comment]
@kursademirtas Hi there and sorry for the late reply, no one is working on this!

**Comment by Andrewnt219** [comment]
Hi @lfades, I can work on it. Seem pretty straightforward as the page already has an `isLoading` state from `useWishlist`.

**Comment by Andrewnt219** [comment]
This issue should have been closed by #458 I assume?

**Comment by Adams-Ijachi** [comment]
is this issue still open
