### ISSUE TITLE
add tests

### ISSUE THREAD

**Issue by Vandivier** [vercel/commerce#346]
Can I add some tests? I would assume a small UI component testing scope with Jest to start with.

Per this issue: https://github.com/vercel/commerce/issues/345, I want to remove some extraneous code, but I would feel better if there were some tests I could pass when PR'ing

**Comment by lfades** [comment]
Closing for now as we don't want to invest too much into testing the UI for now, all of our focus is on creating a very stable commerce core for all providers.

**Comment by tkrotoff** [comment]
> our focus is on creating a very stable commerce core

"very stable" without tests?
