### ISSUE TITLE
Next.js Commerce boilerplates for each provider

### ISSUE THREAD

**Issue by leoortizz** [vercel/commerce#347]
Everyone might need a way to start a new Next.js Commerce app with a single provider, without all the references to providers that won't be used, and also without the demo layout. Is there any solution for this on the roadmaps?

Here are some ideas as I'm not sure on how would be the best way to handle it:

- integrate it to `create-next-app` or to a new CLI like `create-next-commerce`  with a option `-p [name]`/`--provider [name]` 
- a branch for each provider. Right now there's `bigcommerce` and `shopify` branches, but I'm not sure if it's updated/being used for this purpose
- a single repo for the Commerce framework and 'official forks' or templates for each provider

**Comment by muhammad-saleh** [comment]
it will be great also if we can remove other unused providers without breaking anything
I'm using Shopify and I tried to remove the bigcommerce provider the build broke

**Comment by leoortizz** [comment]
> it will be great also if we can remove other unused providers without breaking anything
> I'm using Shopify and I tried to remove the bigcommerce provider the build broke

It seems to be in progress, see #252

**Comment by leoortizz** [comment]
Closing it as it's not really an issue

**Comment by kungfu321** [comment]
I think it's big mistake and seem like not yet already for production.
