### ISSUE TITLE
Themes?

### ISSUE THREAD

**Issue by lawrencecph** [vercel/commerce#353]
In the README u say there is themeing available, how do i do this?

Should i create a folder /themes/example and then i can just put components in there and they will magically replace current ones? Or how does it work?

Thank you!

**Comment by givionte** [comment]
It's Nextjs, so you can theme however you want. The project demo is using Tailwinds with CSS Modules to structure their code.  You can drop Tailwinds and use regular CSS modules, or drop-in your preferred CSS framework.  Take a look through the components folder to see how their css is being applied to individual components.

**Comment by lawrencecph** [comment]
But how would i replace code in the components? Should i make a file in my own /theme folder, how do i make that file overwrite the one in the components folder?

Ty!

**Comment by givionte** [comment]
You'll have to go through and wipe all the current CSS files and modify the Tailwinds config file if you want to do your own theming.  This project was created to get a Nextjs store up and running in minutes, but leaves the CSS theming totally up to the developer's imagination.  If you want to make it easy to drop in or change themes, Tailwinds most certainly gives you the power to do so.

 As was mentioned in #241 you can certainly create your own themes folder, point the files at the components, and serve multiple themes this way for easier development.

**Comment by lawrencecph** [comment]
Sorry for keep this thread open, last message:
I know how to change the themes, but how do i change the code inside some of the component without replacing it directly in the components?
If you know what i mean? Can i overwrite the component jsx files from another folder, so updates to vercel commerce don't break my newly implemented updates?

**Comment by muhammad-saleh** [comment]
@lawrencecph If I understand you correctly then AFAICT this repository is meant to be forked and then later customized to your needs, It's not a versioned package that you can upgrade when there's a new release, If you want to include future fixes/features from this repo into yours then you will have to do that manually.
Unless of course the team here have a different opinion or different plans.

**Comment by lfades** [comment]
We will eventually move everything inside the `framework` folder to npm packages, so updates don't have to be done manually, that's going to be part of our biggest priorities moving forward, once we have a properly enforced commerce core in every provider.

When it comes to themes, once we have npm packages we'll be able to create multiple UIs with different themes that all use the same core commerce packages.
