### ISSUE TITLE
Issue: Fails when adding digitial product (BigCommerce) to cart

### ISSUE THREAD

**Issue by Blaze349** [vercel/commerce#358]
`react_devtools_backend.js:2560 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `Link`.`

Hello, I don't know why this error shows up when you try to add a digital product (BigCommerce) to the cart. Additionally, the categories do not divide the products. Every product shows in every category.

**Comment by Blaze349** [comment]
Is this even active anymore?

**Comment by pfcodes** [comment]
From `framework/bigcommerce/api/endpoints/cart/add-item.tsx`

```
const { data } = cartId ? await config.storeApiFetch(
  `/v3/carts/${cartId}/items?include=line_items.physical_items.options`,
  options
) : await config.storeApiFetch(
  '/v3/carts?include=line_items.physical_items.options',
  options
)
```

Only physical cart items are supported.
