### ISSUE TITLE
Checkout URL is <storename>.mybigcommerce.com

### ISSUE THREAD

**Issue by johnbwu** [vercel/commerce#361]
Is there anyway to have it show our Vercel url instead? for example <mydomain>.com/checkout

**Comment by lfades** [comment]
Bigcommerce didn't have a external checkout that was good as their on-site checkout when we built the provider, if that changes we'll welcome a PR to make the change but for the moment it is not possible.

**Comment by johnbwu** [comment]
@lfades what about for shopify?

**Comment by lfades** [comment]
@johnbwu We have a custom branch for custom checkouts and we're currently working on it
