### ISSUE TITLE
Reduce the types required to add an API operation

### ISSUE THREAD

**Issue by lfades** [vercel/commerce#368]
I feel that the current amount of types an API operation requires is a bit annoying, but haven't managed to reduce it!

**Comment by osseonews** [comment]
Agreed. The implementation here seems needlessly complex. useSWR is a simple  hook. What I could write in 5 lines of code in regular JS is now over 50 lines in typescript for a new API. Granted alot of that is cut/paste, but it's still exhausting to follow. I get the benefits of typescript, but maybe there is some way of simplifying how it's used in this repo, especially for new APIs.
