### ISSUE TITLE
better to keep product slug as domain.com/slug/p 

### ISSUE THREAD

**Issue by that-coder** [vercel/commerce#37]
It is better for SEO to create a URL in a format like above. Also, some sites will follow a pattern like, domain/slug/p/id
the slug entry may same for multiple products but id may differ.

**Comment by okbel** [comment]
Do you have any sources about this that we can read?

**Comment by that-coder** [comment]
In my personal experience, we got better ranking and more traffic generated throughthese kind of URL making 

For reference see how Flipkart is doing 

https://www.flipkart.com/samsung-galaxy-max-gold-32-gb/p/itmevakgf8gmvyte?pid=MOBEV7YDBCAFG3ZH&srno=b_1_2&otracker=browse&lid=LSTMOBEV7YDBCAFG3ZH5FUOXG&iid=4a09db74-d220-409a-9714-cb0b5fc55e1b.MOBEV7YDBCAFG3ZH.SEARCH


At the same time you won't see these kind of URL in amazon and all since google won't crawl Amazon url per day instead they will give the direct access to their search data store to get those URLs. And google rank them prior

**Comment by alexbs** [comment]
or even like this: domain/slug/p{id}
If the slug changes, it is possible to throw a 301 redirect to a new slug
