### ISSUE TITLE
Improve documentation on local env setup

### ISSUE THREAD

**Issue by pawelphilipczyk** [vercel/commerce#38]
I've deployed my next.js commerce based project and cloned it. 
I can see that all env values in Vercel dashboard are set and encrypted. 
Then I generated my store api account in BigCommerce and I got all values except for `BIGCOMMERCE_STOREFRONT_API_TOKEN` (which is not the same thing as `BIGCOMMERCE_STORE_API_TOKEN`).

I can see in BigCommerce api docs I could generate storefront api token with postman or something but this seems a bit complicated. 

Am I missing something simple? :D It feels like I am. I guess this is a call for docs improvement on local dev setup.

**Comment by madchester** [comment]
maybe this will help [#13](https://github.com/vercel/commerce/issues/13)

**Comment by pawelphilipczyk** [comment]
Thanks, it worked! I guess this is a piece of cake for someone familiar with Vercel CLI.

Do you know where do those generated values live? I do not see this client anywhere in my BigCommerce dashboard. 
This is a bit (too) magical.

**Comment by RayeEThompson** [comment]
You can see API token values or generate them in your [BigCommerce Control Panel](https://developer.bigcommerce.com/api-docs/storefront/graphql/graphql-storefront-api-overview#accessing-the-graphql-playground) you can find out how to do this here.

**Comment by okbel** [comment]
@pawelphilipczyk ! Those are part of Vercel<>BigCommerce integration - As soon as you pull those env vars, you are ready to go. 😌 

We updated our README! And more docs coming soon! Thank you!

**Comment by bryandandan** [comment]
Can anybody tell me where the env values are actually being used/called in the code?
