### ISSUE TITLE
Getting this error while trying to run nextjs in my local with bigcommerce

### ISSUE THREAD

**Issue by nikhil104iic** [vercel/commerce#380]
<img width="808" alt="Screen Shot 2021-06-18 at 10 17 14 AM" src="https://user-images.githubusercontent.com/38064079/122507757-69597a00-d01e-11eb-8b58-c4a7ebdb1c09.png">

Getting this while running build locally. I am using Bigcommerce as my provider but error is coming out to be in Saleor provider i.e.  ./framework/saleor/api/utils/fetch-graphql-api.ts

Can anyone help me in this please.

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
