### ISSUE TITLE
GetStaticProps Not working as expected on vercel Returning -1 HTTP error

### ISSUE THREAD

**Issue by achadee** [vercel/commerce#388]
Hi team, Id thought id submit an issue here as the customer success engineers didnt really answer or resolve my issue via support.

So I have a very large number of products, so I can't use getSataticPaths as the build time exceeds 45 minutes (with shopify API rate limit throttling) (plus who wants to wait that long anyway)

[slug].js
```tsx
export async function getStaticPaths({ locales }: GetStaticPathsContext) {
  const { products } = await getAllProductPaths()

  // we have too many products, static rendering will be done the first time a product is loaded up
  return {
    paths: [],
    fallback: true,
  }
}
```

Now this works perfectly on my local machine that builds everything every time. But on production its giving unexpected results on some products (not all). These products also work on my local environment which makes this super hard to debug:

https://storefront-7aja4imda-colabpantry.vercel.app/products/chutney-maison

Logs:

<img width="1067" alt="Screen Shot 2021-06-23 at 12 20 38 pm" src="https://user-images.githubusercontent.com/5952918/123025078-6d6e0900-d41d-11eb-8bc7-ef12f6fdee44.png">

Logs of a product that works:
<img width="1063" alt="Screen Shot 2021-06-23 at 12 21 34 pm" src="https://user-images.githubusercontent.com/5952918/123025177-91314f00-d41d-11eb-8672-0223b4de0338.png">

Now if you are returning HTTP statuses, what does a status of -1 mean? 

PS. I'm sorry I'm posting this here, I've submitted 2 detailed support tickets and both times they have told me to check the logs.

Its also worth noting that I can fix the issue by providing all the build paths eg.

[slug.js] (working - but build time exceeds 45 minutes)
```tsx
export async function getStaticPaths({ locales }: GetStaticPathsContext) {
  const { products } = await getAllProductPaths()

  // we have too many products, static rendering will be done the first time a product is loaded up
  return {
    paths: products.map((product) => `/products${product.node.path}`),
    // paths: [],
    fallback: true,
  }
}
```

**Comment by cond0r** [comment]
@achadee i think you are using an older version. be sure to apply the changes from https://github.com/vercel/commerce/pull/310/files (to fetch only first 100 best selling products).

**Comment by achadee** [comment]
The problem isn't the subset of paths I'm getting - though I might implement the top 100 products in a later release to improve site performance, 

the problem is that `fallback: true` isn't working when it should be. 

I mean technically speaking, this should load all pages upon request:

```tsx
 return {
    paths: [],
    fallback: true,
  }
```

However following this link you can see that some products return that -1 error
https://storefront-7aja4imda-colabpantry.vercel.app/products/chutney-maison


Here is a reference to a product that works from the same deployment:
https://storefront-7aja4imda-colabpantry.vercel.app/products/jordan-river-medjool-dates

Let me know if you have any ideas, Im a bit clueless since I can't replicate it locally :)

**Comment by cond0r** [comment]
@achadee ok, i thought that error happened because of the (API rate limit error since you have too many products on build time)

**Comment by achadee** [comment]
Does log drain log additional information not logged by Vercel? Because I can see the exact log event (as screen shotted above)

**Comment by cond0r** [comment]
It helped me to debug better, don't know if is the case here. By the way, also be sure to have this updated file also to try catch the api fetcher to catch some unexpected errors.

https://github.com/vercel/commerce/blob/main/framework/shopify/api/utils/fetch-graphql-api.ts

**Comment by achadee** [comment]
I have a slightly modified fetcher to work around the rate limit (as I was trying to build all products with getStaticPaths originally):

```tsx
const fetchGraphqlApi: GraphQLFetcher = async (
  query: string,
  { variables } = {},
  fetchOptions
) => {
  let waitingForResponse = true
  let tick = 0
  let res: any
  let dataResponse: any

  while (waitingForResponse && tick < 100) {
    res = await req(query, variables, fetchOptions)
    let { data, errors, status } = await res.json()

    dataResponse = data

    if (errors) {
      if (errors[0].message == 'Throttled') {
        console.log('Throttling - waiting 60 seconds', tick, variables)
        await timeout(60000)
        tick++
      } else {
        throw getError(errors, status)
      }
    } else {
      waitingForResponse = false
    }
  }

  return { data: dataResponse, res }
}
```

maybe that is the issue - i'll try and update it tomorrow and let you know :)

**Comment by achadee** [comment]
Hey I'm pretty confident there is an issue with Vercel.

i've wrapped my entire getStaticProps inside a try/catch and its still giving the error message on some products (not all) (and not locally)
https://gist.github.com/achadee/4849cac259672ac56b5317f101cda6e7

To see if its an issue with nextjs or  vercel I built the server manually using:

```
next build
next start
```

and started the node server locally in production mode manually, and it worked. 

Which leads me to believe the issue is with Vercel. 

Is there anything im missing?  @cond0r

**Comment by cond0r** [comment]
@achadee did you tried to fetch fewer products (without that throttle workaround) at build time ?  Actually i tried with hundreds of product and had no issues what so ever, i'm curious what's your product length number. 

The products that are failing are the same each time, or randomly generates that error to different products ?

**Comment by achadee** [comment]
We have over 1500 products

Ok I've implemented both the fetcher and get all best selling products. 

Just as a general note to anyone else using this this feature in the repo: 

_This doesn't solve the throttling issue as the storefront API throttler is based on a rolling [60 second execution time window](https://shopify.dev/concepts/about-apis/rate-limits). So if the shopify servers are busy, or if you require more information to statically generate your pages - you'll quickly hit the limit (with a large number of products). For my project requirements, I had to lower the 100 product limit to 50 to not get errors when building the project._

Anyway, I've built it locally with:

```
next build
next start
```

And that built as expected and worked for the broken products. 

Next I deployed it to Vercel

So im getting the same error when deploying to Vercel
https://storefront-h6aox77dw-colabpantry.vercel.app/products/chutney-maison

Status -1

<img width="1018" alt="Screen Shot 2021-06-29 at 10 08 17 am" src="https://user-images.githubusercontent.com/5952918/123718217-f07ddc00-d8c1-11eb-83d0-1b00d11c3335.png">

On the client side it looks like this:
<img width="723" alt="Screen Shot 2021-06-29 at 10 09 11 am" src="https://user-images.githubusercontent.com/5952918/123718267-0ee3d780-d8c2-11eb-8a52-4d5e4c4cff02.png">

and in the browser console:
<img width="1061" alt="Screen Shot 2021-06-29 at 10 09 56 am" src="https://user-images.githubusercontent.com/5952918/123718304-291db580-d8c2-11eb-834e-697df2d3a0db.png">

 @cond0r beginning to loose my mind / run out of ideas. If the node server works, we might have to leave Vercel and just spin up a custom server. I REALLY dont want to do this. If you are uncertain on what the next steps are, can you get more eyes on this?

I'm happy to give access to the repo where needed.

Thanks in advance :)

**Comment by achadee** [comment]
Also an idea. 

A lot of this could be resolved with a `getStaticBuildProps` or something which would allow us to build a large number of pages at once on the initial build.

Fallback via `getStaticProps`  could then be used for pages added after the deployment

eg.

```tsx
  return {
     pages: [
        {
            props: ...,
            path: '/t-shirt'
        }
     ]
  }
```

**Comment by cond0r** [comment]
@achadee feel free to invite me on that repo. I can take a look & try something. I know the "loose my mind" feel, almost had this weekend myself :).

I see the problem is more isolated to that product alone (or similar).

**Comment by achadee** [comment]
Ok I've given you access - before you start things up....

There are multiple instances (products) of the issue - and I can't find any similarities in the returned data. The product linked above is what I'm going off to show how to reproduce :)

Also, Just checking that you know that my code works perfectly with `next dev` and `next start` and I can only reproduce the issue on a deployed Vercel

**Comment by achadee** [comment]
Also just wanted to say thanks in advance. This issue has really got me scratching my head.

**Comment by cond0r** [comment]
@achadee is a rate limit error that happens because on your getProduct query. You query too much for each product, so makes that query expensive. And by the time it reaches that product it throws that throttled error because.  

<img width="553" alt="Screenshot 2021-06-29 at 14 36 07" src="https://user-images.githubusercontent.com/1243434/123790821-719b9a00-d8e7-11eb-930d-ac70bc8d918a.png">

If Shopify measures that by the time first request happened until last response (by IP), lambda being slower than your machine maybe that's the answer why on your local machine never happens (I managed to see build errors on mine too)

<img width="1141" alt="Screenshot 2021-06-29 at 14 30 45" src="https://user-images.githubusercontent.com/1243434/123790270-ca1e6780-d8e6-11eb-90e4-3ded158bab1b.png">

After i removed the products recommendations part from your get product query, everything works.  (By the way you can make another request for getting product recommendations on query root ->  productRecommendations, i will suggest it on your repo)

https://storefront-pi.vercel.app/products/chutney-maison

**Comment by achadee** [comment]
Wow, shopify really needs to generate better errors :/

Thank you so much!, ill change and test that now!

just one more thing:

This is working for me, why is that?

```tsx
export async function getStaticPaths({ locales }: GetStaticPathsContext) {
  // const { products } = await getAllProductPaths()

  let broken_paths = [
    '/products/breakfast-negroni-marmalade',
    '/products/blanc-de-caramel-42-caramelised-chocolate-with-sea-salt',
    '/products/hazelnut-gianduja-bombs',
    '/products/caramel-chocolate-freckles',
    '/products/62-chai-latte-dark-milk-hot-chocolate',
    '/products/chamellia-organic-iced-tea-ginger-lemongrass-sparkling',
    '/products/cranberry-macadamia-cherry-milk',
    '/products/2019-rare-hare-rose',
    '/products/nocciolato-bar',
    '/products/amphora-65-dark-chocolate',
    '/products/72-classic-dark-hot-chocolate-with-sea-salt',
    '/products/organic-tea-bags',
    '/products/the-toreador-black-pearl-collab',
    '/products/soleo-42-milk-chocolate',
    '/products/hazelnut-cocoa-bits-dark',
    '/products/chutney-maison',
    '/products/chamellia-organic-iced-tea-lemon-black-still',
    '/products/salted-caramel-rocky-road',
    '/products/pickled-cherries',
    '/products/velvety-marshmallow-milk',
    '/products/chamellia-nine-spice-fresh-chai',
    '/products/moet-chandon-brut-imperial-nv-gift-boxed',
    '/products/bianco-30-white-chocolate',
    '/products/orange-marmalade',
    '/products/los-hermanos-2019-tempranillo',
    '/products/mr-jones-christmas-ham-glaze-250ml',
    '/products/bugs-large-cooked-1kg',
    '/products/black-sesame-seeds-400g',
    '/products/lartisan-cheese-organic-petit-rouge-180g',
    '/products/mauri-mascarpone-250g',
  ]

  // we have too many products, static rendering will be done the first time a product is loaded up
  return {
    // paths: products.map((product) => `/products${product.node.path}`),
    // paths: [],
    paths: broken_paths,
    fallback: true,
  }
}
```

**Comment by achadee** [comment]
Im guessing you run your build paths on seperate threads on Vercel? So they have seperate IP addresses and the throttle limit isn't hit as fast when providing paths?

**Comment by cond0r** [comment]
@achadee the code above works because you have only 30 paths.. then let's say one path takes 1s you have 30 paths means your total query duration in build operation is 30s. Remember you query also pages, collections etc. But the problem is that you query on each product path, also collections that has also other set of products, so is too much.... On the link above i was using  the official query of getting product recommendations. And worked just fine with all 100 paths. If you want to persist that query then change the variable on get-all-product-paths to 30. 

https://shopify.dev/api/storefront/reference/common-objects/queryroot#productrecommendations-2021-04
