### ISSUE TITLE
How do I get this running?

### ISSUE THREAD

**Issue by jpatters** [vercel/commerce#39]
I have been unable to get this running locally or on Vercel. 
Locally, it tells me that there are a number of environment variables required from Big Commerce. So I signed up for an account and tried to create an API key. There are two different types of API keys in Big Commerce and neither of them produce the number of values or values with the same names as the ones required in this repo. So that was a dead end.

In Vercel I just get a bad gateway error after clicking attempting to "install" big commerce (in which I had to click login 3 times).

I'm really curious if anyone else has gotten this working and how you did it.

**Comment by thesobercoder** [comment]
Also for anyone willing to contribute, making it mandatory to sign up BigCommerce may actually discourage potential contributors.

**Comment by okbel** [comment]
Hey @jpatters! I'm sorry you struggled to much to get this working! We updated our README a couple of days ago. Have you tried that? Pulling the env vars? LMK! And thanks for the feedback! 

@thesobercoder We're currently working on supporting more data providers so stay tuned!

**Comment by StellaJung-Student** [comment]
@okbel for the new contributor~, how they know the proper values? Where can we get the API and Token~?

**Comment by David05500** [comment]
> @okbel for the new contributor~, how they know the proper values? Where can we get the API and Token~?

Have you managed to figure out yet?

**Comment by StellaJung-Student** [comment]
@David05500 Yeah.. any tips?

**Comment by David05500** [comment]
> @David05500 Yeah.. any tips?

Unfortunately I am looking for the answer myself!

**Comment by RayeEThompson** [comment]
In BigCommerce you can get the API tokens from the Store's control panel - you can refer to our documentation on authentication here: https://developer.bigcommerce.com/api-docs/getting-started/authentication/rest-api-authentication
You will also need a graphql auth token: https://developer.bigcommerce.com/api-reference/store-management/tokens/api-token/createtoken

The easiest way to connect however, is to use the Vercel CLI and pull your .env.local. This is part of the native integration ;)

**Comment by zeekrey** [comment]
@RayeEThompson How does the Vercel CLI help me getting the right credentials? It will only store and receive credentials. But it won't magically generate them. Or am I wrong here? 🤔 

This is my personal story. The needed data:

```
BIGCOMMERCE_STOREFRONT_API_URL=<>
BIGCOMMERCE_STOREFRONT_API_TOKEN=<>
BIGCOMMERCE_STORE_API_URL=<>
BIGCOMMERCE_STORE_API_TOKEN=<>
BIGCOMMERCE_STORE_API_CLIENT_ID=<>
```

I searched the whole BigCommerce docs but could only finde that I can obtain the following data from the BigCommerce dashboard:
* Client Secret
* Client ID
* Access Token
* API Path

This is documented here: [BigCommerce Docs](https://developer.bigcommerce.com/api-docs/getting-started/authentication/rest-api-authentication#obtaining-store-api-credentials#obtaining-store-api-credentials)
I would derive the following mapping:
* BIGCOMMERCE_STORE_API_TOKEN = Access Token
* BIGCOMMERCE_STORE_API_CLIENT_ID = Client ID
* BIGCOMMERCE_STORE_API_URL = API Path

For the storefront itself there are no credentials: 

> The Storefront API is unauthenticated, allowing you to make client-side requests for carts, checkouts, and orders using JavaScript.
[Source](https://developer.bigcommerce.com/api-docs/getting-started/authentication/authenticating-bigcommerce-apis)

But, there are so called _Storefront GraphQL credentials_. To use them I need to create a JWT like explained [here](https://developer.bigcommerce.com/api-docs/storefront/graphql/graphql-storefront-api-overview#authentication). So I would suppose that this is the BIGCOMMERCE_STOREFRONT_API_TOKEN. The BIGCOMMERCE_STOREFRONT_API_URL is the URL I see in the BigCommerce dashboard when I click on "View Store".

I'll try this now. Would be awesome if you could add the table below or any further information to the readme. ❤️  

| Variable        | Example           | Source|
| ------------- |-------------| -----|
| BIGCOMMERCE_STOREFRONT_API_URL|https://myfunnystore.mybigcommerce.com|BigCommerce dashboard, "View Store"|
| BIGCOMMERCE_STOREFRONT_API_TOKEN|iyK2eXAiXiJKV1QiLCJhbGciOiJFUzI1NiJ...|Should be generated: [BigCommerce Docs](https://developer.bigcommerce.com/api-docs/storefront/graphql/graphql-storefront-api-overview#authentication)|
| BIGCOMMERCE_STORE_API_URL|https://api.bigcommerce.com/stores/lk60zuokx/v3/ |BigCommerce dashboard, visible during the "Create API Account" process|
| BIGCOMMERCE_STORE_API_TOKEN|iyK2eXAiXiJKV1QiLCJhbGciOiJFUzI1NiJ... |BigCommerce dashboard, visible after the "Create API Account" process|
| BIGCOMMERCE_STORE_API_CLIENT_ID|iyK2eXAiXiJKV1QiLCJhbGciOiJFUzI1NiJ...|BigCommerce dashboard, visible afterthe "Create API Account" process|

**Comment by RayeEThompson** [comment]
You will need to use the Vercel CLI and use the cmd for pull .env.local, as long as you used the native integration. 
The Storefront API URL should contain the /graphql endpoint. Everything else looks correct.

**Comment by bryandandan** [comment]
Can anybody tell me where the env values are actually being used/called in the code?

**Comment by markcmurphy** [comment]
> Can anybody tell me where the env values are actually being used/called in the code?

They're being used in the [@bigcommerce/storefront-data-hooks](https://www.npmjs.com/package/@bigcommerce/storefront-data-hooks) node module: node_modules\@bigcommerce\storefront-data-hooks\api\index.js

**Comment by bryandandan** [comment]
Correct. Thank you!

**Comment by bhamed-altesse** [comment]
It should be as below :

BIGCOMMERCE_STOREFRONT_API_URL=https://store-{$STORE_ID}.mybigcommerce.com/graphql
BIGCOMMERCE_STOREFRONT_API_TOKEN=${**STOREFRONT_TOKEN**}
BIGCOMMERCE_STORE_API_URL=https://api.bigcommerce.com/stores/{$STORE_ID}
BIGCOMMERCE_STORE_API_TOKEN=${**STORE_TOKEN**}
BIGCOMMERCE_STORE_API_CLIENT_ID=${**STORE_CLIENT**}

With :
**STORE_ID**: you can get it from your bigcommerce admin URL,
**STOREFRONT_TOKEN**: easy way to get it is to go to Advanced Settings --> Storefront API Playground. Once connected to the GraphQL Playground pick the storefront_token from the URL,
**STORE_TOKEN**|**STORE_CLIENT**: go to Advanced Settings --> API Accounts and then create a V2/V3 API Token.

**Comment by BilalDev** [comment]
It should be as below:

BIGCOMMERCE_STOREFRONT_API_URL=https://store-${STORE_ID}.mybigcommerce.com/graphql
BIGCOMMERCE_STOREFRONT_API_TOKEN=${**STOREFRONT_TOKEN**}
BIGCOMMERCE_STORE_API_URL=https://api.bigcommerce.com/stores/${STORE_ID}
BIGCOMMERCE_STORE_API_TOKEN=${**STORE_TOKEN**}
BIGCOMMERCE_STORE_API_CLIENT_ID=${**STORE_CLIENT**}

With:
**STORE_ID**: you can get it from your bigcommerce dashboard URL,
**STOREFRONT_TOKEN**: easy way to get it is to go to Advanced Settings > Storefront API Playground and then pick the storefront_token from URL,
**STORE_TOKEN|STORE_CLIENT**: go to Advanced Settings > API Accounts then create a V2/V3 API Token.

**Comment by millerized** [comment]
> It should be as below:
> 
> BIGCOMMERCE_STOREFRONT_API_URL=[https://store-${STORE_ID}.mybigcommerce.com/graphql](https://store-$%7BSTORE_ID%7D.mybigcommerce.com/graphql)
> BIGCOMMERCE_STOREFRONT_API_TOKEN=${**STOREFRONT_TOKEN**}
> BIGCOMMERCE_STORE_API_URL=[https://api.bigcommerce.com/stores/${STORE_ID}](https://api.bigcommerce.com/stores/$%7BSTORE_ID%7D)
> BIGCOMMERCE_STORE_API_TOKEN=${**STORE_TOKEN**}
> BIGCOMMERCE_STORE_API_CLIENT_ID=${**STORE_CLIENT**}
> 
> With:
> **STORE_ID**: you can get it from your bigcommerce dashboard URL,
> **STOREFRONT_TOKEN**: easy way to get it is to go to Advanced Settings > Storefront API Playground and then pick the storefront_token from URL,
> **STORE_TOKEN|STORE_CLIENT**: go to Advanced Settings > API Accounts then create a V2/V3 API Token.

@BilalDev Thanks. 

✅ My auth only works with the store token + store id version of the `BIGCOMMERCE_STOREFRONT_API_URL` e.g. 
```bash
BIGCOMMERCE_STOREFRONT_API_URL=https://store-${STORE_TOKEN}-${STORE_ID}.mybigcommerce.com/graphql
```

🚫 These storefront api urls do not work with my generated API creds + storefront token: 
```bash
https://${STORE_NAME}.mybigcommerce.com/graphql
https://store-${STORE_ID}.mybigcommerce.com/graphql
```

Hope this helps!
