### ISSUE TITLE
My account removed?

### ISSUE THREAD

**Issue by osseonews** [vercel/commerce#392]
On each of the frameworks there is no longer any link in the navigation to sigin into an account or create one. I seem to remember this was included before. Was this an intentional change? If intentional, I don't think this is a good idea. On every e-commerce site, users expect to be able to find a link to sign in or create an account.

**Comment by sinan-yilmaz** [comment]
I am referring to [README.md](https://github.com/vercel/commerce#how-to-turn-features-on-and-off). You can enable or disable the customer authentication in commerce.config.json by setting the `customerAuth` to `true`
