### ISSUE TITLE
is it possible for me to use `saleor` as a provider?

### ISSUE THREAD

**Issue by KnowsCount** [vercel/commerce#394]
this is what I see in my `.env.template`:

```
# Available providers: bigcommerce, shopify, swell
COMMERCE_PROVIDER=

BIGCOMMERCE_STOREFRONT_API_URL=
BIGCOMMERCE_STOREFRONT_API_TOKEN=
BIGCOMMERCE_STORE_API_URL=
BIGCOMMERCE_STORE_API_TOKEN=
BIGCOMMERCE_STORE_API_CLIENT_ID=
BIGCOMMERCE_CHANNEL_ID=

NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN=
NEXT_PUBLIC_SHOPIFY_STOREFRONT_ACCESS_TOKEN=

NEXT_PUBLIC_SWELL_STORE_ID=
NEXT_PUBLIC_SWELL_PUBLIC_KEY=

NEXT_PUBLIC_SALEOR_API_URL=
NEXT_PUBLIC_SALEOR_CHANNEL=
```

there is indeed a `saleor` option in the bottom, but it does not say there is such option in the first line... just to make sure: is the integration with saleor finished and can I use it?

thank you for this wonderful project.

**Comment by lfades** [comment]
Closing as Saleor is now in .env.template. Thank you for the report 💯
