### ISSUE TITLE
Provider: GetCandy

### ISSUE THREAD

**Issue by glennjacobs** [vercel/commerce#395]
I run an open source project called GetCandy which is a Laravel package that provides a headless e-commerce API.

I would love to have the opportunity to integrate with this store front project. 

How would I best go about this?

**Comment by lfades** [comment]
Usually what every provider does is copy the folder of another provider and change it with theirs.

**Comment by lfades** [comment]
Usually what every provider does is copy the folder of another provider and change it with theirs.

**Comment by glennjacobs** [comment]
Thanks. But then what? Do a PR to bring it in? Or can we offer it as a separate npm package?

**Comment by lfades** [comment]
Make a PR, we'll eventually move every provider and the core to a separate package, currently having all of them inside the repo allows us to move faster.

**Comment by glennjacobs** [comment]
No worries, thanks for the guidance.

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
