### ISSUE TITLE
Wishlist API for BigCommerce fails to add an item.

### ISSUE THREAD

**Issue by Miladroigari** [vercel/commerce#396]
Adding an item to wishlist using BigCommerce framework results in:

BigcommerceApiError: Big Commerce API error (422):
```json
{
  "status": 422,
  "title": "JSON data is missing or invalid",
  "type": "https://developer.bigcommerce.com/api-docs/getting-started/api-status-codes",
  "errors": {
    "customer_id": "error.expected.jsnumber"
  }
}
```

A quick hacky fix is to make sure the `customer_id` is an integer not a string on this [line](https://github.com/vercel/commerce/blob/08813be880d0276c3b7308600771ae45ba4ec4ea/framework/bigcommerce/api/endpoints/wishlist/add-item.ts#L43).
```javascript
customer_id: Number(customerId)
```

**Comment by vczb** [comment]
this fix looks good to me, why you donth submit an PR @Miladroigari ?

**Comment by okbel** [comment]
Looks like this has been fixed!
