### ISSUE TITLE
Error "502: BAD_GATEWAY" on Nextjs vercel site

### ISSUE THREAD

**Issue by SVronskiy** [vercel/commerce#40]
Open https://nextjs.org/commerce and click "Clone & Deploy"

Click Continue with default project name

Click Install to Connect a BigCommerce Store to your Vercel Project

Get error:

```

An error occurred with this application.

This is an error with the application itself, not the platform.

502: BAD_GATEWAY

Code: 

NO_RESPONSE_FROM_FUNCTION

ID: 

arn1::glhqb-1603884124738-af1b3d8f06af

If you are a visitor, contact the website owner or try again later.
If you are the owner, check the logs for the application error.
```

BTW. link "check the logs" returns 404 error.

Created the same bug in [BigCommerce Q&A](https://support.bigcommerce.com/s/question/0D54O00006f05edSAA/error-502-badgateway-on-nextjs-vercel-site)

**Comment by okbel** [comment]
Hi @SVronskiy ! Could you retry? We noticed issues with BigCommerce API last week, we were wondering if that was the case for this. Thank you! LKM!

**Comment by SVronskiy** [comment]
Hello, @okbel !

Now it works! I'm getting two factor authenticationm form instead of error on bigcommerce site and can complete installation and get to the site preview. 
Thank you!

**Comment by okbel** [comment]
Woohoo! Thanks for letting me know!

**Comment by fandy** [comment]
@okbel this error has come back. I've tried yesterday and today and had the same issue (unable to install).
