### ISSUE TITLE
Provider: Commerce.js

### ISSUE THREAD

**Issue by sarvarrose** [vercel/commerce#406]
Ecommerce Provider: https://commercejs.com/

**Comment by robbieaverill** [comment]
Duplicate of https://github.com/vercel/commerce/issues/193

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
