### ISSUE TITLE
Swell Provider: Account Functionality Does Not Work

### ISSUE THREAD

**Issue by osseonews** [vercel/commerce#407]
Per Issue 392, we added the customerAuth to the config and set it to true. This adds the customer links, but they do not work. 

We noticed the following errors:
1. Log in doesn't work. If you try to sign in with existing account all you get in the loading in the LogIn button and you are never logged in. We know the account exists, because if we use Swell's Nuxt.js storefront theme we can log in fine. 
 
2. Creating a new account doesn't work. If you try to add a new account, you can submit the form, but it does nothing. Again, not an issue with Swell per se, b/c their Nuxt.js theme works fine for this. 

3. No functionality for resetting password. Finally ,there is no link for a user to reset their password. This is basic for any ecommerce site.

BTW, we also tried the customer functionality with another provider, Vendure, and had the same issues as above.

**Comment by osseonews** [comment]
We have figure out how to get this to work. Apparently, there is a small bug in the code, in that if you switch frameworks after an initial build, you still need to include the older framework information in the env.local or errors are thrown. Not sure why. So we now just have all the frameworks in the env.local with blank data, except for the framework we are testing.

But some issues that remain:
1. There is no confirmation of an email upon signup before activating accounts. This will cause massive spam to all stores.

2. Forgot password link is only shown after an unsuccesful login and it's very difficult to spot. This is not user-friendly. It's better to just have this link on the signin page under the form.

3.  Also, alot of customer functionality is still not actually developed (e.g. order list page is just dummy info), and that thru us for a loop, as we were looking for customer data that is just not implemented.

**Comment by nsakibp** [comment]
@osseonews 
Hi, Hope you are well. Can you please let us know if you have solved the Account Functionality issue?
If yes, then how? 

Thanks in advance

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
