### ISSUE TITLE
Call a different Shopify url store depending on locale

### ISSUE THREAD

**Issue by PierreBeaufils** [vercel/commerce#408]
Hello,

Is it currently possible to switch to a different shopify store when the user change the language by the i18n widget ?

Thanks !

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
