### ISSUE TITLE
The /search isn't working correctly with BigCommerce 

### ISSUE THREAD

**Issue by geniti** [vercel/commerce#410]
The products related to a specific category are not showing up! 

So the demo is not working properly. Im very disappointed

**Comment by geniti** [comment]
@lfades

**Comment by wimsikal** [comment]
I am experiencing the same issue.  /search/category does not return the products in the given category. Instead, it returns all products.

**Comment by MitchStarkTekton** [comment]
We noticed this issue as well when getting started with BigCommerce. I opened [this PR (pending a review)](https://github.com/vercel/commerce/pull/422) to resolve the issue

**Comment by lfades** [comment]
Should be fixed by https://github.com/vercel/commerce/pull/422
