### ISSUE TITLE
I want to add Direct-Message function in next commerce

### ISSUE THREAD

**Issue by takashiAg** [vercel/commerce#413]
I want to add function Direct-Message such as facebook, twitter, instagram.
But, I don't know how to develop.

Suppose a user logs in using shopify's storefront-api.
And then the user makes a request to another API server.
How do the server confirm that the token in request valid or invalid?
Is there such a method at present?

I just want to additional function such as chat, messaging and so on.
Let me know if there is other good way.

**Comment by okbel** [comment]
This is not in the scope of the project.
