### ISSUE TITLE
Can't deploy this code locally on windows (same procedure worked on Linux)

### ISSUE THREAD

**Issue by knixer** [vercel/commerce#420]
I wasn't able to deploy this locally through my windows computer. When I ran` yarn dev` on my windows computer I got the error message: 

```
NODE_OPTIONS='--inspect' next dev
'NODE_OPTIONS' is not recognized as an internal or external command,
operable program or batch file.
```
I followed the steps under "Contribute" on the main page of this repo ( https://github.com/vercel/commerce ). I did the same thing on my Linux computer and was successful. Why?

**Comment by osseonews** [comment]
To get this to work on Windows, install cross-env: yarn or npm i cross-env and then add cross-env to the scrip. See this: https://stackoverflow.com/questions/53948521/node-options-is-not-recognized-as-an-internal-or-external-command

So something like this in the package.json:
`"dev": "cross-env NODE_OPTIONS='--inspect' next dev"`

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
