### ISSUE TITLE
nextjs-commerce as a npm package

### ISSUE THREAD

**Issue by lehoangphan** [vercel/commerce#426]
I have an existing Nextjs project now I need reuse the standarlize of this project (nextjs-commerce, vendure Provider) 

Does any npm package like nextjs-commerce or nextjs-commerce-vendure for reuse? 

I try to copy folder framework/commerce  for reuse but it seem to be not work outside this project. 

Thanks.

**Comment by pfcodes** [comment]
Seriously. How are we supposed to keep up with updates? Checking latest commit date then manually copying and pasting changed files?

**Comment by chinchang** [comment]
There is absolutely no docs on keep update to date with this repo. Please guide us, maintainers.

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
