### ISSUE TITLE
Finish the core commerce schema

### ISSUE THREAD

**Issue by lfades** [vercel/commerce#429]
The current core schema is missing multiple pieces of different commerce features and current types are not finished. Core types should be extendable by community PRs, but not inside providers.

First, we need to start properly defining every core schema type:

- [x] #504 
- [x] #505
- [x] #506
- [x] #509
- [x] #511

Once the above are done, we can start working towards removing customization over our core types:

- [x] #512

> **Why shouldn't our types be extendable?**
We're trying to create a single schema that works for every commerce feature an app might need, if something is missing we'll add it the core types, but we don't want providers to extend our types because if we one day do themes, that can make providers incompatible with each other.

**Comment by themiligod** [comment]
lets get this deployed
