### ISSUE TITLE
Bug: switching languages does not update currency locale format

### ISSUE THREAD

**Issue by robbieaverill** [vercel/commerce#43]
Steps to reproduce:

* Go to https://demo.vercel.store/search?q=accessories
* Scroll to bottom, change English to Español
* Notice things update, but price formats remain in US locale
* Refresh the page
* Notice price formats are now shown in Spanish locale format

Expected: locale formats should update with the rest of the DOM repaint, rather than requiring a page refresh

**Comment by okbel** [comment]
We currently don't support multi-currency. Please, open one issue per topic. 
It's in our roadmap! Thank you.

**Comment by robbieaverill** [comment]
Thanks for the reply. As far as I can tell from the UI and the demo store data, it's a single currency but formatted in different locale. Perhaps you should revert #47 and/or remove all locale formatting of prices altogether to remove confusion if you do not wish to support it.
