### ISSUE TITLE
Shopify Checkout Throttling and Queue

### ISSUE THREAD

**Issue by ottomated** [vercel/commerce#431]
This repository is missing two critical features required for large Shopify stores:

> **Checkout-level throttle**
Shopify limits the amount of checkouts that can be created on the Storefront API per minute. If an API client exceeds this throttle, then a 200 Throttled error response is returned. Shopify recommends designing your app to be resilient to this scenario. For example, you could implement a request queue with an exponential backoff algorithm.

> **/throttle/queue**
Shopify redirects users in the checkout flow to `/throttle/queue` if the store is under high traffic.

Without these features, two things will happen. The API silently fails when creating a checkout session, meaning that addToCart requests also silently fail. Also, during the checkout flow, the user will be redirected to a nonexistent URL.

**Comment by DanielHirunrusme** [comment]
This is an interesting subject. If a store is facing this issue during sales then bots may likely be involved. 

Not only does Shopify Plus have a throttle but also a checkpoint option to solve a captcha before receiving a checkout url.

Obviously, some bots can still get around this checkpoint. It’s an uphill battle and Shopify Plus is constantly adding patches to bot squash and handle traffic.

Question is: During these types of sales do you want to be responsible for scaling the site to handle this amount of traffic/bots or allowing Shopify by using a theme?

**Comment by balakedev** [comment]
> If a store is facing this issue during sales then bots may likely be involved. 

Lot's of shopify plus stores hit peaks of more than 4000 concurrent users, particularly merchants that have product releases or drops. I would say this is something the vercel commerce team needs to address pretty quickly. There are work arounds that you can do in the existing project to resolve this issue that don't involve a queue. But it would be better if the core did actually use cart instead of checkout.

**Comment by muhammad-saleh** [comment]
Referencing this here:
https://github.com/vercel/commerce/issues/430

**Comment by ottomated** [comment]
> This is an interesting subject. If a store is facing this issue during sales then bots may likely be involved.

I actually created this issue because I manage https://ludwig.gg, and ran into these issues yesterday during a merch release. Especially since by default, the repository creates a cart session upon the first `useCart` call, it doesn't take too much traffic to trigger throttling. Perhaps if there isn't an existing cart, the framework should wait until the first add, remove, or update request to actually create the cart session.

> Question is: During these types of sales do you want to be responsible for scaling the site to handle this amount of traffic/bots or allowing Shopify by using a theme?

The reason I shifted to this framework was to avoid using themes because of their limitations. I will be in contact with Shopify Plus to find out if it's feasible to re-implement their checkout queue, or add a single redirect for the `/throttle/queue` page (which is undocumented, as far as I can see)

**Comment by balakedev** [comment]
@ottomated, I might be able to help you with this issue as my team has solved it. There’s only a few lines of code to change to stop useCart() initialising a cart immediately on page view and only triggering it on add to cart. Happy to collaborate here.

**Comment by cond0r** [comment]
@ottomated just created a PR with your suggestion to create a checkout only on the fist cart interaction, not the very first visit of the store. 

I started also to implement the Cart API instead of Checkout, i will make a PR with that too when is finished.

@balakedev would be nice for the community to create a PR when you have a fix or an improvement so we all can benefit from it :)

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
