### ISSUE TITLE
Bug: PDP page doesn't format prices correctly

### ISSUE THREAD

**Issue by robbieaverill** [vercel/commerce#44]
See https://demo.vercel.store/product/next-js-short-sleeve-unisex-t-shirt

The price is 13.50 USD, but it's rendered as 13.5 USD. Should be 13.50 USD.

![image](https://user-images.githubusercontent.com/5170590/97606506-18ccd800-19cd-11eb-95a6-f9f701449f9c.png)

**Comment by bntzio** [comment]
Fixed on #47

**Comment by robbieaverill** [comment]
Nice, thanks @bntzio
