### ISSUE TITLE
BigCommerce - Wishlist page: Cannot remove item from wishlist

### ISSUE THREAD

**Issue by pfcodes** [vercel/commerce#446]
Attempting to remove a wishlist item from this page does nothing. Apparently the wrong `itemId` is being passed. The `WishlistButton` component uses a different `itemId` (`itemInWishlist.id`)

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
