### ISSUE TITLE
The /checkout isn't working correctly after I logged in as a user/customer  (with BigCommerce)

### ISSUE THREAD

**Issue by juandominguezgalvan** [vercel/commerce#448]
There seems to be a problem when a user tries to go to /checkout with BigCommerce, it returns a blank page with the following message:
{"data":null,"errors":[{"message":"An unexpected error ocurred"}]}
I'm not sure where the issue has come from. I've made zero changes to the original code from the starter kit and I think I've configured the store properly in BigCommerce.

Any thoughts or guidance?

**Comment by Nazmer** [comment]
I have the same problem

**Comment by kogan007** [comment]
@Nazmer @juandominguezgalvan 

add BIGCOMMERCE_STORE_URL and BIGCOMMERCE_STORE_API_CLIENT_SECRET with their respective values to .env file

**Comment by kogan007** [comment]
Also add BIGCOMMERCE_STORE_API_STORE_HASH if you haven't already

**Comment by juandominguezgalvan** [comment]
Thanks @kogan007, 
Could you provide us some guidance on how to obtain these environmental variables? 
Because I used the **Vercel cli** and pulling .env.local from vercel didn't set (BIGCOMMERCE_STORE_URL, BIGCOMMERCE_STORE_API_CLIENT_SECRET, BIGCOMMERCE_STORE_API_STORE_HASH).

**Comment by juandominguezgalvan** [comment]
@kogan007 @Nazmer  I've created a new API in the Advance Settings Menu from the BigCommerce Dashboard 
and now the checkout seems to work.
Thanks again @kogan007 and hope this helps @Nazmer.
