### ISSUE TITLE
Bug: PDP page doesn't render prices formatted for the current locale

### ISSUE THREAD

**Issue by robbieaverill** [vercel/commerce#45]
Similar to https://github.com/vercel/commerce/issues/44

When you switch to Spanish (bottom right) the prices should be displayed in Spanish locale format, e.g. `13,50 US`. They remain unformatted.

Would probably be fixed by fixing https://github.com/vercel/commerce/issues/44.

**Comment by robbieaverill** [comment]
Update after #47 was merged:
![image](https://user-images.githubusercontent.com/5170590/97647464-8f8ac500-1a0f-11eb-83d6-04ee16634452.png)

Still some bugs here

**Comment by okbel** [comment]
We currently don't support multy-currency. It's in our roadmap but notice that the exchange can be handled by the Bank/Credit Card

**Comment by robbieaverill** [comment]
My mistake, I was just following the UI and noticed that it was broken. Perhaps you should remove the ability to localise currency from this demo store if it's not a supported feature?
