### ISSUE TITLE
Bug: Prompt to accept cookie use is not remembered

### ISSUE THREAD

**Issue by robbieaverill** [vercel/commerce#46]
![image](https://user-images.githubusercontent.com/5170590/97606712-56316580-19cd-11eb-9682-2b72000a7bb6.png)

Confirmation of cookie use should be remembered (with a cookie presumably), but it continues to show up every time you refresh the page.

**Comment by jerrylopez** [comment]
@robbieaverill Looks like this one is being worked on or will be worked in #6

**Comment by marbiano** [comment]
@robbieaverill https://github.com/vercel/commerce/pull/52
