### ISSUE TITLE
Cumulative Layout Shift on Product Page

### ISSUE THREAD

**Issue by JamesSingleton** [vercel/commerce#472]
Running lighthouse on https://demo.vercel.store/product/next-js-enamel-mug, it says to avoid large layout shifts for the carousel under the main image.
![image](https://user-images.githubusercontent.com/21000200/132540856-8ed780e8-4773-4083-a400-d3110c0377cb.png)

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966

**Comment by JamesSingleton** [comment]
I honestly forgot this PR was even open 😅
