### ISSUE TITLE
Multiple store support? Multi tennancy

### ISSUE THREAD

**Issue by Jarrodsz** [vercel/commerce#478]
Any thoughts on multisite from
1 install with multi tennancy?

What would be best approach towards this. Kind regards project is awesome.

**Comment by Jarrodsz** [comment]
Any updates on this?

Is multi store from 1 install possible?

**Comment by okbel** [comment]
Not plan of this project but the approach would be using [Platforms](https://github.com/vercel/platforms) pattern and Next.js Commerce. We worked on an example and we will push it soon to vercel/examples 
Example here: https://vercel.shop/

**Comment by ashitikov** [comment]
+1 will be grateful for example with platforms and commerce
