### ISSUE TITLE
Provider: WooCommerce

### ISSUE THREAD

**Issue by flyboarder** [vercel/commerce#480]
It would be great if woocommerce was one of the supported providers.

**Comment by ramyareye** [comment]
I did a very first version here: https://commerce-mvjc07mzq-woocommerce.vercel.app/ 
base on [wp-graphql](https://github.com/wp-graphql/wp-graphql) and [wp-graphql-woocommerce](https://github.com/wp-graphql/wp-graphql-woocommerce)

by the next weekend I may can complete all the functionality

**Comment by fabianmarz** [comment]
Duplicate of #172. @ramyareye, could you please also share your progress there? :-)

**Comment by geniti** [comment]
> I did a very first version here: https://commerce-mvjc07mzq-woocommerce.vercel.app/
> base on [wp-graphql](https://github.com/wp-graphql/wp-graphql) and [wp-graphql-woocommerce](https://github.com/wp-graphql/wp-graphql-woocommerce)
> 
> by the next weekend I may can complete all the functionality
Could you please share some of the steps need to be made?

**Comment by geniti** [comment]
@ramyareye are you planning to launch this with all functionality?

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966

**Comment by hemangjoshi37a** [comment]
any update on this ? any new alternative available for woo-commerce to integrate  with this ?
