### ISSUE TITLE
Type error compiling with shopify framework

### ISSUE THREAD

**Issue by ryangall7** [vercel/commerce#489]
I'm getting this error when trying to run `npm run build`

```
Type error: Argument of type '{ method: string; headers: { 'Content-Type': string; } | { 'Content-Type': string; length: number; toString(): string; toLocaleString(): string; pop(): string[] | undefined; push(...items: string[][]): number; ... 28 more ...; [Symbol.unscopables](): { ...; }; } | { ...; } | { ...; }; ... 7 more ...; timeout?: numbe...' is not assignable to parameter of type 'FetchOptions'.
  Type '{ method: string; headers: { 'Content-Type': string; } | { 'Content-Type': string; length: number; toString(): string; toLocaleString(): string; pop(): string[] | undefined; push(...items: string[][]): number; ... 28 more ...; [Symbol.unscopables](): { ...; }; } | { ...; } | { ...; }; ... 7 more ...; timeout?: numbe...' is not assignable to type '{ agent?: Agent | undefined; retry?: RetryOptions | undefined; }'.
    Types of property 'agent' are incompatible.
      Type 'Agent | ((parsedUrl: URL) => Agent) | undefined' is not assignable to type 'Agent | undefined'.

   8 |   async (query: string, { variables, preview } = {}, fetchOptions) => {
   9 |     const config = getConfig()
> 10 |     const res = await fetch(config.commerceUrl, {
     |                                                 ^
  11 |       ...fetchOptions,
  12 |       method: 'POST',
  13 |       headers: {
```

Everything works fine in dev but building for a deployment fails. I've reverted to the initial commit and I'm still receiving the error. I don't really know enough about typescript to fully debug. But I can't find any references to the type Agent in any of the code so I'm kinda stumped

**Comment by ryangall7** [comment]
this is in the `./framework/local/api/utils/fetch-local.ts` file btw.

**Comment by ryangall7** [comment]
Small update here, I realized that since we're not using the `local` framework I can ignore that whole folder in the `tsconfig.json` but that just popped up the same error in `./framework/shopify/api/utils/fetch-graphql-api.ts` so it's not isolated to a single framework, but something with either the version of some module or my system? Though this error is also breaking our vercel builds so I suspect its a issue in a deplenency

**Comment by hsdonkin** [comment]
I also had this issue with Shopify, this is currently broken in the example repo.

- there's a type declaration in `framework/commerce/api/index.ts` for `GraphQLFetcher`
- the `GraphQLFetcher` has `fetchOptions` which are required to be a `RequestInit` from `node-fetch`
- however, there's an invalid argument being passed in... somewhere... so there's an invalid type error

I can fix this by changing `fetchOptions?: RequestInit` to `fetchOptions?: any` but it's not a long term solution
