### ISSUE TITLE
Error: Page with slug 'en-US/<no source>' not found

### ISSUE THREAD

**Issue by Florian-crg** [vercel/commerce#493]
### What version of Next.js are you using?
11.0.0

### What version of Node.js are you using?
v12.22.1

### What browser are you using?
Chrome, Firefox

### What operating system are you using?
MacOS M1

### How are you deploying your application?
next dev

### Describe the Bug

I've just cloned the repo and I get the following error 

```
error - pages/[...pages].tsx (42:10) @ getStaticProps
Error: Page with slug 'en-US/<no source>' not found
...
```

It seems to work normally, but the error is showing on each reload of first load.

**Comment by kogan007** [comment]
In getStaticPaths change it so that for the return its something like paths.map(path => ({ params: { pages: [path] } }))

**Comment by Florian-crg** [comment]
I am not sure what you mean sorry.

Maybe you could make a PR since this is a global concern. 
   
https://github.com/vercel/commerce/blob/main/pages/[...pages].tsx

**Comment by carl-st** [comment]
Did you manage to fix the issue? Just got the same errors in Next 12.

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
