### ISSUE TITLE
Focus trap does not trap focus

### ISSUE THREAD

**Issue by hsdonkin** [vercel/commerce#499]
Tested this with the `<Modal />` component, where `<FocusTrap />` is used. It's possible to reverse tab into the main.

![recording (39)](https://user-images.githubusercontent.com/49598076/134550078-633c5fb1-26e1-4edb-98c3-ba8c9dd7cf13.gif)

**Comment by luisorbaiceta** [comment]
It happened the same to me and I finally ended up adding [focus-trap-react](https://github.com/focus-trap/focus-trap-react). Hope this helps

**Comment by charkour** [comment]
Moving to focus-trap-react worked well.

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
