### ISSUE TITLE
[Bug] Selecting variant with different price point doesn't update price tag.

### ISSUE THREAD

**Issue by ceiphr** [vercel/commerce#508]
The price will be updated upon adding to cart, but the change in price is not shown in the product view.

**Comment by lfades** [comment]
@ceiphr Is the bug happening in our demo with BigCommerce or with another provider, or in general?

**Comment by ceiphr** [comment]
It is occurring with Shopify. I'm unfamiliar with how other providers handle price for variants. I haven't tested this with any of the demos.

The following change to the `price` object's amount in `/components/product/ProductSidebar` resolved the issue:

```tsx
const { price } = usePrice({
	amount: (variant ? variant.price : product.variants[0].price), // instead of product.price.value
	baseAmount: product.price.retailPrice,
	currencyCode: product.price.currencyCode!,
})
```

Should I make a PR for this, @lfades?

**Comment by lfades** [comment]
@ceiphr it may have broke for other providers with that change, in this case we need to make sure the price of the product matches the variant 🤔

**Comment by ceiphr** [comment]
Would it make more sense to do this?
```tsx
variant ? variant.price : product.price.value
```
So, variant price is only applied if a variant is being shown. As I understand from the logic, the product object is consistent between providers, correct?

**Comment by ceiphr** [comment]
@geniti, I'm a bit confused by your comment. The snippet I commented is the solution I've made which seems to work for Shopify. Specifically, `amount: (variant ? variant.price : product.variants[0].price)`. This way, variant price is used, which will update when a variant is selected. I hope that helps!

**Comment by ceiphr** [comment]
@geniti the version of commerce starter kit I'm using has this before the `return`:

```tsx
const { price } = usePrice({
	amount: product.price.value,
	baseAmount: product.price.retailPrice,
	currencyCode: product.price.currencyCode!,
})
```

Mine also has a `Text` component for displaying the price:

```tsx
<Text
    className='text-cyan pb-4 break-words w-full max-w-xl'
    variant='sectionHeading'
    html={`${price} ${product.price?.currencyCode}`}
/>
```

My solution is to rewrite `amount` for the object passed to `usePrice`, like so:

```tsx
variant ? variant.price : product.price.value
```

It seems like your file is missing these parts of the starter. Maybe you're using an older version?

**Comment by ceiphr** [comment]
@gnacoding nice catch! I completely forgot I updated the `ProductVariant` type.

Also, to answer your question, my version of vercel/commerce is two months old. So, either, the ordering of price and variant was different before, or that was another thing I forgot about.

I'm going to make a fork and write a PR for this.

Side note: @lfades, just curious, are you willing to add this project to [Hacktoberfest](https://hacktoberfest.digitalocean.com/)?

**Comment by philsmithies** [comment]
Having the same issue with Shopify as of now

**Comment by gnacoding** [comment]
I'm resurrecting this topic due to the recent update to next13. 

The code:
```tsx const { price } = usePrice({
    amount: (variant ? variant.price : product.price.value),
    baseAmount: product.price.retailPrice,
    currencyCode: product.price.currencyCode!,
  })
```
still works but TypeScript is now having a problem with 'amount':
```tsx
Type 'number | ProductPrice | undefined' is not assignable to type 'number'.
  Type 'undefined' is not assignable to type 'number'.ts(2322)
```

ProductPrice.value ( is a defined as 'number' in product.ts - so I'm not quite sure what I'm missing.
By using:
```tsx
    amount: (variant ? variant.price?.value : product.price.value),
```
TypeScript still says it's not assignable to type 'number'

Could someone please give me a hint?

**Comment by gnacoding** [comment]
> I'm resurrecting this topic due to the recent update to next13.
> 
> The code:
> 
> ```tsx
>     amount: (variant ? variant.price : product.price.value),
>     baseAmount: product.price.retailPrice,
>     currencyCode: product.price.currencyCode!,
>   })
> ```
> 
> still works but TypeScript is now having a problem with 'amount':
> 
> ```tsx
> Type 'number | ProductPrice | undefined' is not assignable to type 'number'.
>   Type 'undefined' is not assignable to type 'number'.ts(2322)
> ```
> 
> ProductPrice.value ( is a defined as 'number' in product.ts - so I'm not quite sure what I'm missing. By using:
> 
> ```tsx
>     amount: (variant ? variant.price?.value : product.price.value),
> ```
> 
> TypeScript still says it's not assignable to type 'number'
> 
> Could someone please give me a hint?
> 
> EDIT: in product.ts > export interface ProductVariant > price? is now optional


For anyone interested - I ended up modifying the accepted types of the usePrice.tsx hook: 
```
packages/commerce/src/product/use-price.tsx
```
```tsx
export default function usePrice(
  data?: {
    amount: number | any  /*<--- Add any */
    baseAmount?: number
    currencyCode: string
  } | null
) {
  const { amount, baseAmount, currencyCode } = data ?? {}
  const { locale } = useCommerce()
  const value = useMemo(() => {
    if (typeof amount !== 'number' || !currencyCode) return ''

    return baseAmount
      ? formatVariantPrice({ amount, baseAmount, currencyCode, locale })
      : formatPrice({ amount, currencyCode, locale })
  }, [amount, baseAmount, currencyCode])

  return typeof value === 'string' ? { price: value } : value
}

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
