### ISSUE TITLE
Enviroment variables

### ISSUE THREAD

**Issue by emilkowalski** [vercel/commerce#51]
I am working with bigcommerce for the first time. I keep getting errors with the enviroment variables. Does anyone have a quickstart for bigcommerce or any hints on how to get this thing running?

**Comment by frannunezrivera** [comment]
Please take a look at already opened/closed issues before opening a new one about the same thing.

I this case:
https://github.com/vercel/commerce/issues/30

**Comment by RayeEThompson** [comment]
@emilkowalski you can always look at developer.bigcommerce.com as well. The .env supports secrets for both Storefront GraphQL API and Storefront REST APIs.

**Comment by okbel** [comment]
Please, check the README file that we added documentation on how to proceed. Thank you!

**Comment by bryandandan** [comment]
Can anybody tell me where the env values are actually being used/called in the code?
