### ISSUE TITLE
Setup npm packages for the core and every provider

### ISSUE THREAD

**Issue by lfades** [vercel/commerce#513]
This is our most important step in order to be able to use Next.js Commerce outside of our current demo without making it difficult to get updates and bug fixes.

We should be able to have a npm package for every folder inside the [framework folder](https://github.com/vercel/commerce/tree/main/framework) inside this same repo under a new folder named `packages`. This is what we'll need:

1. A worskpace tool like [npm workspaces](https://docs.npmjs.com/cli/v7/using-npm/workspaces) or [Lerna](https://github.com/lerna/lerna), whatever works best.
2. A tool that helps us quickly publish releases and updates of every package
3. Automatically create deployments of our demo as that's going to be our main testing ground, this can probably be as simple as updating our settings in vercel.com
4. Publish every package as a ES module, Next.js already supports ES modules [behind a flag](https://nextjs.org/blog/next-11-1#es-modules-support) and will be the default with Next.js 12

For the moment we want every provider to be inside the repo as we work on making the Next.js Commerce API stable, and that's ideal if we want to test every provider in our current demo, but that's not a requirement for any provider once we have working npm packages.

**Comment by FabianHippmann** [comment]
Did you also consider using yarn workspaces ? Speedwise Yarn workspaces wins over using lerna.

We also used yarn with similar setup & are actually building our own UI packages -> `packages/ui` as a yarn workspace package & moved nextjs commerce inside of an `apps/shop` - workspace/folder
