### ISSUE TITLE
The Future of Next.js Commerce

### ISSUE THREAD

**Issue by lfades** [vercel/commerce#515]
When we first released Next.js Commerce to the public in our first Next.js Conf, we wanted to have a real e-commerce app that worked with BigCommerce and Next.js, as we we're building it we realized we could do much more and started doing a "core" framework that could be used by more commerce providers, or else we would need to repeat the same work for every provider out there (and there are a lot of them).

After the Next.js Conf was done we started working on adding more and more providers to the repo, we currently have 7 providers and more on the way. A lot of the work has been done by our e-commerce partners themselves while we focused on getting the core framework into a better state.

As of today the core of Next.js Commerce is missing features, structure changes, and more, but we are more committed than ever to keep working on it as we aim towards our goal: **An open source commerce framework that works with anything you throw at it.**

In order to achieve our goal we have to stabilize our core data types, improve tooling, add documentation, and create npm packages for the core and every provider, allowing it to work outside of our demo in any other Next.js (and react) application, subsequently allowing us to have a marketplace of themes under the same core, with a one click switch between e-commerce providers.

And the above is just the start! In the issues below you can see our live roadmap to **V1**:

- [x] #513
- [x] #429
- [ ] #368
- [x] #367

We're also investing into new features and enhancements:

- [ ] #476
- [x] #516
- [ ] #514

**Comment by lfades** [comment]
**Update**: We (the Solutions Team at Vercel) were very busy working on the Next.js Conf and haven't had the time to put more work into Commerce, and we're currently looking on expanding the team to have more hands that can help us improve Next.js Commerce

**Comment by charkour** [comment]
Understandable! We appreciate the work you and the team put into Commerce.

**Comment by patrick-mcdougle** [comment]
Is the plan to eventually continue on the 7 roadmap items listed above? Would you welcome community contributions toward that goal, or should the community sit tight until this thread is updated?

**Comment by kennyadsl** [comment]
Hello! 

We are planning to build a provider for [Solidus](https://solidus.io) and Next.js Commerce but there seem to be very few activities here, especially in terms of allowing new providers to be added.

I read that [adding new providers is on hold until there's a new API for commerce](https://github.com/vercel/commerce/blob/main/packages/commerce/new-provider.md), which seems to be [merged](https://github.com/vercel/commerce/pull/252), but as outlined in this other issue, it's not clear what should happen now, considering that, reading [this issue](https://github.com/vercel/commerce/issues/741), there seem to be still some items to complete before release V1.

That said, we are considering using Next.js Commerce as the default Next.js solution when people want to use our platform with some JS framework, but it's not clear if this is a good moment for the project to add new providers. 

On a side note, with some direction, we are probably able to contribute to the project if needed.

Can someone help us understand the plans for the project in order for us to take an informed decision? Thanks in advance! 🙏

**Comment by mtsmachado8** [comment]
any updates?

**Comment by drugan** [comment]
Can somebody tell if that project has a future at all?

Because what I see is a kind of an abandoned issue queue. The maintainer is just updating statuses at the Kanban without actually taking part in discussion ([example](https://github.com/vercel/commerce/issues/22)). Some pull requests stay without review very long time until they become outdated. 

I mean is there a sense to develop plugins for the _Next.js Commerce_ because the task does not look like as a trivial one overall.

**Comment by cond0r** [comment]
@drugan Like you can see in a previous comment, the team was busy with other internal things, like the Next.js Conf, providing many examples you can find in the Vercel Examples repo. Meanwhile, the project migrated to Turborepo, and there was a decision to make the core more solid and future-proof for accepting PR & new providers to address and avoid precisely what you mentioned. Also, there are fixes  & improvements for the things you said also.

**Comment by drugan** [comment]
@cond0r you've done an impressive work but in my mind some members of you team might be more responsive on the issue queue. At least to leave some short description when they create an issue or update the Kanban status. So we all know what is going on.

Thanks again for your work, I do greatly appreciate it!

**Comment by callmephilip** [comment]
is now a good moment to pick up this discussion? or is there maybe a better place to do this? we are currently looking into Vercel Commerce for a custom provider implementation

**Comment by leerob** [comment]
Update: We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
