### ISSUE TITLE
Pages don't display more than 12 products by default, and can never display more than 50

### ISSUE THREAD

**Issue by jordanarldt** [vercel/commerce#521]
I've found that when using the Next.js Commerce integration with BigCommerce, the site never displays more than 12 products on any page or category, despite the category/page having more than 12 products assigned to it.

It would be great if this could be fixed natively, or if there was documentation added on how to increase this hard limit set by the integration for users that are planning to set up this integration for production.

<img width="1615" alt="Screen Shot 2021-10-07 at 5 40 19 PM" src="https://user-images.githubusercontent.com/19815878/136472526-02b442ec-f0a2-4a58-8e2e-3fad1eee23cb.png">

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
