### ISSUE TITLE
I found that only 20 static pages limit for BigCommerce

### ISSUE THREAD

**Issue by chintanredefine** [vercel/commerce#530]
I am facing issue and found that there is only 20 static pages limit for BigCommerce.

Is there any way to increase the limit as the website which I am working is huge and has more than 150 static pages.

**Comment by kogan007** [comment]
Open framework/bigcommerce/api/operations/get-all-pages.ts

Look for this
```
const { data } = await cfg.storeApiFetch<
      RecursivePartial<{ data: Page[] }>
    >('/v3/content/pages')
 ```
 
 change it to 
 ```
 const { data } = await cfg.storeApiFetch<
      RecursivePartial<{ data: Page[] }>
    >('/v3/content/pages?limit=250')
```

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
