### ISSUE TITLE
[BC] Customcheckout error 

### ISSUE THREAD

**Issue by Florian-crg** [vercel/commerce#533]
I have just cloned the project and set my .env with BC then enabled customCheckout which display an error when clicking on checkout. See the picture bellow 

`TypeError: Cannot read properties of undefined (reading 'fetcher')
`

<img width="975" alt="Capture d’écran 2021-10-17 à 21 27 16" src="https://user-images.githubusercontent.com/20863963/137642085-1315b32c-0464-41c2-9f6c-2f61a67d3ca6.png">

**Comment by ReevMich** [comment]
I am getting this error as well but using Swell provider

**Comment by ReevMich** [comment]
@Florian-crg I managed to get mine working but, you have to add the `useCheckout` hook to your `provider.ts` in the BC folder.

```
export const swellProvider: Provider & { swell: any } = {
  locale: 'en-us',
  cartCookie: SWELL_CHECKOUT_ID_COOKIE,
  swell,
  fetcher,
  cart: { useCart, useAddItem, useUpdateItem, useRemoveItem },
  customer: { useCustomer },
  products: { useSearch },
  checkout: { // Added this object and hook. You will have to fill in the logic for your provider
    useCheckout,
  },

  auth: { useLogin, useLogout, useSignup },
}
```

**Comment by GodwinEbikwo** [comment]
@ReevMich should do the same thing in the Shopify folder ? having the same issue

**Comment by jackkrebsbach** [comment]
I don't think is possible to have a custom checkout out with BigCommerce.

In BigCommerce's checkout SDK docs they say that their Storefront Web API does not support CORS.
https://github.com/bigcommerce/checkout-sdk-js#cors

Unfortunately because next commerce is a headless solution I don't think you can use custom checkout with BigCommerce.

**Comment by brightonmike** [comment]
If you try the fix here https://github.com/vercel/commerce/issues/533#issuecomment-981149223 you only just get other errors further down the line. E.g. if you click into Payment Method, you get:

```
../packages/commerce/dist/utils/use-hook.js (24:0) @ useMutationHook

  22 | export function useMutationHook(hook) {
  23 |     const fetcher = useFetcher();
> 24 |     return hook.useHook({
```

You also get the same error for Shipping Method.

Getting the custom checkout to actually work therefore just feels like endless whack-a-mole.

**Comment by devlamine** [comment]
Hi I have same error : 

```
../packages/commerce/dist/utils/use-hook.js (24:0) @ useMutationHook

  22 | export function useMutationHook(hook) {
  23 |     const fetcher = useFetcher();
> 24 |     return hook.useHook({
  25 |         fetch: useCallback(({ input  } = {})=>{
  26 |             return hook.fetcher({
  27 |                 input,
```

**Comment by guibovo** [comment]
+1

**Comment by brightonmike** [comment]
I wasn't able to resolve this, we abandoned Vercel Commerce and went down a different route.

**Comment by mrth2** [comment]
up! I'm getting the same error trying to proceed checkout with shopify from the cart drawer

**Comment by valentin-harrang** [comment]
Same error

**Comment by valentin-harrang** [comment]
I think custom checkout only works with OrderCloud 😞

**Comment by adityanagar10** [comment]
Having the same issues with Saleor. Did anyone fix this issue or finally implement their own custom checkout?

**Comment by allexxis** [comment]
Same error using Shopify commerce

**Comment by David05500** [comment]
same issue with bigcommerce

**Comment by David05500** [comment]
Looks like all the hooks (useCheckout, useSubmitCheckout) for the checkout functionality are empty. Would anyone know if its something that is coming very soon, or something that we have to roll out ourselves?

**Comment by Imtiyaz94** [comment]
i got same error and unable to solve it. If anyone has resolved so can you please tell me.

**Comment by Imtiyaz94** [comment]
> i got same error and unable to solve it. If anyone has resolved so can you please tell me. And i am using Next js storefront with vendure

Why this issue has not been solved or have idea to solve yet.

**Comment by Imtiyaz94** [comment]
Why this issue has not been solved or have no idea to solve yet.

**Comment by marcabisamra** [comment]
This would be amazing if this can be addressed. This is a really wonderful project and works great otherwise, its a shame this is holding it back

**Comment by cahyawibawa** [comment]
same issue with shopify

**Comment by jitupatel76877** [comment]
Same error getting with me

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
