### ISSUE TITLE
Bike-Shedding Reasons

### ISSUE THREAD

**Issue by charkour** [vercel/commerce#545]
Thanks for this awesome starter repo. 

One thing I was wondering about were some of the tool choices for the project, specifically the choice of TailwindCSS and CSS Modules. I understand Tailwind's benefits (fixes the append only problem with CSS, etc), but why use Tailwind with CSS Modules? Documenting the reason somewhere in the repo (perhaps the readme) for this choice would be beneficial since CSS Modules seems counter to many of Tailwind's benefits.

Also documenting choices for third-party dependencies, ESLint/Prettier standards, and other bike-shedding topics would also be beneficial. Thanks.

**Comment by charkour** [comment]
Yeah, that's exactly what I've run into. However, when you use the `@apply` directive in a CSS module, it duplicates the rule set which can increase the number of bytes sent to the client for css. 

Also, using CSS modules means can component that extends a base component that uses CSS modules must also use CSS modules due to CsS precedence rules. I've found this to be confusing when styles aren't seemingly applied.

**Comment by okbel** [comment]
We really enjoyed developing with Tailwind that's why we chose it. If there are any significant perf issues with x lib we would consider removing it for sure.
