### ISSUE TITLE
CartItem Image left as unoptimized

### ISSUE THREAD

**Issue by nikushx** [vercel/commerce#549]
Hey Vercel Commerce team,

https://github.com/vercel/commerce/blob/c440ff06d43f8959d46f1789c9d1d8949c566f0a/components/cart/CartItem/CartItem.tsx

Was looking at this file and noticed this is the only image flagged with `unoptimized`.
I'm curious why this is the way it is, and why I should/shouldn't keep it in my forked branch.

Thanks!

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
