### ISSUE TITLE
EXIST ADMIN DASHBOURD?

### ISSUE THREAD

**Issue by loveyandex** [vercel/commerce#551]
ARE U DESIGN A DASHBOARD FOR ADMIN? OR U LEAVE IT FOR COMMERCE PROVIDERS

**Comment by Florian-crg** [comment]
This is not an issue. https://github.com/vercel/commerce/discussions

**Comment by ranstyr** [comment]
> This is not an issue. You may find this section more appropriate https://github.com/vercel/commerce/discussions

@Florian-crg I didn't find the related section at https://github.com/vercel/commerce/discussions
Could you please advise?
