### ISSUE TITLE
node 17.0.1 postcss-nesting@8.0.1 incompatible.

### ISSUE THREAD

**Issue by luluhoc** [vercel/commerce#556]
As in title can you please update it?
```
error postcss-nesting@8.0.1: The engine "node" is incompatible with this module. Expected version "12 - 16". Got "17.0.1"
error Found incompatible module.
```

**Comment by charkour** [comment]
I'd recommend downgrading your version of node. It doesn't look like Postcss Nesting supports Node v17 yet, plus most hosting providers only host Node v12 and v14, including Vercel.

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
