### ISSUE TITLE
Build is failing | Module '"@vercel/fetch"' has no exported member 'Response'. Did you mean to use 'import Response from "@vercel/fetch"' instead?

### ISSUE THREAD

**Issue by dejesus2010** [vercel/commerce#568]
I just pulled the repo to test out the demo and the build is failing:

$ npm run build

nextjs-commerce@1.0.0 build /Users/Temp/commerce
next build

next.config.js {
  "commerce": {
    "features": {
      "cart": false,
      "search": false,
      "wishlist": false,
      "customerAuth": false,
      "customCheckout": false
    },
    "provider": "local"
  },
  "i18n": {
    "locales": [
      "en-US",
      "es"
    ],
    "defaultLocale": "en-US"
  },
  "images": {
    "domains": [
      "localhost"
    ]
  },
  "env": {}
}
Failed to compile.

./framework/commerce/api/index.ts:2:29
Type error: Module '"@vercel/fetch"' has no exported member 'Response'. Did you mean to use 'import Response from "@vercel/fetch"' instead?

  1 | import type { NextApiHandler } from 'next'
2 | import type { FetchOptions, Response } from '@vercel/fetch'
  3 | import type { APIEndpoint, APIHandler } from './utils/types'
  4 | import type { CartSchema } from '../types/cart'
  5 | import type { CustomerSchema } from '../types/customer'
info  - Checking validity of types .npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nextjs-commerce@1.0.0 build: `next build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nextjs-commerce@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by zhaodadi** [comment]
can confirm this.
npm run dev is fine, but npm run build is giving the above error.

**Comment by zhaodadi** [comment]
Not an expert on typescript, i followed the error suggestion by
removing the Reponse import and added this:
import Response from '@vercel/fetch'

build seems fine now

BTW u also need to update the errors.ts file too (the build error will lead u to it)

**Comment by mcavady** [comment]
I confirm that this "bug" happened for me too, following the same as the above, this fixed deployement.

Steps to reproduce for me. 

Cloned - setup github deployment made some test edits and setup local dev ( all working fine )
Added in Checky ( all working fine with test commits )
Added in "analytics" from vercel side and deployment broke.


`<html>
<body>


info  - Checking validity of types...
--
04:32:43.937 | Failed to compile.
04:32:43.938 |  
04:32:43.938 | ./framework/commerce/api/utils/errors.ts:1:15
04:32:43.939 | Type error: Module '"@vercel/fetch"' has no exported member 'Response'. Did you mean to use 'import Response from "@vercel/fetch"' instead?


</body>
</html>` 

Followed @zhaodadi comments and deployment is working again :) 

Thank you @zhaodadi 👍

**Comment by AgentPoles** [comment]
thank you @zhaodadi, worked for me too!

**Comment by johnmasonwilliams** [comment]
Thank you @zhaodadi, your fix also worked for me as well.

I looked into the @vercel/fetch code and the issue is with how they are exporting the Reponse type that they import from 'node-fetch'. They are doing "export * from 'node-fetch' which is causing the error.

**Comment by jonrrivera** [comment]
are you guys able to add to cart on local? even fixing this error following @zhaodadi suggestion is still not working for me. For some add reason, I can only add to cart on the server.

**Comment by johnmasonwilliams** [comment]
Local add to cart doesn't work for me either. Might be something to do with localhost not being allowed for Shopify storefront api? No idea...> are you guys able to add to cart on local? even fixing this error following @zhaodadi suggestion is still not working for me. For some add reason, I can only add to cart on the server.
