### ISSUE TITLE
Medusa Provider

### ISSUE THREAD

**Issue by luisorbaiceta** [vercel/commerce#589]
Is there any plan to add [Medusa](https://github.com/medusajs/medusa) to the current providers? If this is something interesting for people I could send a PR

**Comment by lsalling** [comment]
Let us know if you do any progress on this. Don't use Medusa myself but would be interesting seeing a provider for this as well🙂

**Comment by christofferbjorkman** [comment]
That is a fantastic idea 👌🏼

**Comment by aecorredor** [comment]
I saw that this https://github.com/vercel/commerce/pull/486 was actually closed one day before this new issue was opened. Does anybody know what happened with #486? CC: @kasperkristensen

**Comment by aecorredor** [comment]
Nvm, this explains it https://github.com/medusajs/medusa/issues/1428.

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
