### ISSUE TITLE
Could not find docs or tutorials.

### ISSUE THREAD

**Issue by singhsimranjeetg** [vercel/commerce#59]
Hi, 

I am looking forward to use vercel/commerce for my clients' Shopify stores once its supported. Meantime, I would like to learn how API's and components works in this project so it will be easier to customize later on. Unfortunately, I couldn't find any docs or tutorial for that. Please share if someone knows any resources.

Thank you

**Comment by okbel** [comment]
Hi Simranjeet, 

We're currently working on documenting the UI, data hooks, and more.

Thanks for the feedback!

Stay tuned for more updates
