### ISSUE TITLE
Support for BigCommerce modifiers with variants

### ISSUE THREAD

**Issue by mmaaaaz** [vercel/commerce#599]
Is there any way we can support BigCommerce modifiers along with variants?

**Comment by rubri-sparrow** [comment]
Encountering the same problem, does anyone have an update on this?

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
