### ISSUE TITLE
Accept Cookies functionality

### ISSUE THREAD

**Issue by okbel** [vercel/commerce#6]

**Comment by marbiano** [comment]
@okbel did you start working on this one? If not, I'll take care of it.

**Comment by aevaldas** [comment]
Seems like this one is already done on https://demo.vercel.store/:
![image](https://user-images.githubusercontent.com/38099310/97456824-df9b5600-1941-11eb-8a1d-c5e80f02ef0e.png)

**Comment by marbiano** [comment]
@aevaldas if you click on Accept and then reload the page, you'll see the banner again. It should disappear for good once it's been accepted.

@okbel I'll take care of this one if you don't mind.
