### ISSUE TITLE
'yarn install' causes breaks where `npm install` works

### ISSUE THREAD

**Issue by ktravelet** [vercel/commerce#601]
something weird is going on and I'm just going to offload to the team :D 

yarn install, installs something strange that causes the `/// <reference types="next/types/global" />` line from `next-env.d.ts` file to be removed.  This causes some errors when running `yarn dev`.

If I use `npm install` everything will work fine.

wierd...

**Comment by charkour** [comment]
I can respond to the first aspect of your issue. Using `next` >12.0.4 causes ```///  <reference types="next/types/global" />``` to be removed. Not sure why this is the case, but my team hasn't noticed any issues since then. 

We use npm so I don't know why yarn is not working. Sorry to hear that.

**Comment by lsalling** [comment]
Was messing around with the same problem until eventually coming to the same conclusion. This should maybe be mentioned somewhere in the readme until a fix has been issued to avoid further confusion.

**Comment by okbel** [comment]
Looks like this has been fixed already!
