### ISSUE TITLE
Why does my add to cart work on remote, but not on local ?

### ISSUE THREAD

**Issue by jonrrivera** [vercel/commerce#609]
This has happened to me on all my next commerce projects. Any chance I can debug this ?

**Comment by iamthehimansh** [comment]
I also Have same Problem

**Comment by jshay21** [comment]
Same issue here with Shopify integration.  Doesn't throw of console error either.

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
