### ISSUE TITLE
Shopify wishlist implementation

### ISSUE THREAD

**Issue by chemmanouilidis** [vercel/commerce#610]
I was wandering if we can use the customer.metafields field of the shopify storefront API to create a wishlist functionality in the current commerce implementation. If so, we need to add an updateCustomer mutation and define a wishlist handler that updates the customer metafields field with a key:value pair of productId-productName and returns the metafields of the customer.

Is this doable?

**Comment by okbel** [comment]
Shopify's Storefront API doesn't support Wishlist :(
