### ISSUE TITLE
Having issue with next/dynamic

### ISSUE THREAD

**Issue by geniti** [vercel/commerce#614]
![Schermafbeelding 2021-12-16 om 10 09 47](https://user-images.githubusercontent.com/32541489/146342045-f26e028a-1492-430d-bbb4-8c6269c8a9d0.png)

**Comment by geniti** [comment]
@lfades do you know how to solve this err?

**Comment by lsalling** [comment]
There's a problem when installing dependencies using yarn right now. Use npm instead🙂

**Comment by Dooptroop** [comment]
You can get it working with yarn by updating the `Layout.tsx` files dynamic imports like so

```typescript
const Loading = () => (
  <div className="w-80 h-80 flex items-center text-center justify-center p-3">
    <LoadingDots />
  </div>
)

const SignUpView = dynamic(
  () => import('@components/auth/SignUpView'),
  {
    loading: Loading
  }
)

const ForgotPassword = dynamic(
  () => import('@components/auth/ForgotPassword'),
  {
    loading: Loading
  }
)

const FeatureBar = dynamic(
  () => import('@components/common/FeatureBar'),
  {
    loading: Loading
  }
)

const Modal = dynamic(
  () => import('@components/ui/Modal'),
  {
    loading: Loading,
    ssr: false
  }
)
```

**Comment by Dooptroop** [comment]
There is a package-lock.json commited so npm install maintains the package versions.

Running with Yarn will install slightly newer versions of the packages.

**Comment by Dooptroop** [comment]
https://github.com/vercel/commerce/pull/618

**Comment by Dooptroop** [comment]
I made a PR here https://github.com/vercel/commerce/pull/618
