### ISSUE TITLE
No email field on custom checkout form

### ISSUE THREAD

**Issue by cpv123** [vercel/commerce#616]
The custom checkout does not include a field to collect the customer's email address. This would be useful for the Commerce.js provider and likely useful for other providers using custom checkout given that collecting email is common.

Currently, there are sections for "payment" and "shipping", and so I'm not sure where is best to add the email field. I will create a PR to implement this, assuming that there are no concerns with this feature. And any suggestions for where the field should go would be much appreciated 🙏 

---

<img width="350" alt="Screenshot 2564-12-17 at 11 47 23" src="https://user-images.githubusercontent.com/35846795/146540308-3fa3efe5-51c3-4b46-893e-03260da34f77.png">

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
