### ISSUE TITLE
is vendure provider support all feature? i don't find checkout implemented

### ISSUE THREAD

**Issue by loveyandex** [vercel/commerce#619]

**Comment by okbel** [comment]
This one is for @michaelbromley

**Comment by teddybee** [comment]
Is there any ETA for this feature? I see a big "Merging is blocked" issue in the #619 PR.

**Comment by michaelbromley** [comment]
@teddybee unfortunately maintenance of this repo seems quite sporadic - there have only been a couple of minor updates in the past couple of months. The work for the Vendure custom checkout is done in PR #760, it just needs approval and merging now.

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
