### ISSUE TITLE
Somebody managed to get featured image from collection/category with Shopify?

### ISSUE THREAD

**Issue by geniti** [vercel/commerce#625]
im trying to get the image I uploaded in Shopify collection featured image

**Comment by geniti** [comment]
@lfades could you help me with this


i have created this type
export type Category = {
  id: string
  name: string
  image: CategoryImage[]
  slug: string
  path: string
}

export type CategoryImage = {
  url: string
  alt?: string
}

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
