### ISSUE TITLE
BigCommerce: login error 

### ISSUE THREAD

**Issue by ryankauk** [vercel/commerce#627]
I tried cloning and deploying the commerce repo and tried to "sign up" but right after signup during the login stage I got an error

"Operation cannot be performed as the storefront channel is not live"

I don't see any settings in BigCommerce for making the channel "live". Under manage/channel-manager the Vercel store is showing "active" and do see any docs from BigCommerce relating it to be live. Is this an integration problem?

Thanks for any help

**Comment by ryankauk** [comment]
So Vercel integration seems to have created it's own storefront under the channel manager displayed as "Next.js Commerce" there's also another one that looks like the default one (domain ending with .mybigcommerce.com) which was inactive. Once I set that to active the login worked. The env variables are populated from the integration but the BIGCOMMERCE_STOREFRONT_API_URL seems to be connected to the default one instead of the nextjs one.

**Comment by okbel** [comment]
Is this still happening? Looks like this is an issue on BigCommerce side
