### ISSUE TITLE
Error when building with commerceprovider=ordercloud

### ISSUE THREAD

**Issue by oliverheywood451** [vercel/commerce#629]
Steps to recreate: 

- Use these test values for .env.local
```
COMMERCE_PROVIDER=ordercloud
ORDERCLOUD_MARKETPLACE_ID=2DvXKzN8Chr9eXWL
ORDERCLOUD_BUYER_CLIENT_ID=59071C75-E89B-47FE-950B-BE29554C28A0
ORDERCLOUD_MIDDLEWARE_CLIENT_ID=211846D5-ACA0-4B8F-A2B1-5ECE362215C0
ORDERCLOUD_MIDDLEWARE_CLIENT_SECRET=vzI808AkKtPGmN4t9yKUBFMtwBlL9snjzHfVRwnGpR7QNqz8SZLEHqquNxzU
```
- run `npm i`
- run `npm run build`

See the error - Type error: Property 'token' does not exist on type 'Global & typeof globalThis'.

![image](https://user-images.githubusercontent.com/38010640/148095285-ab66bdcf-3f9d-46ed-858d-eb0fa9179e67.png)

**Comment by okbel** [comment]
Looks like this has been solved! Thanks for reporting Oliver!
