### ISSUE TITLE
Commerce.js wishlist missing, login & register form do not work

### ISSUE THREAD

**Issue by wlaj** [vercel/commerce#634]
Steps to reproduce

1. Navigate to https://commercejs.vercel.store/

See Commerce.js demo header missing wishlist
![chrome_YzYFGKCMLd](https://user-images.githubusercontent.com/40787982/148559662-d4802c20-3b42-40c4-88e9-ed0df62451e1.png)

Bigcommerce demo header containing wishlist
![chrome_nu54wThQFZ](https://user-images.githubusercontent.com/40787982/148559913-d7cbd099-302f-4bb0-b6d3-6665e5e2d235.png)

Login and register form do not seem to respond to the input, nor login the user.

After installing, running and setting up the project locally, the same issue seems to appear. Everything else looks to be working as normal.

**Comment by robbieaverill** [comment]
Hi @wlaj, Commerce.js does not support a wishlist so this feature will not be implemented in this repository. You can use Next.js API routes and some kind of database to create your own equivalent.

**Comment by cpv123** [comment]
@wlaj the login flow is not very clear, but I think it should work.

The first thing to note is that you can only log in using an email address that is already registered as a customer, meaning you must first create an order using the email address (which then creates the customer record). @robbieaverill correct me if this is wrong, but it seems that the login token email only sends to email addresses that already exist as "customers"?

After this, you should be able to submit the login form leaving the _password field empty_. You will then receive an email that contains a login URL (see screenshot). Clicking this URL should then redirect you back to the site but you will be logged in. However, this repo current does not contain logic for fetching the orders for authenticated customers, so even once you are logged in there is not much that can be seen.

<img width="615" alt="Screenshot 2565-01-24 at 21 15 51" src="https://user-images.githubusercontent.com/35846795/150799331-d3fc801f-10a2-48ab-ab2b-a6b10abf70e1.png">

**Comment by cpv123** [comment]
Update - the login link does not work and instead takes me to a "not found" page which means the login API route is not working as expected. I will look into this and get it fixed.

@robbieaverill @wlaj

**Comment by GodwinEbikwo** [comment]
Any update @cpv123 ??

**Comment by cpvdeveloper** [comment]
Small update here, but no fix unfortunately.

The login flow works when running locally, but doesn't work at the deployed site https://commercejs.vercel.store. Here, the login link that gets email ends up going to a 500 error page. 

But without accessing the Vercel dashboard where it's deployed, I can't see what's causing the error. The login API does rely on some env variables which may be set incorrectly in Vercel - this could possibly be the issue.

**Comment by cpv123** [comment]
Small update here, but no fix unfortunately.

The login flow works when running locally, but doesn't work at the deployed site https://commercejs.vercel.store/. Here, the login link that gets email ends up going to a 500 error page.

But without accessing the Vercel dashboard where it's deployed, I can't see what's causing the error. The login API does rely on some env variables which may be set incorrectly in Vercel - this could possibly be the issue. I will deploy the site on my own Vercel account and see if I can get it working.

**Comment by cpv123** [comment]
I've deployed my own version to Vercel and now I also get the 500 error. The full error log is
```
[GET] /api/login/a2d6e9c5-874b-4c43-938b-7a7feb7e196c
17:23:19:69
2022-02-21T10:23:19.879Z	beda8155-3c48-4e53-aa52-dda273994368	ERROR	Error: Cannot find module 'react/jsx-runtime'
Require stack:
- /var/task/site/.next/server/pages/_document.js
- /var/task/node_modules/next/dist/server/require.js
- /var/task/node_modules/next/dist/server/load-components.js
- /var/task/node_modules/next/dist/server/base-server.js
- /var/task/node_modules/next/dist/server/next-server.js
- /var/task/___next_launcher.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.997 (/var/task/site/.next/server/pages/_document.js:1041:18)
    at __webpack_require__ (/var/task/site/.next/server/webpack-runtime.js:25:42)
    at Object.2565 (/var/task/site/.next/server/pages/_document.js:947:75)
    at __webpack_require__ (/var/task/site/.next/server/webpack-runtime.js:25:42)
    at __webpack_exec__ (/var/task/site/.next/server/pages/_document.js:1051:39)
    at /var/task/site/.next/server/pages/_document.js:1052:66 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/task/site/.next/server/pages/_document.js',
    '/var/task/node_modules/next/dist/server/require.js',
    '/var/task/node_modules/next/dist/server/load-components.js',
    '/var/task/node_modules/next/dist/server/base-server.js',
    '/var/task/node_modules/next/dist/server/next-server.js',
    '/var/task/___next_launcher.js',
    '/var/runtime/UserFunction.js',
    '/var/runtime/index.js'
  ]
}
2022-02-21T10:23:19.880Z	beda8155-3c48-4e53-aa52-dda273994368	ERROR	Error: Cannot find module 'react/jsx-runtime'
Require stack:
- /var/task/site/.next/server/pages/_document.js
- /var/task/node_modules/next/dist/server/require.js
- /var/task/node_modules/next/dist/server/load-components.js
- /var/task/node_modules/next/dist/server/base-server.js
- /var/task/node_modules/next/dist/server/next-server.js
- /var/task/___next_launcher.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.997 (/var/task/site/.next/server/pages/_document.js:1041:18)
    at __webpack_require__ (/var/task/site/.next/server/webpack-runtime.js:25:42)
    at Object.2565 (/var/task/site/.next/server/pages/_document.js:947:75)
    at __webpack_require__ (/var/task/site/.next/server/webpack-runtime.js:25:42)
    at __webpack_exec__ (/var/task/site/.next/server/pages/_document.js:1051:39)
    at /var/task/site/.next/server/pages/_document.js:1052:66 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/task/site/.next/server/pages/_document.js',
    '/var/task/node_modules/next/dist/server/require.js',
    '/var/task/node_modules/next/dist/server/load-components.js',
    '/var/task/node_modules/next/dist/server/base-server.js',
    '/var/task/node_modules/next/dist/server/next-server.js',
    '/var/task/___next_launcher.js',
    '/var/runtime/UserFunction.js',
    '/var/runtime/index.js'
  ],
  page: '/api/login/a2d6e9c5-874b-4c43-938b-7a7feb7e196c'
}
RequestId: beda8155-3c48-4e53-aa52-dda273994368 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

**Comment by guibovo** [comment]
+1 on @cpv123 latest comment

**Comment by JimmyK1995** [comment]
Seems like you guys are working on the login errors. 
Is the missing wishlist up for grabs? Would love to help out.

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
