### ISSUE TITLE
[BUG] Sign up error (BigCommerce)

### ISSUE THREAD

**Issue by WebcrazyDylan** [vercel/commerce#636]
When I create an account in the nextjs storefront channel, an account is created in the default customer group of BigCommerce. 
I created an additional customer group for the nextjs storefont channel in addition to the default customer group.
But I couldn't get an account to be created in the customer group of the nextjs storefront channel.

**Comment by okbel** [comment]
Can you add more clarification?

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
