### ISSUE TITLE
Menu Side Bar does not close when clicking link

### ISSUE THREAD

**Issue by SylvainGarrigues** [vercel/commerce#643]
Title almost says it all: when using a phone, if I click the "hamburger" icon to open the side bar menu, clicking one of the items ("All", "Apparel", "Shop All") seems to have no action as it does not close the side bar menu (but I can see it does navigate to a different page if I close the menu myself)

**Comment by okbel** [comment]
Hey! We couldn't reproduce it 🤔  It could be because we fixed it already. Thank you!
