### ISSUE TITLE
[Commerce JS] Checkout Returns 404 with Cart Not Found

### ISSUE THREAD

**Issue by madusankapremaratne** [vercel/commerce#659]
CommerceJS does not allow to checkout the items, instead returns with 404. 
```
❌ HTTP ERROR [404] Type: 
index.js?6741:1 Cart with ID "cart_id" not found.
```
<img width="628" alt="Screenshot 2022-01-25 at 15 06 59" src="https://user-images.githubusercontent.com/5510460/150951043-2a6fb624-1a24-4115-978a-d7f3a148b3b2.png">

**Comment by cpv123** [comment]
@madusankapremaratne is this happening after you click "checkout"?

If so, I think that the checkout itself might actually be working, and this 404 error is just when the cart is refreshed after checkout.

<img width="600" alt="Screenshot 2565-01-26 at 07 35 01" src="https://user-images.githubusercontent.com/35846795/151083222-e5a11646-6dbf-4ada-863b-0f168ad82513.png">

**Comment by pratik9333** [comment]
Hello just a random question, can we use this layout design for our projects  @cpv123 @madusankapremaratne

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
