### ISSUE TITLE
Provider: Sylius

### ISSUE THREAD

**Issue by DnD-Magnum** [vercel/commerce#662]
Ecommerce Provider: https://sylius.com/
REST & GraphQL API are available.

**Comment by loic-carbonne** [comment]
Hello, at Theodo, we use both Sylius and NextJs Commerce, we are very interested in developing that provider !
We started some developments, we will update you in few weeks on our progress

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
