### ISSUE TITLE
just i want Frontend and with my own rpc  backend (in other language and other dunctionallity)

### ISSUE THREAD

**Issue by loveyandex** [vercel/commerce#663]
I just want nextjs commerce ui with my own backend 
where should I modify to add rpc functions in order to frontend works correctly

**Comment by charkour** [comment]
Just add your own [framework provider](https://github.com/vercel/commerce/blob/main/framework/commerce/new-provider.md).

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
