### ISSUE TITLE
Change Clothes and Accessories link href in Navbar

### ISSUE THREAD

**Issue by eric-stanley** [vercel/commerce#67]
Currently both Clothes and Accessories link in the Navbar searches for the matching word (clothes and accessories) in the product name, instead it should search for tags linked to the product.

**Comment by manovotny** [comment]
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: #966
