### ISSUE TITLE
'@vercel/commerce@^0.0.1' is not in the npm registry.

### ISSUE THREAD

**Issue by ayushmankumar7** [vercel/commerce#673]
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@vercel%2fcommerce - Not found
npm ERR! 404
npm ERR! 404  '@vercel/commerce@^0.0.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'site'

**Comment by charkour** [comment]
Try installing using yarn. The project uses yarn workspaces.

**Comment by robearlam** [comment]
I'm seeing the same error when attempting to run `npm i` from inside the 'site' folder.
