### ISSUE TITLE
postcss-nesting expecting  node  version "12 - 16"  Got "17.4.0"

### ISSUE THREAD

**Issue by nerkn** [vercel/commerce#677]
I wrote dockerfile, of course using latest node but it failed. Reason is 

> PostCSS Nesting was moved to [@csstools/postcss-plugins](https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-nesting). 

>Here is the discussion:  https://github.com/csstools/postcss-plugins/discussions/75

>yarn install v1.22.17
>[1/4] Resolving packages...
> [2/4] Fetching packages...
>error postcss-nesting@8.0.1: The engine "node" is incompatible with this module. Expected version "12 - 16". Got "17.4.0"
>error Found incompatible module.

**Comment by okbel** [comment]
We ran some updates since Feb. Is this still happening?

**Comment by jshay21** [comment]
Yes, this is still ongoing 

postcss-nesting@8.0.1: The engine "node" is incompatible with this module. Expected version "12 - 16". Got "17.8.0"

**Comment by Steenos** [comment]
Still running into this issue, got it working using
 yarn install --ignore-engines

**Comment by lack-of-gravitas** [comment]
Still occurring -- is this on the roadmap to fix?

**Comment by ellume-maneesh** [comment]
I am also getting this issue. Is this issue resolved?
