### ISSUE TITLE
[BUG] can't add any products in local env

### ISSUE THREAD

**Issue by buty619** [vercel/commerce#68]
hello @okbel  thanks for all you help but im still having same issue i already create the .ev.local file whit the key get from versel, there is something else im missing? maybe local env should be different to the once generate on versel?

<img width="1263" alt="Screen Shot 2020-10-28 at 5 13 42 PM" src="https://user-images.githubusercontent.com/36422189/97502588-6a2f8580-1941-11eb-8488-463e48147065.png">

<img width="339" alt="Screen Shot 2020-10-28 at 5 14 17 PM" src="https://user-images.githubusercontent.com/36422189/97502598-6ef43980-1941-11eb-9f6e-1ff45dca704f.png">

_Originally posted by @buty619 in https://github.com/vercel/commerce/issues/29#issuecomment-718240560_

**Comment by Sami-Az** [comment]
@buty619 have you been able to get a fix for this error ? I'm having the same error triggered with the cart request failing with a 500 status ...

**Comment by okbel** [comment]
This looks pretty weird. Could you post this here? https://github.com/bigcommerce/storefront-data-hooks Looks like it's coming from BigCommerce.

**Comment by bryandandan** [comment]
Can anybody tell me where the env values are actually being used/called in the code?
