### ISSUE TITLE
[Vendure] locale selection does not work

### ISSUE THREAD

**Issue by OlegKunitsyn** [vercel/commerce#680]
Reproduction
- go settings/global-settings in Vendure Admin, add `es` in Available languages
- go catalog/collections in Vendure Admin, add one or two in Spanish
- go storefront `/es`
- collections remain English

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
