### ISSUE TITLE
usePrice throws error with Typescript

### ISSUE THREAD

**Issue by vicasas** [vercel/commerce#685]
Using the usePrice hook doing destructuring to use `price` `basePrice` and `discount` this throws a Typescript error.

```jsx
const { price, basePrice, discount } = usePrice({
    amount: product.offerPrice,
    baseAmount: product.price,
    currencyCode: 'CLP',
  })
```

> const basePrice: any
Property 'basePrice' does not exist on type '{ price: string; basePrice: string | null; discount: string | null; } | { price: string; }'.ts(2339)

**Comment by vicasas** [comment]
@mauriciofragajr I do not understand. The error occurs precisely because of that function, since it returns two different objects and when typesript destructuring is used, it does not understand what the function returns.

**Comment by okbel** [comment]
We're going to check it! Thanks for reporting.

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
