### ISSUE TITLE
Error when deploying on Vercel Bigcommerce

### ISSUE THREAD

**Issue by GodwinEbikwo** [vercel/commerce#688]
After signing up and connecting the store, the build failed with the following error:

Error: No Output Directory named "public" found after the Build completed. You can configure the Output Directory in your Project Settings. Learn More: https://vercel.link/missing-public-directory

@lfades

**Comment by omertoast** [comment]
I'm also having the same problem

**Comment by cpv123** [comment]
@GodwinEbikwo I got this working by configuring some settings in Vercel. I've explained here: https://github.com/vercel/commerce/pull/692

**Comment by lfades** [comment]
Should be working now!

https://github.com/vercel/commerce/pull/692#issuecomment-1055863907
