### ISSUE TITLE
Shopify Abandoned Checkouts not sending email

### ISSUE THREAD

**Issue by babyPrince** [vercel/commerce#696]
Has anyone encountered issues with Shopify's Abandoned checkouts not sending emails?
I'm in touch with Shopify support and they are talking about [storefrontAccessToken](https://community.shopify.com/c/technical-q-a/abandoned-checkout-emails-not-sending/td-p/630381), but commerce doesn't use the buy SDK right? 

Any info on this would be highly appreciated.

<img width="1671" alt="Screenshot 2022-03-01 at 13 34 46" src="https://user-images.githubusercontent.com/5452135/156170055-98b64397-fc6e-4652-8f0f-f89637d6568b.png">

**Comment by okbel** [comment]
I don't think this is implemented but we can consider adding this to our roadmap. 🙌  
Just out of curiosity and to prioritize this accordingly are you using Next.js Commerce in production? We would love to feature it! Thanks.

**Comment by babyPrince** [comment]
@okbel Thanks for looking into this. Would be really nice if this is fixed in future update, makes sense to take advantage of the marketing part. 

Re production, we are about to relaunch towards the end of the month. Once online, i'll send you a message with the link :)

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
