### ISSUE TITLE
Auto clone and deploy failed with peer dependencies unmet

### ISSUE THREAD

**Issue by rt3me** [vercel/commerce#700]
I tried to run the clone and deploy and connect Shopify and the deploy failed. There were errors about unmet peer dependencies and output directory not existing.

**Comment by rt3me** [comment]
I tried again today and noticed that adding an integration for Shopify is no longer an option in the clone and deploy. Could there be an issue with the Shopify integration?

**Comment by caleblawrence** [comment]
I'm seeing the same issue: 
```
Error: No Output Directory named "public" found after the Build completed. You can configure the Output Directory in your Project Settings. Learn More: https://vercel.link/missing-public-directory
```

**Comment by okbel** [comment]
Taking a look!

**Comment by francispham** [comment]
Hi, I couldn't create any e-commerce app from the temple. I got the loading icon with `Failed to load data, retrying...`.

![Screen Shot 2022-03-20 at 4 28 30 PM](https://user-images.githubusercontent.com/32145268/159190702-108d5bd1-3c19-46f5-9b94-deb4a44c1764.png).

I don't know if this is related to the issue here?

**Comment by oven-one** [comment]
Same issue here: ```No Output Directory named "public" found after the Build completed.```

If it helps at all in debugging, changing the output directory in app settings to something like ```site/public``` allows the build to complete successfully and the app to deploy, but obviously loading the app then loads from ```site/public``` where there's nothing but images and other static assets.

**Comment by jshay21** [comment]
Having this same issue with a Shopify install

"There were errors about unmet peer dependencies and output directory not existing"

**Comment by fullstack-overkill** [comment]
Having the same problem.

Anyone managed to get it working?

**Comment by JakeSc** [comment]
Hitting the same issue on a fresh Commerce deploy with no integrations. A little frustrating seeing the demo app not work out of the box.

**Comment by cond0r** [comment]
@JakeSc If you are not using the integration please be sure that the Build & Development Settings & Root Directory settings under Project -> Settings -> General look like this. 

<img width="922" alt="Screen Shot 2022-08-12 at 8 30 22 AM" src="https://user-images.githubusercontent.com/1243434/184290697-2eda9580-57bd-421a-b153-379e687d100d.png">

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
