### ISSUE TITLE
local version without cart, auth etc?

### ISSUE THREAD

**Issue by mxcdh** [vercel/commerce#711]
Hi

I installed local version (COMMERCE_PROVIDER=@vercel/commerce-local), but I see that this version doesn't have cart, auth etc.  How I can run cart, auth on local version?

Actuall version:
![image](https://user-images.githubusercontent.com/98115983/158227757-323e5c2e-29de-459c-aecd-77998aa32606.png)

**Comment by okbel** [comment]
Hey! Local version only supports catalog viewing. We're going to consider it after the core update! I'll add it to the ROADMAP

**Comment by maburzynski** [comment]
@okbel, what you consider? I think that super option will bee - full working 
e-commerce backend in next, what you think about it?

**Comment by mxcdh** [comment]
@okbel  what do you consider?
It's very helpful will be fully working e-commerce-backend in next.js, what do you think about it?
