### ISSUE TITLE
[VENDURE] how to efficiently query a graphql backend based on needed data

### ISSUE THREAD

**Issue by biclighter81** [vercel/commerce#715]
Hello together,
I'm using the vendure backend for handling my shop logic. After implementing a few new checkout query hooks I noticed a potential approach mistake by myself. The activeCustomer query of the vendure backend returns beside customer metadata like firstname, name, phone, etc. also all completed, failed and active orders (and a lot more). It would be possible to create an order overview just using the useCustomer hook. If i additionally add order items and some other sub selects to the graphql statement, the json backend response gets huge. But at some places in my application I just need a few of these datas. In my opinion this approach  (fetching always everything) completely abuses the idea behind graphql. Can somebody tell me their approach for keeping graphql responses small? Should I create hooks for every sub select (f.e. useCustomerAddress, useOrders, useOrderLines, useProductVariants, etc.).

Thank you,
sincerely Moritz

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
