### ISSUE TITLE
[SHOPIFY] update image when variant changes

### ISSUE THREAD

**Issue by GodwinEbikwo** [vercel/commerce#718]
Hi, currently changing variants in this shop I am building and the image does not reflect the chosen variant. Any help on how to. move forward.
Thanks

**Comment by okbel** [comment]
This in our roadmap and it's currently under progress.

**Comment by GodwinEbikwo** [comment]
Cheers for the feedback

**Comment by drugan** [comment]
Is not this issue a duplicate of the #22

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
