### ISSUE TITLE
[Shopify] Webpack Error whilst trying to add new API operation

### ISSUE THREAD

**Issue by oliverjarvis** [vercel/commerce#720]
I'm trying to get a sense of how to add an API operation, which I've been doing by simply duplicating the getAllProducts api operation, and renaming it very smartly to getAllProducts2. So I'm sure there are many places where this could have gone wrong.
I am however pretty stumped.

<img width="980" alt="image" src="https://user-images.githubusercontent.com/40406126/159932313-01bc3209-10ec-4d19-bfd2-e65877a95faf.png">

I wish I could give more context. Alternatively I'd love if you could provide a more straightforward guide for adding new operations.

**Comment by oliverjarvis** [comment]
I figured out it must have something to with not appearing in the commerce api.
<img width="586" alt="image" src="https://user-images.githubusercontent.com/40406126/159943067-8188ecc9-81e5-4b82-8ccc-9198cbe5fd65.png">


However as you can see I have definitely have it present in my operations.ts file

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
