### ISSUE TITLE
Upgrade to React 18

### ISSUE THREAD

**Issue by SebHex** [vercel/commerce#725]
## Useful links

- [React changelog](https://github.com/facebook/react/blob/main/CHANGELOG.md)
- [React 18 upgrade guide](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html)
- [React 18 blog post](https://reactjs.org/blog/2022/03/29/react-v18.html)

**Comment by wimsikal** [comment]
In React 18, there is a breaking change of types with the [Removal of Implicit Children](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210).

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966

(It covers upgrading to React 18)
