### ISSUE TITLE
[SHOPIFY] Define nested categories for proucts

### ISSUE THREAD

**Issue by DanielePancottini** [vercel/commerce#730]
Hello,
I need to define an hierarchy of categories for products in shopify, is this functionality supported by this starter kit ?
How I can solve this problem?
Thanks to all for support

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
