### ISSUE TITLE
yarn run dev is not working 

### ISSUE THREAD

**Issue by devnajam** [vercel/commerce#732]
yarn run dev
yarn run v1.22.18
$ turbo run dev
• Packages in scope: @vercel/commerce, @vercel/commerce-bigcommerce, @vercel/commerce-commercejs, @vercel/commerce-kibocommerce, @vercel/commerce-local, @vercel/commerce-ordercloud, @vercel/commerce-saleor, @vercel/commerce-shopify, @vercel/commerce-spree, @vercel/commerce-swell, @vercel/commerce-vendure, next-commerce, taskr-swc
• Running dev in 13 packages
@vercel/commerce-swell:dev: cache miss, executing 369355c6aae2fd58
next-commerce:dev: cache miss, executing 84bfc33760fdf5f1
@vercel/commerce-spree:dev: cache miss, executing cae9e02ae640a7a7
@vercel/commerce-vendure:dev: cache miss, executing 52c13fcf5ba30dac
@vercel/commerce-ordercloud:dev: cache miss, executing 58e0c6bc1647f90d
@vercel/commerce-bigcommerce:dev: cache miss, executing e68c165024c85074
@vercel/commerce-local:dev: cache miss, executing ed77d1899a2860ea
@vercel/commerce:dev: cache miss, executing 5eefe2687b22310b
@vercel/commerce-commercejs:dev: cache miss, executing 3aa1d95d9d0db027
@vercel/commerce-shopify:dev: cache miss, executing 3f1b4684525f7ea6
@vercel/commerce-vendure:dev: $ taskr
@vercel/commerce-spree:dev: $ taskr
next-commerce:dev: $ next dev
@vercel/commerce-bigcommerce:dev: $ taskr
@vercel/commerce:dev: $ taskr
@vercel/commerce-commercejs:dev: $ taskr
@vercel/commerce-swell:dev: $ taskr
@vercel/commerce-ordercloud:dev: $ taskr
@vercel/commerce-local:dev: $ taskr
@vercel/commerce-shopify:dev: $ taskr
@vercel/commerce-spree:dev: [14:41:50] Running with D:\Code\Job\nft-store\packages\spree\taskfile.js
@vercel/commerce-spree:dev: [14:41:50] Starting default
@vercel/commerce-spree:dev: [14:41:50] Starting build
@vercel/commerce-spree:dev: [14:41:50] build failed because task.source(...).swc is not a function
@vercel/commerce-spree:dev: [14:41:50] default failed because task.source(...).swc is not a function
@vercel/commerce-spree:dev: Task chain was aborted!
next-commerce:dev: ready - started server on 0.0.0.0:3000, url: http://localhost:3000
next-commerce:dev: info  - Loaded env from D:\Code\Job\nft-store\site\.env.local
@vercel/commerce-vendure:dev: [14:41:50] Running with D:\Code\Job\nft-store\packages\vendure\taskfile.js
@vercel/commerce-vendure:dev: [14:41:50] Starting default
@vercel/commerce-vendure:dev: [14:41:50] Starting build
@vercel/commerce-vendure:dev: [14:41:50] build failed because task.source(...).swc is not a function
@vercel/commerce-vendure:dev: [14:41:50] default failed because task.source(...).swc is not a function
@vercel/commerce-bigcommerce:dev: Task chain was aborted!
@vercel/commerce-vendure:dev: Task chain was aborted!
@vercel/commerce-bigcommerce:dev: [14:41:50] Running with D:\Code\Job\nft-store\packages\bigcommerce\taskfile.js
@vercel/commerce-bigcommerce:dev: [14:41:50] Starting default
@vercel/commerce-bigcommerce:dev: [14:41:50] Starting build
@vercel/commerce-bigcommerce:dev: [14:41:50] build failed because task.source(...).swc is not a function
@vercel/commerce-bigcommerce:dev: [14:41:50] default failed because task.source(...).swc is not a function
@vercel/commerce-swell:dev: [14:41:50] Running with D:\Code\Job\nft-store\packages\swell\taskfile.js
@vercel/commerce-swell:dev: [14:41:50] Starting default
@vercel/commerce-swell:dev: [14:41:50] Starting build
@vercel/commerce-swell:dev: [14:41:50] build failed because task.source(...).swc is not a function
@vercel/commerce-swell:dev: [14:41:50] default failed because task.source(...).swc is not a function
@vercel/commerce-commercejs:dev: [14:41:50] Running with D:\Code\Job\nft-store\packages\commercejs\taskfile.js
@vercel/commerce-commercejs:dev: [14:41:50] Starting default
@vercel/commerce-commercejs:dev: [14:41:50] Starting build
@vercel/commerce-commercejs:dev: [14:41:50] build failed because task.source(...).swc is not a function
@vercel/commerce-commercejs:dev: [14:41:50] default failed because task.source(...).swc is not a function
@vercel/commerce-swell:dev: Task chain was aborted!
@vercel/commerce-commercejs:dev: Task chain was aborted!
@vercel/commerce:dev: [14:41:50] Running with D:\Code\Job\nft-store\packages\commerce\taskfile.js
@vercel/commerce:dev: [14:41:50] Starting default
@vercel/commerce:dev: [14:41:50] Starting build
@vercel/commerce:dev: Task chain was aborted!
@vercel/commerce:dev: [14:41:50] build failed because task.source(...).swc is not a function
@vercel/commerce:dev: [14:41:50] default failed because task.source(...).swc is not a function
@vercel/commerce-local:dev: Task chain was aborted!
@vercel/commerce-bigcommerce:dev: error Command failed with exit code 1.
@vercel/commerce-bigcommerce:dev: [14:41:50] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@vercel/commerce-spree:dev: error Command failed with exit code 1.
@vercel/commerce-spree:dev: [14:41:50] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@vercel/commerce-local:dev: [14:41:50] Running with D:\Code\Job\nft-store\packages\local\taskfile.js
@vercel/commerce-local:dev: [14:41:50] Starting default
@vercel/commerce-local:dev: [14:41:50] Starting build
@vercel/commerce-local:dev: [14:41:50] build failed because task.source(...).swc is not a function
@vercel/commerce-local:dev: [14:41:50] default failed because task.source(...).swc is not a function
@vercel/commerce-vendure:dev: error Command failed with exit code 1.
@vercel/commerce-vendure:dev: [14:41:50] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@vercel/commerce-bigcommerce:dev: Error: command finished with error: exit status 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

![image](https://user-images.githubusercontent.com/63273965/162624911-e27e27e0-5943-4024-80d0-25d9a340ec4e.png)

**Comment by devnajam** [comment]
I have set the env variables for commerce js, it was working before but stopped working when recloned the project

**Comment by dominiksipowicz** [comment]
@devnajam can you try `yarn build` in the root directory before you run `yarn dev` and check the result.

**Comment by MostlyWhat** [comment]
Can confirm that doing `yarn build` in the root dir before `yarn dev` works on mine.

**Comment by devnajam** [comment]
I installed Linux and it worked there, the problem i think is with how
paths with in windows vs Linux based systems, next commerce is not properly
configured to work in windows env

**Comment by MostlyWhat** [comment]
I'm on windows btw.

**Comment by devnajam** [comment]
It is going to be very helpful for me if you can tell me your development
setup, i can't even run the code when i clone the repo and run it without
making any changes, it gives me module not found error and if not that then
it gives task.swc is not a function. I can share exact errors with you if
you need them to help, thanks

**Comment by dominiksipowicz** [comment]
@devnajam can you try now on Windows please after #728 PR was merged. I have the feeling this should solve your problem.

**Comment by tuncatunc** [comment]
I'm using WSL 2 on windows and it works great.

**Comment by devnajam** [comment]
You mean your code, git and node is installed on Linux subsystem and
everything else on windows, can you tell me about your workflow if that is
fine. Thanks a lot

**Comment by tuncatunc** [comment]
https://www.omgubuntu.co.uk/how-to-install-wsl2-on-windows-10?amp

**Comment by shixin-guo** [comment]
in your project, do you have this package 'packages/taskr-swc' ? 
and check '  "taskr-swc": "^0.0.1" in your package-lock file
@devnajam

**Comment by omerfe** [comment]
Building then starting the server didn't work for me anybody solved this?

**Comment by tuncatunc** [comment]
Which OS are you using?

**Comment by hoangbaovu** [comment]
I'm having the same issue

I first clone project:

Error: Couldn't find package "taskr-swc@^0.0.1" required by "@vercel/commerce@0.0.1" on the "npm" registry.

yarn version 1.22.17
Macos M1 12.4

**Comment by devnajam** [comment]
Okaay let me try

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
