### ISSUE TITLE
Cart API usage for Shopify

### ISSUE THREAD

**Issue by leeuwisarvin** [vercel/commerce#740]
Hi all,

I'm preparing a Flash Sale for a client. I wrote Shopify and asked what the considerations are that I should be aware of. One major thing that they talked about was to use the Cart API instead of the Checkout API: _What you should be using is the cart flow which we announced at Unite. Here is a link: https://shopify.dev/custom-storefronts/cart during a flash sale the cart flow will redirect users to a checkout queue if necessary under high amount of load and is not subject to the hard checkout throttle mentioned above._

Are you guys familiar with this? And how can I integrate this?

Please let me know,

Arvin

**Comment by leeuwisarvin** [comment]
@cond0r How stable is your previous PR request? https://github.com/vercel/commerce/pull/438/files

**Comment by cond0r** [comment]
@leeuwisarvin it was working / stable at the time. I closed that one because I was doing a workaround for the wishlist implementation using the same Cart API for quickly adding to the wishlist (from the grid view), but since it was not aligned with the other providers, as you might see in the comments there decided to close it.

**Comment by leeuwisarvin** [comment]
> @leeuwisarvin it was working / stable at the time. I closed that one because I was doing a workaround for the wishlist implementation using the same Cart API for quickly adding to the wishlist (from the grid view), but since it was not aligned with the other providers, as you might see in the comments there decided to close it.

@cond0r I'll try it out next week. Are you still active on Twitter?

**Comment by funkoff** [comment]
@cond0r Is there any news for the cart API implementation? I need that for subscriptions.

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
