### ISSUE TITLE
Update provider documentation

### ISSUE THREAD

**Issue by fewieden** [vercel/commerce#741]
I was reading through the documentation in order to figure out how to add a new provider.

I found two places that refer to a big change https://github.com/vercel/commerce/pull/252:
- https://github.com/vercel/commerce/blob/main/packages/commerce/new-provider.md#adding-a-new-commerce-provider
- https://github.com/vercel/commerce/blob/main/packages/commerce/README.md#commerce-api

Since the PR was already merged in June last year the documentation should be updated.

Are only the references to the PR outdated or does the whole integration documentation need an update?

**Comment by callmephilip** [comment]
i've stumbled upon the same comment. could anybody from Vercel confirm if the comment is in fact outdated at this point and we can assume that we can add new custom providers?

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
