### ISSUE TITLE
Unable to connect to shopify development store

### ISSUE THREAD

**Issue by siliconchild** [vercel/commerce#742]
I created a Shopify partner account and subsequently made a development store. Shopify password protects the store to prevent abuse. The issue I'm facing is when spinning up a dev server it error's out saying shopify site is password protected,  Please let me knowhow to make next commerce work with a Shopify development store.
Thank You

**Comment by gnacoding** [comment]
Please provide more Info. A password-protected Shopify-Storefront shouldn't affect using the dev environment. 
Have you created the API keys in the App Section of Shopify?

**Comment by davebeauchemin** [comment]
I got the same problem and removing the _https://_ part in NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN solved the issue.

**Comment by MyArgan** [comment]
> I got the same problem and removing the _https://_ part in NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN solved the issue.

Thanks a lot for sharing this.

**Comment by leerob** [comment]
Hey there! Thank you for opening this issue. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
