### ISSUE TITLE
Configuring https://commercejs.vercel.store/ 

### ISSUE THREAD

**Issue by abhi-turbo** [vercel/commerce#752]
Hi @okbel Is there any guide available for configuring `@vercel/commerce-commercejs` provider for https://commercejs.vercel.store/ I tried deploying and updating the .env but it's not working. A step by step guide will be very helpful 🙏

**Comment by LeonXu260** [comment]
Same here, I am having some trouble with CommerceJS. I think the first part is straight forward, go to commercejs.com and register for an account. You should see the API Key after you've created the store and the account. But I am unsure about the deployment url, it is the storefront?

**Comment by MostlyWhat** [comment]
same here

**Comment by okbel** [comment]
Hey folks!

We're planning a Nextra site for the docs of Next.js Commerce. 🔜 

Here are the instructions for Commerce.js (check the readme): https://github.com/vercel/commerce/pull/548#issue-1036871335

**Comment by leerob** [comment]
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
