### ISSUE TITLE
attributes not available in graphql requests for shopify

### ISSUE THREAD

**Issue by Si-Oz** [vercel/commerce#763]
When I copy the query which works in shopify Graphiql app. Many of the attributes that are available in shopify graph ql do not work when I  query through the framework. 

Field 'ruleSet' doesn't exist on type 'CollectionEdge'
  3 | export function getError(errors: any[] | null, status: number) {
  4 |   errors = errors ?? [{ message: 'Failed to fetch Shopify API' }]
> 5 |   return new FetcherError({ errors, status })
    |         ^
  6 | }

When i change the CollectionEdge type in the schema to include the attribute it still doesn't work

**Comment by cond0r** [comment]
@Si-Oz commerce uses the Storefront API https://shopify.dev/api/storefront/2022-07/objects/collection
The field you tried on GraphiQL was from Admin API.
