### ISSUE TITLE
Show all products in collection from useSearch hook

### ISSUE THREAD

**Issue by jonrrivera** [vercel/commerce#766]
Hi All,

I am looking to show all the products within a collection. Currently using the out of the box `useSearch` hook. But looking to show all products similarly to 

`
commerce.getAllProducts({
    variables: { first: 1 },
    config,
    preview,
  })
`

would love any help, thanks!!

**Comment by drugan** [comment]
I wonder what you mean by a "collection": product category or brand (designer)?

**Comment by DennisKraaijeveld** [comment]
Product category I assume. I have the same question :)

**Comment by leerob** [comment]
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
