### ISSUE TITLE
Facebook Messenger Chat Plugin CSS broken

### ISSUE THREAD

**Issue by aecorredor** [vercel/commerce#769]
I followed https://github.com/vercel/next.js/pull/35764 to integrate the facebook messenger chat plugin into my Next.js commerce website, and it works, but the CSS is broken:

<img width="418" alt="Screen Shot 2022-06-11 at 7 56 59 PM 1" src="https://user-images.githubusercontent.com/9114987/173208693-c8e71bfc-bffc-4468-979b-78e2b8305725.png">
<img width="418" alt="Screen Shot 2022-06-11 at 7 56 59 PM" src="https://user-images.githubusercontent.com/9114987/173208694-6a2d87d6-ca6c-4a15-958e-bedc722d948b.png">
<img width="435" alt="Screen Shot 2022-06-11 at 7 56 17 PM" src="https://user-images.githubusercontent.com/9114987/173208695-07881696-5ae8-46eb-9a37-5e09d9e98efe.png">

**Comment by okbel** [comment]
Hey, this doesn't appear to be related to Next.js Commerce.
Closing as this is not related to Next.js Commerce.
