### ISSUE TITLE
Server Error: Image is missing required "src" property.

### ISSUE THREAD

**Issue by leahtard** [vercel/commerce#79]
When first running `yarn dev` after build, I was seeing the following error:

```
Server Error
Error: Image is missing required "src" property. Make sure you pass "src" in props to the `next/image` component. Received: {"width":540,"height":540,"quality":"85"}
```

This occurred because I connected to an existing BigCommerce sandbox -- as opposed to creating a new site on creation. In this sandbox, I had a few products without any images which were causing this error. It would be great if the commerce package could account for this. 

My proposal:
1. Filter out products from the Grid displays on the homepage when they do not have images.
2. Provide a placeholder/fallback image for the ProductCard.

Cheers, Leah

**Comment by leahtard** [comment]
I get this a try in this PR: https://github.com/vercel/commerce/pull/80

**Comment by okbel** [comment]
This is great!!! Thank you. _checking_
