### ISSUE TITLE
Docs: How to create new hooks?

### ISSUE THREAD

**Issue by guibovo** [vercel/commerce#818]
### What is the improvement or update you wish to see?

I'd love to see more detailed information on how to create new hooks in this project.

### Is there any context that might help us understand?

I'm trying to create a hook to fetch a single product data on the front-end to be able to use it together with page builders. But I was not able to find documentation or guidance on how to do this in this project

**Comment by cond0r** [comment]
@guibovo what is the provider you are using?

**Comment by guibovo** [comment]
I'm using Shopify.

I've tried to create one based on useSearch but no success, I'm getting "TypeError: hook.useHook is not a function"

So far I've created:

GetProductHook type on commerce/src/types/product.ts
```
...
export type GetProductHook<T extends ProductTypes = ProductTypes> = {
  data: { product: T['product'] }
  input: T['getProductBody']
  fetcherInput: T['getProductBody']
}
```

use-product.tsx on commerce/src/product/use-product.tsx
```
import { useHook, useSWRHook } from '../utils/use-hook'
import { SWRFetcher } from '../utils/default-fetcher'
import type { GetProductHook } from '../types/product'
import type { HookFetcherFn, SWRHook } from '../utils/types'
import type { Provider } from '..'

export type UseProduct<
  H extends SWRHook<GetProductHook<any>> = SWRHook<GetProductHook>
> = ReturnType<H['useHook']>

export const fetcher: HookFetcherFn<GetProductHook> = SWRFetcher

const fn = (provider: Provider) => provider.products?.useProduct!

const useProduct: UseProduct = (input) => {
  const hook = useHook(fn)
  return useSWRHook({ fetcher, ...hook })(input)
}

export default useProduct
```

and on Shopify shopify/src/use-product.tsx
```
import { SWRHook } from '@vercel/commerce/utils/types'
import useProduct, { UseProduct } from '@vercel/commerce/product/use-product'
import { getProductQuery, normalizeProduct } from '../utils'
import { GetProductBySlugQuery, Product as ShopifyProduct, } from '../../schema'
import { GetProductHook } from '@vercel/commerce/types/product'

export default useProduct as UseProduct<typeof handler>

export const handler: SWRHook<GetProductHook> = {
  fetchOptions: {
    query: getProductQuery, 
  },
  async fetcher({ input, options, fetch }) {
    const { slug } = input
    const data = await fetch<GetProductBySlugQuery>({
        ...options,
        variables: { slug },
      })
    return { product : normalizeProduct(data?.productByHandle as ShopifyProduct) }
  },
  useHook:
    ({ useData }) =>
    (input) => {
      return useData({
        input: [
            ['slug', input.slug]
        ],
        swrOptions: {
          revalidateOnFocus: false,
          ...input?.swrOptions,
        },
      })
    },
}
```

I've also added the useProduct to commerce/src/index.tsx
```
...
useProduct?: SWRHook<Product.GetProductHook>
```

**Comment by cond0r** [comment]
@guibovo I suggest a simpler solution like this:

Install swr on the site folder.
`yarn add swr`

then you create a hook in site/lib/hooks/ useProduct.ts

```
import useSwr from 'swr'
import shopifyFetcher from '@vercel/commerce-shopify/fetcher'
import { normalizeProduct } from '@vercel/commerce-shopify/utils/normalize'
import getProductQuery from '@vercel/commerce-shopify/utils/queries/get-product-query'

import type { Product } from '@vercel/commerce/types/product'

interface ProductVariables {
  slug: string
}

const fetcher = (slug: string) =>
  shopifyFetcher({
    query: getProductQuery,
    variables: {
      slug,
    },
  }).then(({ productByHandle }: any) => normalizeProduct(productByHandle))

const useProduct = (slug: string) =>
  useSwr<Product, ProductVariables>(['product', slug], () => fetcher(slug))

export default useProduct`
```

Then in your component

```
import useProduct from '@lib/hooks/useProduct'

export default function Product() {
  const { data } = useProduct('example-slug')

  if (!data) return <span>Loading...</span>

  return <span>{data.name}</span>
}
```

**Comment by guibovo** [comment]
Thanks @cond0r this will work for now ((:

But my idea was to keep this new hook abstract/ecommerce agnostic as the useSearch i.e.

Is that something in the roadmap for the next commerce?

Also - Since I've forked the project and I'm working on top of it to create something that the company I work needs, do you have any suggested way to keep my fork up to date with the original project without *much* trouble?

**Comment by cond0r** [comment]
@guibovo the primary concern why I suggested the more straightforward approach was not to edit the provider's folders, especially the commerce folder, if you do not intend to create a PR. There are plans to make the core more extensible, and something like that is valuable.

If you make changes in the site folder, you are safe. The site folder doesn't change much with a severe breaking change
