### ISSUE TITLE
Add starter settings for Jest

### ISSUE THREAD

**Issue by marceloF5** [vercel/commerce#83]
Hey guys, I saw that this project doesn't have any unit tests. So I'd like to contribute to the unit test and I created this PR https://github.com/vercel/commerce/pull/82 in order to apply the starter settings with jest and react testing library.

**Comment by okbel** [comment]
Thank you!!! Checking

**Comment by lfades** [comment]
Although we like the idea of unit testing, it doesn't enough value for us at the moment, in the future we might start exploring different testing strategies, but for the moment we are not thinking about doing unit testing.
