### ISSUE TITLE
Docs: The template file has Dropdown UI issue 

### ISSUE THREAD

**Issue by blueice930** [vercel/commerce#854]
### What is the improvement or update you wish to see?

For using the lib _@radix-ui/react-dropdown-menu_, the Dropdown.tsx file should make the following change to display correctly:

`
<DropdownMenu.Portal>
      // original content
</DropdownMenu.Portal>
`

Without wrapping it, the dropdown menu will float to the left and hard to debug through css styles.

### Is there any context that might help us understand?

`site/components/ui/Dropdown/Dropdown.tsx`
For any component that using dropdown.

**Comment by MostlyWhat** [comment]
I've experienced that issue on my website. Hopefully this gets patched.

**Comment by samcxps** [comment]
In file `UserNav.module.scss` change 

`
.item:hover {
  @apply text-accent-6 transition scale-110 duration-100;
}
`

to

`
.item:hover {
  @apply text-accent-6 transition;
}
`

for a temporary fix

**Comment by pinpontitit** [comment]
> In file `UserNav.module.scss` change
> 
> `.item:hover { @apply text-accent-6 transition scale-110 duration-100; }`
> 
> to
> 
> `.item:hover { @apply text-accent-6 transition; }`
> 
> for a temporary fix

It works, but only on large screen. On small screen, the dropdown is hidden behind the right side of screen and you can't access it.

**Comment by omertoast** [comment]
I'm not a front-end expert but I found a temporary solution for small screens i.e. phones. @dylandea 

Go to `CustomerMenuContent.module.css`

Change this
```
.root {
  @apply inset-0 fixed;
  left: 72px;
  z-index: 10;
  height: 100vh;
  min-width: 100vw;
  transition: none;
}
```
to this
```
.root {
  @apply inset-0;
  left: 72px;
  z-index: 10;
  height: 100vh;
  min-width: 100vw;
  transition: none;
}
```

**Comment by sitch** [comment]
Push this fix to main?

**Comment by leerob** [comment]
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
