### ISSUE TITLE
Product route returns 500 when product is not found

### ISSUE THREAD

**Issue by slackerzz** [vercel/commerce#879]
### Describe the feature you'd like to request

Since the addition of `with-operation-callback.ts` when a product is not found the route returns a 500 error.

For example https://demo.vercel.store/product/not-a-product-slug

An Error is thrown at https://github.com/vercel/commerce/blob/6c2610584de973f90777defc0f5daa94330b5335/packages/commerce/src/api/utils/with-operation-callback.ts#L17 and it comes from a failed validation at: https://github.com/vercel/commerce/blob/6c2610584de973f90777defc0f5daa94330b5335/packages/commerce/src/api/utils/with-operation-callback.ts#L24

The problem here seems to be that when a product is not found `data.product` is undefined

### Describe the solution you'd like

When a product is not found the route should return a 404

### Describe alternatives you've considered

I've considered to wrap al the code in `site/pages/product/[slug].ts` in a try catch but it's cleaner to change https://github.com/vercel/commerce/blob/6c2610584de973f90777defc0f5daa94330b5335/packages/commerce/src/api/utils/with-operation-callback.ts#L24 to 
```ts
productSchema.nullable().parse(data.product ?? null)
```

**Comment by cond0r** [comment]
@slackerzz Thank you for reporting. The error will be thrown either way on the product page `pages/product/[slug].ts`.

<img width="540" alt="CleanShot 2022-11-18 at 07 54 24@2x" src="https://user-images.githubusercontent.com/1243434/202631104-5c87a0a9-8f60-4f55-9010-5fe8ef48644a.png">

A PR will be opened soon, which will improve by returning `notFound: true`, resulting in a 404.

**Comment by slackerzz** [comment]
@cond0r you're right, in the project I'm working on I've already replaced this lines with:
```ts
if (!product) {
    return {
      notFound: true,
    }
  }
```

I've updated my pull request
