### ISSUE TITLE
Login not working with BigCommerce

### ISSUE THREAD

**Issue by slackerzz** [vercel/commerce#888]
### Describe the feature you'd like to request

After [this](https://github.com/vercel/commerce/commit/c75b0fc0012b2c31c40c6b1584b1a72c0dbeea7f) commit the login stopped working with BigCommerce.

The problem seems to be in https://github.com/vercel/commerce/blob/main/packages/bigcommerce/src/api/endpoints/login/login.ts where a new Response is returned and not the one manipulated in https://github.com/vercel/commerce/blob/main/packages/bigcommerce/src/api/operations/login.ts with the `Set-Cookie` header.

After a signup the `SHOP_TOKEN` cookie is correctly set in the client, but every call to `/api/commerce/customer` return 404, so I believe that the changes at
https://github.com/vercel/commerce/blob/main/packages/bigcommerce/src/api/endpoints/customer/get-logged-in-customer.ts#L33-L39
introduced a regression

### Describe the solution you'd like

To be able to login

### Describe alternatives you've considered

none

**Comment by cond0r** [comment]
@slackerzz Thank you for reporting, I will investigate this.

**Comment by leerob** [comment]
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
