### ISSUE TITLE
Sitecore Ordercloud, CommerceJS - User authentication not working

### ISSUE THREAD

**Issue by C-EO** [vercel/commerce#916]
### Describe the feature you'd like to request

I have a problem with the Vercel - Ordercloud intergration

For some unknown reason the site auth doesn't work and I don't know why

Please help

Also it would be great if this repo had a bug report template

### Describe the solution you'd like

A detailed documentation on how to fix this issue.

### Describe alternatives you've considered

None

**Comment by cond0r** [comment]
Hello. @C-EO, the auth is not yet implemented on the Ordecloud provider.

**Comment by C-EO** [comment]
@cond0r So does that mean that the wishlist feature for the Ordercloud deployment is also useless untill implemented?

**Comment by cond0r** [comment]
> @cond0r So does that mean that the wishlist feature for the Ordercloud deployment is also useless untill implemented?

What is marked as false in the provider commerce.confing.js is not implemented yet or is unavailable for that provider.

**Comment by C-EO** [comment]
> > @cond0r So does that mean that the wishlist feature for the Ordercloud deployment is also useless untill implemented?
> 
> What is marked as false in the provider commerce.confing.js is not implemented yet or is unavailable for that provider.

I switched to CommerceJS
Now in the `commerce.config.js` file, `auth` is set to true, yet on the deployment, it doesn't work.

Reference: https://github.com/vercel/commerce/blob/main/packages/commercejs/src/commerce.config.json

**Comment by leerob** [comment]
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
