### ISSUE TITLE
Will this project be exposed as a npm module?

### ISSUE THREAD

**Issue by dohomi** [vercel/commerce#92]
Hey Guys,

is this project meant to be a NextJS template or will there be a npm module which would expose all the components and apis? As a template with such a complexity it will be difficult to keep track of changes over the time.

Thanks

**Comment by okbel** [comment]
Thanks for reaching out! I'd love to but this was initially intended as a starter. We're abstracting most of the functionality to commerce-framework. Will update all soon.

**Comment by hichana** [comment]
@okbel how would you recommend someone incrementally adopt the changes/features you are building? I get it that this is intended to be a starter, but even as such there would be a huge benefit in taking advantage of them as they are rolled out. Like would one simply use the starter and then watch this repo looking at each change and cherry-picking what to merge in?
Thank you
