### ISSUE TITLE
Not rebuilding on edit or creation of a product. 

### ISSUE THREAD

**Issue by ogriffithjones** [vercel/commerce#93]
After adding a product in big-commerce I can see it in the search and on the home page, however when I try to view the product e.g. /product/chair it returns a 404.

After ReDeploying manually it is now there and doesn't give a 404.

**Comment by ogriffithjones** [comment]
Fixed title or accurately represent the issue.

**Comment by okbel** [comment]
This should do it. Thank you!!!! https://github.com/vercel/commerce/pull/100
