### ISSUE TITLE
Docs: Locale working on Products.

### ISSUE THREAD

**Issue by 9Shuck** [vercel/commerce#947]
### What is the improvement or update you wish to see?

I would like to know how to handle locate for Products.

### Is there any context that might help us understand?

The app gives an example of how to handle the locate with the i18n widget. So I could do it on Navbar, Hero, Marquee and all of them that don't work with the products.

The problem comes when I try to handle this on Products. I'm not able to apply different languages to names, description, etc...

**Comment by leerob** [comment]
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
