### ISSUE TITLE
After Swell outtage on 6th of april huge amount of requests made in the background

### ISSUE THREAD

**Issue by BelphegorPrime** [vercel/commerce#961]
### Describe the feature you'd like to request

https://swell.is had an outtage on the 6th of april, that resulted in >400GB/hr in server side requestdata. That is an  avoidable amount and hardly accceptable

### Describe the solution you'd like

 detect if commerce has an outtage and don't fetch things that often in the meantime.

### Describe alternatives you've considered

Do it on my own, but i would like that to not happen to others, even if they use other providers.

**Comment by BelphegorPrime** [comment]
![image](https://user-images.githubusercontent.com/3178520/230797393-3ecfb963-2ada-4cc2-9b07-ba6005131a16.png)
Here you can see good how much that was.

**Comment by leerob** [comment]
Hey there! Thank you for your contribution. We have decided to take Next.js Commerce in a new direction and will be closing out current PRs and issues due to this change. Please see this PR for more details: https://github.com/vercel/commerce/pull/966
