### ISSUE TITLE
Update the demo with v2

### ISSUE THREAD

**Issue by leerob** [vercel/commerce#968]
While we have merged code for v2, we are working to create a demo Shopify store for easier cloning and deploying. You currently need to provide the environment variables outlined in the `.env.example` file.

```
SHOPIFY_STOREFRONT_ACCESS_TOKEN=
SHOPIFY_STORE_DOMAIN=
SHOPIFY_REVALIDATION_TOKEN=
```

**Comment by iamzifei** [comment]
What is the SHOPIFY_REVALIDATION_TOKEN used for? I cannot see any reference in the code.  Also, the code is functionally broken, as the homepage hasn't completed.

**Comment by manovotny** [comment]
@iamzifei I am actually removing it in #974. It's not needed currently. Eventually it will be re-added when on-demand ISR is ready and documented.

**Comment by ckkamine** [comment]
Thank you for moving to this v2, I find the v1 more complex and easy to understand without documentation.
I'm still working with the v1, I hope to move to this new version very soon, it seems to give us more possibilities.
Thank you again guys for this incredible work.

**Comment by iamzifei** [comment]
Is there any roadmap or timeline about when the V2 will be the working version and replace the current demo site?

It would also be good if we could have Shopify Admin API options that allow writing data in some circumstances.

**Comment by leerob** [comment]
- v2: https://demo.vercel.store
- v1: https://commerce-v1.vercel.store
