### ISSUE TITLE
One-page checkout via vercel and bigcommerce - Not Found error

### ISSUE THREAD

**Issue by David05500** [vercel/commerce#988]
I just migrated the storefront to nextjs and hosted it on vercel. After this my one-page checkout is giving me the following error 
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/26745120/234108786-c5601dc3-7ccc-48e8-97b5-b811bb4aaa80.png">

I am a bit out of ideas now, if anyone knows how to fix it, would be a massive help!

**Comment by leerob** [comment]
Hey there, I think this might be different than what this template is providing (I see you have `cart.php`, which is not related to this code base). Could you double check this was intentional? 🙏
