### ISSUE TITLE
Does this work on the Shopify Starter plan?

### ISSUE THREAD

**Issue by manovotny** [vercel/commerce#992]
<div type='discussions-op-text'>

<sup>Originally posted by **cvoadmin** March 21, 2023</sup>
https://shopify.com/starter</div>

**Comment by leerob** [comment]
Looking at the landing page + docs, it is not clear if the starter plan supports using Shopify headless.

**Comment by doppiaesse** [comment]
No, it doesn't. Tried today, when you try to add the Headless App it tells you that you need Basic or higher
