### ISSUE TITLE
Great Job: quick question

### ISSUE THREAD

**Issue by manovotny** [vercel/commerce#993]
<div type='discussions-op-text'>

<sup>Originally posted by **osseonews** April 18, 2023</sup>
Awesome new repo! Thanks so much. This is a much better path forward, as there is no need to develop something for each provider, as it's trivial to create a new provider with a fork.

Anyway, my question is: Will you be adding Authentication as you had in the prior V1 repo? Not sure how to set that up with the App folder. Also, when the customer is logged in, how to properly get their data with App folder? i.e. useCustomer hook is implemented how?

</div>

**Comment by leerob** [comment]
We will not be adding auth here, but it could definitely be extended / forked / modified to support auth! We are also working on improved documentation for handling auth with the App Router 👍
