### ISSUE TITLE
Add to Cart Significantly Slower on V2

### ISSUE THREAD

**Issue by manovotny** [vercel/commerce#995]
<div type='discussions-op-text'>

<sup>Originally posted by **osseonews** April 24, 2023</sup>
When comparing the Add to Cart on V1: https://commerce-v1.vercel.store/ vs V2: https://demo.vercel.store/ the performance difference is drastic. V1 is much faster and the actual sidebar cart renders quickly, and correctly. V2 is slow and the cart takes quite some time to render the actual prices in the sidebar cart and other UI elements. On our tests, sometimes actually nothing even updates when you add to the cart and then the data pops in minutes later. </div>

**Comment by itsanishjain** [comment]
I agrees, any finding @manovotny why it's happening? and what are the possible solutions

**Comment by leerob** [comment]
Going to close this one out, but the solution we'd want to add here is optimistic UI: https://nextjs.org/docs/app/building-your-application/data-fetching/forms-and-mutations#optimistic-updates
